### ISSUE TITLE
Unable to login with Alpha version 

### ISSUE THREAD

**Issue by csamolot** [haiwen/seadroid#1000]
I'm unable to login with the new alpha version. Keeps saying wrong password. I uninstalled and reinstalled the stable version and I'm able to login no problem.

**Comment by zhwanng** [comment]
![Screenshot_20240502_042845_Seafile.jpg](https://github.com/haiwen/seadroid/assets/48609908/4ddcaff3-f381-4415-8a68-bcfa504ef52d)

this page？

**Comment by csamolot** [comment]
Yes, that exact page

**Comment by Rescue9** [comment]
I had the same problem last night when trying. I found that the two-factor authentication never shows and it just fails with a "wrong password" error.

**Comment by zhwanng** [comment]
i will test it.

**Comment by Rescue9** [comment]
Hey @zhwanng, what's the status on this? I'd like to get back into building and testing, but can't go without 2FA. Thx!

**Comment by zhwanng** [comment]
We're doing internal testing and will be releasing it soon, probably in a week or two or so

**Comment by zhwanng** [comment]
Is it possible to update to v3.0.1-beta and try it again?

**Comment by Rescue9** [comment]
2FA now works in this version. This can be closed.
