### ISSUE TITLE
3.0.0 Alpha版本还是未解决2.3.4版之后产生的不能自动打开下载文件的问题。

### ISSUE THREAD

**Issue by punkzhang** [haiwen/seadroid#1003]
比如下载一个word文档，不能自动调用app打开。下载一个apk，不能自动跳出安装界面。
最后一版正常的版本是2.3.3。
在seafile论坛也反映过同样问题，回复我说3.0.0会着手解决。
请掌握。

**Comment by zhwanng** [comment]
你那个是什么型号手机？

**Comment by punkzhang** [comment]
一台华为，一台小米。都是同样的问题。下载云里apk之后，不会弹出安装界面（安装器）。

**Comment by zhwanng** [comment]
除了 apk，其它文件应该都是可以打开的吧

**Comment by punkzhang** [comment]
是的，目前测试情况是这样。

**Comment by zhwanng** [comment]
下载一下v3.0.1-beta试试呢？

**Comment by punkzhang** [comment]
> 下载一下v3.0.1-beta试试呢？

第一时间就下载安装了。情况说明一下：
1. doc, mp4之类的文件都能正常拉起app打开。
2. apk无法拉起安装器。会在通知栏产生一个提示，说xxx.apk下载完成。点进去是安卓自带的文件管理器，能显示该apk但不能点击安装。需要安装还是要用第三方的文件管理器（或者手机品牌方的）
3. 到目前为止，能完美实现这个功能的，还是2.3.3。
4. 冒昧问问，鸿蒙next有没有适配的进度啦？手持华为机器深感不安。

**Comment by zhwanng** [comment]
关于第2、3 点，因为 google play 不允许 seadroid app 使用安装应用的权限，所以只能让用户自己选择安装方式。2.3.3之后的版本应该都是不能直接安装app的。
第 4 点，目前还没有鸿蒙的开发需求和计划。但也不排除对增加鸿蒙的支持。

**Comment by punkzhang** [comment]
收到，感谢你们一直以来的付出。期待在鸿蒙NEXT上继续用上seafile。（其实我估计并不难(●'◡'●)）
