### ISSUE TITLE
Change the user agent

### ISSUE THREAD

**Issue by sheosi** [haiwen/seadroid#1006]
I've tried using Google's OAuth for authenticating through a reverse proxy and passing that to seafile. It works except that on the app it fails due to google blocking the user agent of webkit browsers, there's a solution here:

[](https://stackoverflow.com/questions/43972730/getting-403-disallowed-user-agent-in-auth0-lock-for-android)

**Comment by zhwanng** [comment]
https://github.com/haiwen/seadroid/pull/998

**Comment by sheosi** [comment]
Thank you. And thanks for the good work.
