### ISSUE TITLE
seafile 2.3.4/android 13 - weird upload statuses

### ISSUE THREAD

**Issue by xfourat** [haiwen/seadroid#1007]
I'm waiting for my Camera gallery to get uploaded using the seafile android app, I'm getting weird issues, gallery does not sync and when I go to Transfer List I get:

1. Files in "Upload canceled" with no visible issue/error ... while my connection is stable and have no issue on seafile backed,
2. Sometimes the "upload list" tab go blank as if there were no queued uploads at all ...

**Comment by zhwanng** [comment]
with your feedback, we can't know the exact problem. However, in the next version, the exception message will be displayed in the transmission list page.

**Comment by xfourat** [comment]
Is upgrading to 2.3.6 useful ?
