### ISSUE TITLE
Seadroid 2.3.6 crashes when opening a file

### ISSUE THREAD

**Issue by benjamin-rota** [haiwen/seadroid#1008]
Hi,

I updated my Seafile Android client to 2.3.6 via the Play Store, on Android 12.
Since then the app crashes when trying to open a file. 

I tried to empty cache and data, remove and reinstall app, without success.

Reverting to version 2.3.5 solved the issue.

**Comment by zhwanng** [comment]
is PDF or other text-document?

**Comment by benjamin-rota** [comment]
I encountered the issue with PDF, ODT and DOCX.

Didn't try another type of document before reverting.

**Comment by raubjan** [comment]
i get this when try to open kdbx files

**Comment by tvwenger** [comment]
I am also experiencing this issue with .kdbx (keepassxc password database) files. The client crashes when trying to open the file. Furthermore, the keepassxc client fails to read/write the file. 

Files with extensions .txt, .py, and .jpg open without issue.

The client also crashes when opening .pdf, and (text) files without an extension.

**Comment by tvwenger** [comment]
Also failing: .xlsx 

Not failing: .png

**Comment by tvwenger** [comment]
Downgrading to 2.3.5 resolves the issue.

**Comment by zhwanng** [comment]
This issue is a crash caused by not getting the system-supported file formats correctly, please wait for a new version to be released

**Comment by zhwanng** [comment]
Is it possible to test this release?
[seadroid-v2.3.7](https://dev.seafile.com/seahub/f/1aecc488f1e24066a207/?dl=1)

**Comment by benjamin-rota** [comment]
This release solved the issue on my side (test ok with pdf, docx, odt)
Thanks !

**Comment by zhwanng** [comment]
> This release solved the issue on my side (test ok with pdf, docx, odt)
> Thanks !

thanks !

**Comment by raubjan** [comment]
got the new version via play store and works again to open .kdbx files. thx
