### ISSUE TITLE
V2.3.6 not connecting to server

### ISSUE THREAD

**Issue by mister78** [haiwen/seadroid#1009]
Unknown error is the Message. Server Version is 6.0.9.

**Comment by zhwanng** [comment]
Can you provide some detailed logs or screenshots?

**Comment by mister78** [comment]
The Screenshot looks like this.
But i Do not know wheel to find logs in the seadroid app.
I also checken the V3.0 available on fdroid, this does not work either. V2.3.5 is working.
I am using a samsung s10e with Android 12.
![IMG-20240529-WA0000](https://github.com/haiwen/seadroid/assets/36990973/63294dcb-d0bb-4b30-a4fb-4fe0eac4ace9)

**Comment by mister78** [comment]
Wronf click

**Comment by mister78** [comment]
The Screenshot looks like this.
But i Do not know wheel to find logs in the seadroid app.
I also checken the V3.0 available on fdroid, this does not work either. V2.3.5 is working.
I am using a samsung s10e with Android 12.
![IMG-20240529-WA0000](https://github.com/haiwen/seadroid/assets/36990973/b5dd2a8f-5e9c-477c-9ed6-ed483acaf5ca)

**Comment by mister78** [comment]
T

**Comment by tklepzig** [comment]
I'm having the same issue (see screenshot above), I can't connect to any seafile server from any android device, this is literally breaking my whole seafile infrastructure. Unfortunately, I cannot downgrade to a previous version.

**Comment by zhwanng** [comment]
Is it possible to update to v3.0.1-beta and try it again?

**Comment by mister78** [comment]
Yes, if it is possible to upload the Testversion to the fdroid Story, I can check it ...

⁣ ​

**Comment by zhwanng** [comment]
Fdroid will be automatically built, please wait for its completion

**Comment by mister78** [comment]
Just to be sure, until now, I do not see a newer version in the fdroid repo than 3.0.0 from may

⁣

**Comment by zhwanng** [comment]
can test v3.0.5 again?

**Comment by bashir-abdelwahed** [comment]
it is better to use solid explorer via webdav extension. It works flawlessly

**Comment by freeplant** [comment]
The new version 3.0.6 has been uploaded to Google Play store. If you still have the problem, just open a new issue for version 3.0.
