### ISSUE TITLE
Unknown error when logging in with 3.0.0-alpha

### ISSUE THREAD

**Issue by toasterking** [haiwen/seadroid#1014]
When I try to log in using seadroid client 3.0.0-alpha, "Unknown error" is displayed. If it revert back to 2.3.5, it works fine. Seafile server version is 5.0.3. 
![Screenshot_20240617-023918~2](https://github.com/haiwen/seadroid/assets/12618800/845390c1-ff0c-4594-8444-295a7db4f104)

**Comment by zhwanng** [comment]
please update to v3.0.1-beta and try it again

**Comment by toasterking** [comment]
The "Unknown error" is fixed in 3.0.1-beta, but I still cannot display libraries.

If I use https, it does not like my self-signed certificate (does not give the option to trust despite security issues).

![Screenshot_20240701-102059~2](https://github.com/haiwen/seadroid/assets/12618800/bd5aa510-93c4-4533-9e28-f357bdb3fdc8)

If I use http, the initial communication with the server completes, but it does not display libraries and shows a "Not found" flash message.

![Screenshot_20240701-102606~2](https://github.com/haiwen/seadroid/assets/12618800/e96d49db-2b7b-4253-955c-be15cd130318)
![Screenshot_20240701-102136](https://github.com/haiwen/seadroid/assets/12618800/f49cfdc6-d0e0-410c-827d-9c079f3fe7cc)

**Comment by zhwanng** [comment]
you can upgrade to the latest version and retry it.
