### ISSUE TITLE
Unable to list libraries in 2.3.6/2.3.7

### ISSUE THREAD

**Issue by toasterking** [haiwen/seadroid#1015]
I get "Error when loading libraries" on seadroid 2.3.6 and 2.3.7. I can create a library with seadroid and see it in the Web UI, but it still does not display in seadroid. Downgrading to 2.3.5 fixes it. Seafile server version is 5.0.3.

This is also mentioned in issue #1013, but the initial report there appears to be about a different (but possibly related) problem.

![Screenshot_20240617-021940](https://github.com/haiwen/seadroid/assets/12618800/fb4d19be-350f-48c8-aec1-d9dacc3c1acc)

**Comment by zhwanng** [comment]
Is it possible to update to v3.0.1-beta and try it again?

**Comment by toasterking** [comment]
It does not work in 3.0.1-beta, either.

If I use https, it does not like my self-signed certificate (does not give the option to trust despite security issues).

![Screenshot_20240701-102059~2](https://github.com/haiwen/seadroid/assets/12618800/bd5aa510-93c4-4533-9e28-f357bdb3fdc8)

If I use http, the initial communication with the server completes, but it does not display libraries and shows a "Not found" flash message.

![Screenshot_20240701-102606~2](https://github.com/haiwen/seadroid/assets/12618800/e96d49db-2b7b-4253-955c-be15cd130318)
![Screenshot_20240701-102136](https://github.com/haiwen/seadroid/assets/12618800/f49cfdc6-d0e0-410c-827d-9c079f3fe7cc)

**Comment by toasterking** [comment]
> Are you on the latest version of Seafile? I ran into this issue as well because Unraid's app section lists an old 2019 version as official, and that only works with up to 2.3.5 of this app.

No, my Seafile server version is 5.0.3 (which I think I stated) and is not even remotely close to the latest.  Thank you for the tips, but I cannot change the server version right now due to hardware and OS limitations.

**Comment by zhwanng** [comment]
Is the server's SSL certificate self-signed?

**Comment by zhwanng** [comment]
The use of self-signed certificates on servers is no longer recommended. if possible, SSL certificates provided for free by third-party platforms can be used.

**Comment by toasterking** [comment]
Was it decided that this bug will not be fixed? My problem with 3.0.1-beta is due to the self-signed certificate, but the problem with 2.3.7 is different and seemingly unrelated.

**Comment by toasterking** [comment]
Also mentioned as secondary issue in #1013 and does not appear resolved there.

**Comment by freeplant** [comment]
If there is another issue, please open a new dedicated issue. So that we can better check the problem.

**Comment by toasterking** [comment]
This issue I opened here is for the problem listing libraries in Seadroid 2.3.7. It does not seem related to the inability to use self-signed certificates in Seadroid 3.0.1-beta. I suspect that the latter was conflated with the former and was the reason for closing this issue, when the former was not actually resolved nor addressed.

**Comment by freeplant** [comment]
Since we are going to release 3.0.3 on Google Play Store soon, we will on longer maintain 2.3.7. Is it possible for you to upgrade your Seafile server and use Android client version 3.0.3?
