### ISSUE TITLE
[3.0.1] App not responding

### ISSUE THREAD

**Issue by virusperfect** [haiwen/seadroid#1017]
The app immediatly crashes when opening it on my Fairphone 4 5G. This is only happening with version 3.0.1.

**Comment by zhwanng** [comment]
thanks for your feedback. I will check logs.

**Comment by zhwanng** [comment]
Please update on the latest release, and try it again.

**Comment by zhwanng** [comment]
please update on the latest release, and try it again

**Comment by virusperfect** [comment]
Yes, thank you for the quick response, it works now!
