### ISSUE TITLE
自签证书设置https后，网页端可正常预览图片和视频，安卓端无法预览图片和视频

### ISSUE THREAD

**Issue by Oiuiuiu** [haiwen/seadroid#1018]

**Comment by zhwanng** [comment]
目前正在修复这个问题了，请等待下个发布

**Comment by zhwanng** [comment]
android 新版本已经升级了更加严格的自签证书校验策略，证书验证不通过则不会正常使用 app，你可以从第三方平台获取免费 的SSL证书部署到服务器。也可以降级到 v2.x.x 版本继续使用
