### ISSUE TITLE
3.0.1-beta没有关闭验证证书的选项

### ISSUE THREAD

**Issue by Oiuiuiu** [haiwen/seadroid#1019]
自签证书设置的https无法登陆

**Comment by Oiuiuiu** [comment]
![S40709-16221771_com.android.systemui.png](https://github.com/haiwen/seadroid/assets/99924636/3325c457-ae30-4f80-b755-b26e50c9878b)

还有上传文件显示超额，网页端正常

**Comment by zhwanng** [comment]
> ![S40709-16221771_com.android.systemui.png](https://private-user-images.githubusercontent.com/99924636/346877447-3325c457-ae30-4f80-b755-b26e50c9878b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDM5MDksIm5iZiI6MTcyMTgwMzYwOSwicGF0aCI6Ii85OTkyNDYzNi8zNDY4Nzc0NDctMzMyNWM0NTctYWUzMC00ZjgwLWI3NTUtYjI2ZTUwYzk4NzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA2NDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZGM2MWZjZDVmM2EyNzk2M2EyZDc0NTAxMmMwZTI4NzI2NWE1ZWFjNmJiM2ZiNGNmYzk3MzhiMWZlYTMzMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wLX728cVXWokrO63ilhm2jneCXm2tis57VudoRhdYgE)
> 
> 还有上传文件显示超额，网页端正常

等 v3.0.2 再试一下

**Comment by zhwanng** [comment]
> 自签证书设置的https无法登陆

新版android 端升级了自签证书策略，从 v3.0.2 开始将严格校验自签证书，不允许自签证书了，可以去第三方平台免费生成一些证书。
