### ISSUE TITLE
Downloading over previous file breaks significantly.

### ISSUE THREAD

**Issue by Rescue9** [haiwen/seadroid#1022]
Downloading over a previous file in seadroid is broken. When trying to download over a previous file without deleting, it downloads about 50k worth of data, then says download is finished, but data is corrupted. I've tried various combinations of clearing the cache in the app, clearing the cache from the android apps settings, deleting the file manually via a file browser, etc. 

I think this may be an issue with slow / poor network connections and keeping the security passwords. As I was sitting here writing out this bug, I couldn't get it to crash, but at work where I'm on LTE cell service, it crashes constantly.

**Comment by Rescue9** [comment]
This is not an issue with slow networks. I've been dealing with this for weeks now. I'm finding this only happens in folders that have password protection. I've tried deleting the password, logging out of the Seafile account, manually deleting the file in a different app and re-downloading. Nothing is seeming to work. 

Two things should be implemented:
First, the ability to choose to save library passwords or not. If the app automatically saves passwords, then testing for problems is a pain because I always have to go to settings and clear the library password.
Second, selecting Download Now should ALWAYS re-download the file; no checking if it exists, no checking if it's the same size, etc.... just download the file over the existing one. I can see managing file version clashes when clicking on the filename to re-download, but manually selecting Download Now is a conscious action to get the specific version that is on the server.

**Comment by zhwanng** [comment]
We've optimized some of the logic for this feature. However, we have not encountered and reproduced this issue, you can upgrade to the latest version

**Comment by Rescue9** [comment]
This is still an issue. I can't tell if it is due to saved logins or what, but I had to revert to 2.3.6 again just to be able to download my keepass file. Very frustrating.

Once again
 The download now option should supercede everything else.
