### ISSUE TITLE
Android not uploading phone photos

### ISSUE THREAD

**Issue by plaindocs** [haiwen/seadroid#1024]
Hi Folks,

I'm using Seafile (2.3.7) on an up to date OnePlus 10 Pro, syncing with my self hosted community edition. 
I've turned on Camera Upload, and customized the folders. However, the `DCIM` folder in the Library where my phone stores photos is empty.

There is an old `Camera` directory from a previous phone, photos from 2020, all good. 

But nothing from this year in `DCIM\Camera`

Any suggestions?

**Comment by zhwanng** [comment]
can try the v3.0.x release?

**Comment by plaindocs** [comment]
OK, I'm now running 3.0.0 from F Droid, and it doesn't look like there is any change. 

- `DCIM` folder on Seafile `last updated` does change, but still shows no contents
 
- Digging in to the file details on the phone, recent pics are in `/storage/emulated/0/DCIM/Camera/....` 
- That has the same contents as `Internal storage/DCIM/Camera`
- Neither of these are findable in the custom Folder Camera upload settings

**Comment by plaindocs** [comment]
hmmm, now I'm getting an "Out of quota" message, which I know isn't the case. (I just uploaded and deleted a 2GB file from my desktop to make sure).

Might be this? https://github.com/haiwen/seadroid/issues/1001 I'll updated

**Comment by plaindocs** [comment]
Looks fixed! :tada: :tada:
