### ISSUE TITLE
[3.0.2-pre] Folder jumps to root on screen rotation

### ISSUE THREAD

**Issue by yvtr** [haiwen/seadroid#1025]
Actual: you rotate the device while you are in a subfolder: the displayed folder switches to root directory.
Expected behaviour: remain in the last viewed subfolder.

Tested on: Huawei P20 (arm64-v8a, Android 10, SDK 29)
App installed from F-Droid

**Comment by zhwanng** [comment]
please bump to v3.0.3 and retry it.

**Comment by yvtr** [comment]
Bug fixed in v3.0.3
