### ISSUE TITLE
Photo take upload file name improvment

### ISSUE THREAD

**Issue by looric** [haiwen/seadroid#1038]
the current name is similar to sf_photo_1732687893.jpg

To make the photo naming convention more intuitive and date-recognizable, you can modify it as:

**Format: %y%mo%d_%unix.jpg
Example: 20241127_1732687893.jpg**
Why it's better:

    Readable Date: The date comes first, making it easy to recognize when the photo was taken.
    Unique Identifier: The Unix timestamp ensures each photo name is unique.
    Compatibility: It remains simple and compatible with various systems.

Updated Implementation Logic:

**Instead of sf_photo_<timestamp>.jpg, generate names as:**

    Extract the date in %Y%m%d format from the Unix timestamp.
    Append the original Unix timestamp for uniqueness.
    Combine them to form the final filename.

**Comment by zhwanng** [comment]
tks to your feedback, this feature will be updated.
