### ISSUE TITLE
Cannot download files with blanks in filename

### ISSUE THREAD

**Issue by ThomasA94** [haiwen/seadroid#104]
Hi,
when a filenames contains a blank there is the error: The file "xxxx.x" has been deleted 
This error occurs only when the filename contains blanks.

Newest app version
Newest seafile server version.
Webserver is IIS on a Windows 2012 system
Tested on Android clients: Galaxy S4 with CM11, Galaxy S4 with Samsung Rom, Galaxy Note 10.1 (2012) Samsung Rom.
Using https, of course

We want to migrate our pictures from dropbox to seafile, but with this error we cannot use seafile. Every filename contains space characters.

**Comment by Logan676** [comment]
It's related to IIS. You need to enable "double escaping" as explained here: http://technet.microsoft.com/en-us/library/hh831621.aspx

see the original answer from [here](https://groups.google.com/forum/#!topic/seafile/LBBe2quCwuk)
