### ISSUE TITLE
[Feature Request] Tag-Support for App

### ISSUE THREAD

**Issue by marolaro** [haiwen/seadroid#1044]
Seafile Server supports tags in web interface. So even when I don't have Pro-Version with elasticsearch installed I can search my files through tags in Web Interface.

But in the app this is not possible and I have no option to search any files (Except the function to search in one folder WITHOUT subfolders) . I always have to search in all folders. So is it possible to bring Tags into the app? This would be a great help.

**Comment by freeplant** [comment]
We are going to redesign tags feature in version 13.0. After that we will add tags support in mobile too.

**Comment by marolaro** [comment]
Thank you for your answer, this is great! Is it planned when implemanting this feature to take over the old tags in the old system into the new system? So that I don't have to re-tag all thousends of files...🙃

**Comment by freeplant** [comment]
Yes, we will add a migrate method for old tags.
