### ISSUE TITLE
Auto-upload videos too

### ISSUE THREAD

**Issue by jbbr** [haiwen/seadroid#112]
Thank you for adding the camera upload feature!
It would be great if it would be possible to upload videos too. As videos require much more space, a toggle in the preferences might be a good idea instead of enabling it by default.

**Comment by resuser** [comment]
When adding this feature, please create a seperate option for uploading over 2G/3G/4G, or allow an option to only upload files smaller than xx file size on 2G/3G/4G.  This is the only reason I still use my dropbox account.  They allow you to upload smaller files over 2G/3G/4G immediately, but wait until you're on WiFi to upload larger files such as videos.

**Comment by Logan676** [comment]
thanks for your comment, will take that into consideration.
