### ISSUE TITLE
get photo path from external SD card

### ISSUE THREAD

**Issue by Logan676** [haiwen/seadroid#140]
Seadroid 1.2 only supports uploading photos from primary external storage not the secondary external storage. That\`s to say.  
- [x] if the device only has one emulated external storage (on-board flash), camera upload service can scan photo directories on it correctly.
- [x] if the device only has a removable storage (like SD card), camera upload service can scan photo directories correctly as well. So far so good.
- [x] if the device both has a emulated external storage and a removable storage, camera upload service only scans photo directories on the emulated external storage (primary storage), but a majority of users  save their photos to the 32G or bigger size removable SD card (secondary storage) which will be ignored by Seadroid 1.2. That\`s where problem comes in.

**Comment by schokonsti** [comment]
The paths seem to be available as environment variables this is what I found here:
http://stackoverflow.com/a/25196520
`System.getenv("EXTERNAL_STORAGE")` will give you the external storage's path (e.g. `/sdcard`)
`System.getenv("SECONDARY_STORAGE")` will give you the secondary external storage's **paths** separated by `:` so you should split it before working with it.

An implementation of that can be found in this function here (with emulated storage included): http://stackoverflow.com/a/18871043

You could offer the user a list with these path's as "Pictures Source".
