### ISSUE TITLE
let user choose which photo directories they want to upload

### ISSUE THREAD

**Issue by Logan676** [haiwen/seadroid#151]
preview
![20140124115941500](https://cloud.githubusercontent.com/assets/2975850/4912383/f40c5d4c-649c-11e4-9ce6-0aee249f4258.png)

**Comment by schokonsti** [comment]
There should be an option choose a custom path (e.g. `/storage/sdcard1/DCIM/Camera`). That would solve the issue with internal emulated sdcard0 and external sdcard1 #140.
Further there could be an option to check several folders for Camera Upload. That would also solve the WhatsApp images issue #255...

**Comment by Logan676** [comment]
@schokonsti I like your comment, and that\`s exactly what I am doing now.
Preview the patch.
![local_library](https://cloud.githubusercontent.com/assets/2975850/6223064/cefbecb6-b69a-11e4-80f0-6aa63acf1525.png)
![remote_library](https://cloud.githubusercontent.com/assets/2975850/6223065/cff45d60-b69a-11e4-8361-32ed4065400f.png)

**Comment by MiG29** [comment]
I assume this would also solve the issue where the contents of subdirs on the phone all get dumped into one upload directory?

**Comment by Logan676** [comment]
@MiG29 it probably not, because I plan to let user choose one remote upload directory. So files from multiple directories on SD card will be uploaded to one remote directory (all get dumped into one upload directory). 
see #274

**Comment by MiG29** [comment]
I'll start a new issue then.
