### ISSUE TITLE
[Feature] Mobile app PIN/PASS code access

### ISSUE THREAD

**Issue by soakes** [haiwen/seadroid#16]
Having a simple PIN or PASS method like dropbox for example has, would go a very long way to brining a little extra security in case your phone gets nicked.

Currently there is no simple way to tell if a mobile client has connected and downloaded any files. Clients list page in version 1.7 only displays sync based clients i.e. desktop app.  This means you can't revoke access.  This is another reason why I believe PIN or PASS method to open the app would be a great idea.

**Comment by Logan676** [comment]
this feature was implemented by "show gesturelock when resume from multitask window" #237
