### ISSUE TITLE
libraries layout messed up

### ISSUE THREAD

**Issue by logan676** [haiwen/seadroid#174]
When navigate into one library, which has a lot of folders , the layout of the folder list will be messy.
See screenshot below.
![layout_messed_up](https://cloud.githubusercontent.com/assets/2975850/5103372/3bb87b5a-7012-11e4-9fe8-9df92939081b.png)
Note: this exception is irregular which appears through multiple screen sizes and API level devices. Could reproduce it very easily.

**Comment by freeplant** [comment]
Good
