### ISSUE TITLE
Account password is exposed by keyboard suggestions

### ISSUE THREAD

**Issue by Asfaloth** [haiwen/seadroid#224]
When typing the password in the password field, the keyboard shows suggestions and exposes the entered password. I can add a screenshot of this problem later.

I'm using SwiftKey, but I think other keyboards have the same problem. Other apps that require a password doesn't have this affect, no suggestions are shown at all.

I think it can be solved by adding `edit_text.setInputType(InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS | InputType.TYPE_TEXT_VARIATION_PASSWORD);` in the method `setInputType` in class `CustomClearableEditText`.

**Comment by Logan676** [comment]
keyboard suggestion works quite differently due to different kind of IME installed. 
I can\`t reproduce it, so please show the screenshot, will disable the suggestion feature of the password text filed.

**Comment by Asfaloth** [comment]
![screenshot_2015-01-06-11-20-15](https://cloud.githubusercontent.com/assets/5488288/5627322/d1cf63b6-9596-11e4-8f24-6f4eb390e96f.png)

I can create a pull request with a fix once I'm home if you like.

**Comment by Logan676** [comment]
that\`s nice!
