### ISSUE TITLE
seadroid 1.4.0 crashes after every file download

### ISSUE THREAD

**Issue by monochromec** [haiwen/seadroid#231]
First observed on KK (4.4.2) but also happens on ICS (4.0.2).

Steps to reproduce:
1. Launch seadroid
2. Click on any file not in cache
3. App crashes after download
4. Doesn't happen with files already cached.

Log excerpt:

E/dalvikvm(26749): >>>>> com.seafile.seadroid2 [ userId:0 | appId:10278 ]
E/Parcel  (29226): Class not found when unmarshalling: com.seafile.seadroid2.account.Account
E/Parcel  (29226): java.lang.ClassNotFoundException: com.seafile.seadroid2.account.Account
E/Parcel  (29226): Caused by: java.lang.NoClassDefFoundError: com/seafile/seadroid2/account/Account
E/Parcel  (29226): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.seafile.seadroid2.account.Account" on path: DexPathList[[zip file "/data/data/de.robv.android.xposed.installer/bin/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime(26749): Process: com.seafile.seadroid2, PID: 26749
E/AndroidRuntime(26749):        at com.seafile.seadroid2.monitor.SeafileMonitor.onFileDownloaded(SeafileMonitor.java:57)
E/AndroidRuntime(26749):        at com.seafile.seadroid2.monitor.FileMonitorService$3.onReceive(FileMonitorService.java:134)
W/ActivityManager(29226):   Force finishing activity com.seafile.seadroid2/.ui.activity.FileActivity
W/ActivityManager(29226):   Force finishing activity com.seafile.seadroid2/.ui.activity.BrowserActivity
D/CrashAnrDetector(29226): processName: com.seafile.seadroid2
D/CrashAnrDetector(29226): broadcastEvent : com.seafile.seadroid2 data_app_crash
I/ActivityManager(29226): Process com.seafile.seadroid2 (pid 26749) (adj 15) has died.
I/WindowState(29226): WIN DEATH: Window{4475dfa8 u0 com.seafile.seadroid2/com.seafile.seadroid2.ui.activity.BrowserActivity}
W/ActivityManager(29226): Service crashed 2 times, stopping: ServiceRecord{43bd1598 u0 com.seafile.seadroid2/.transfer.TransferService}
W/ActivityManager(29226): Service crashed 2 times, stopping: ServiceRecord{43bd1288 u0 com.seafile.seadroid2/.monitor.FileMonitorService}
W/ActivityManager(29226): Service crashed 2 times, stopping: ServiceRecord{43ba16f8 u0 com.seafile.seadroid2/.avatar.AvatarManageService}
I/WindowState(29226): WIN DEATH: Window{457b1790 u0 com.seafile.seadroid2/com.seafile.seadroid2.ui.activity.FileActivity}
V/ApplicationPolicy(29226): isApplicationStateBlocked userId 0 pkgname com.seafile.seadroid2
E/dalvikvm(26931): >>>>> com.seafile.seadroid2 [ userId:0 | appId:10278 ]

**Comment by Logan676** [comment]
Thanks for your reply, we already fixed this bug in 1.4.1, please update your client to the latest version.

**Comment by monochromec** [comment]
Seems to work in 1.4.1 on both Android versions.

Closing the issue.
