### ISSUE TITLE
A question about the meaning of a string...

### ISSUE THREAD

**Issue by rcoss** [haiwen/seadroid#232]
In this string:
` <string name="lockscreen_access_pattern_passwd_forget">Forget password</string>`

Do you mean Forget or rather Forgot?
I couldn't find where in the code this string is used and what actions were to be executed.
Some of the translations at transifex mean Forget and others Forgot (according to Google's translate)
Reversing chinese translation: 忘记密码 gives us: Forgot password

Thanks,
Rodolfo

**Comment by lins05** [comment]
@Logan676 I think It should be "Forgot Password".

On Sun, Jan 11, 2015 at 1:26 AM, Rodolfo Cossalter <notifications@github.com

**Comment by Logan676** [comment]
yeah, exactly. I will change it to be `forgot password`
