### ISSUE TITLE
seadroid no Messenger function ?

### ISSUE THREAD

**Issue by mickeyboss123** [haiwen/seadroid#235]
seadroid no Messenger function ?

seafile-ios ↓
![s__11796485](https://cloud.githubusercontent.com/assets/1274528/5695633/ee31a91a-99e7-11e4-92f7-23a42a8dbcf3.jpg)

**Comment by Logan676** [comment]
maybe it\`s much better if user can integrate a third party instant communication tools according to their specific needs.

**Comment by shoeper** [comment]
I don't need this but I'd think it is a nice feature. Espacially in Germany where companies cannot just use some messenger for sensitive data. The self hosted one could afaik securely used.
