### ISSUE TITLE
Password Bug?

### ISSUE THREAD

**Issue by eLement87** [haiwen/seadroid#236]
Hello,

recently i've installed the latest Version of Seafile on my Android Device, also updated my Server to 4.0.4.
Now i have strange problems. 
My Tablet is running the newest Version of Seafile for Android - 1.4.1 - and the Login process works without problems. But with my smartphone(1.4.1) I can't login. They said: Wrong Username / Password

I found the problem in my Password, there is a special Character like !%$§ - without and with normal Letters and Numbers - the connection work.

I have changed my password for now, but... ;)

Thank You and Best Regards
Ben

**Comment by lins05** [comment]
So you have tried logging in with the same account on both your tablet and
smartpone, but one suceeded while the other failed?

**Comment by eLement87** [comment]
Yes, with the same credentials.
The Server Log says a *Bad Request* from my Smartphone.

**Smartphone:**
`"POST /api2/auth-token/ HTTP/1.1" 400 264 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; GT-I9505 Build/KTU84Q)"`

**Tablet:**
`"POST /api2/auth-token/ HTTP/1.1" 200 84 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; K00C Build/KTU84Q)"`

With a dirty trick it also works on my smartphone... i've copied the *account.db*  from my Tablet `/root/data/data/com.seafile.seadroid2/databases/account.db` to my Smartphone.

With a new account and same password the error occurs as well.

**Comment by Logan676** [comment]
Do you have this error with the older version. If it is convenient to you, please test it with 1.3.1 because we didn\`t modify login module in 1.3.1. You can get the apk from [here](https://dev.seafile.com/seahub/f/7d3116cda0/).

**Comment by eLement87** [comment]
Thanks for your reply. 
I've installed 1.3.1 and it works out of box without complication (Password with special characters).
`"POST /api2/auth-token/ HTTP/1.1" 200 84 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; GT-I9505 Build/KTU84Q)"`

After 1.3.1 i've updated to 1.4.1 over the Play Store and "bam" it works too. 
But with new Account it's still the same problem with special characters in 1.4.1.

Anyway with this Workaround, it works ;)
Thanks

**Comment by Logan676** [comment]
Unfortunately, I reproduced this error with on lucky. BTW, I could\`t find such a symbol "§" on my keyboard. So I copied and pasted it via Genymotion virtual device on my laptop and register an account with password like "!%$§", turned out I can login successfully. 

So I wonder if I reproduced the same way as you did? As you mentioned above, it works find on 1.3.1 but 1.4.1, so it maybe a bug introduced to 1.4.1.

**Comment by caschual** [comment]
I have a similar problem. I can access seafile through various channels (Windows Client, iPhone Client, Windows WebBrowser, Android WebBrowser), but NOT Android Client. Here it keeps on refusing access.

The problem occurred first when I enabled SSL, before that via HTTP the android version worked also fine. Now it keeps saying "Wrong Email or Password", although I'm absolutely sure that the credentials are correct.

Version Android Client 1.3.1 did not fix the problem. A simple password with chars and digits neither.

Are there any news?

Cheers

**Comment by Fendorn** [comment]
I had one case where password "seee??433" did not work but just on "Android 4.4.2; GT-I9505 Build" (e.g. Samsung S4)
POST /api2/auth-token/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.4.2; GT-I9505 Build/KOT49H)
Host: 11.22.33.44:8000
Connection: Keep-Alive
Accept-Encoding: gzip
Content-Length: 161
=>
username=some-user%40gmx.net&password=seee%3F+%3F433&platform=android&device_id=a12b12c12d12e12f&device_name=GT-I9505&client_version=1.4.1&platform_version=4.4.2
HTTP/1.1 400 BAD REQUEST
Note: IP, user and device_id anonymized.

Ich simply resetted the password for this user and seafile generated a password only with letters (upper and lower) and digits, but no more special sign AND it worked !

**Comment by bjoernr-de** [comment]
@Fendorn if you url decode your password (&password=seee%3F+%3F433) it is "seee? ?433" so there's a space between the question mark.

Android's default character after a question mark is a blank space (in a textfield). 
The url encoded password looks like this happened to you.

**Comment by shoeper** [comment]
It's a bug in at least the samsung keyboard. They also include a blank after a question mark in password fields without auto-completion.

**Comment by caschual** [comment]
I again tried a really simple password, small letters and digits and at now the "BAD REQUEST" error disappeared. The Apache log now writes no error.log anymore but in vhost_access.log:

my-domain:443 80.187.123.123 - - [02/Feb/2015:23:22:42 +0100] "POST /seafile/api2/auth-token/ HTTP/1.1" 400 730 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; A0001 Build/KTU84Q)"
my-domain:443 80.187.123.123 - - [02/Feb/2015:23:22:43 +0100] "POST /seafile/api2/auth-token/ HTTP/1.1" 400 730 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; A0001 Build/KTU84Q)"

But the app still says "Wrong Email or Password", althought definitely the right combination.

Any more ideas?

**Comment by bjoernr-de** [comment]
@caschual Is this password/your seafile instance definitely working on other platforms?
I tried many passwords with my Seafile instance and everything worked on Android.

**Comment by klemens** [comment]
I am not sure if this is related, but I could not login today with a fresh installation of version 1.4.2, whereas the linked 1.3.1 worked as expected.
The error message shown was that the certificate is not trusted, but the dialog box did not contain any information about the certificate (which actually is a proper cert that is trusted in the stock browser) and tapping accept just showed the same empty box again. There were no errors shown in logcat.

I am using a 60 character password that uses all characters from the following (regex) range: `a-zA-Z0-9&()>/#[]%{}-` Sou you could try to reproduce this issue with eg:
`}t%2wz6q89f]Sv&7(SQs#m7HD)M/pBm[5gQ{LJtYf}U-h>Vd&bi5rYUeVu#n`

I can do some more testing if you want.

**Comment by caschual** [comment]
So far nothing helped. The Windows client for instance works, browser interface as well.

I even tried password "a" with the Android client. Didn't work. Then I switched apache to debug mode. I saw that the username and password was correctly transmitted like "username=email%40domain.com&password=a", which works perfectly nice with the well known curl statement to test the token-thing (curl -k -l "username=email%40domain.com&password=a" mydomain/api2/auth-token).

BUT, when I took the full POST statement from the log:
curl -d "username=email%40domain.com&password=a&platform=android&device_id=6a33737a8962e422&device_name=A0001&client_version=1.4.2&platform_version=4.4.4" https://gizmo.dynpc.net/api2/auth-token/
I received this:
{"non_field_errors": ["invalid device id"]} 

The respective log as specified in /apis/serializers.py I coudn't find.

 # -----------------------------------------------------------
      f = open('/seahub/logs/erroneous_device_id.log','a+')
      f.write(device_id.lower()) # python will convert \n to os.linesep
      f.write(_ANDROID_DEVICE_ID_PATTERN)
      f.close() # you can omit in most cases as the destructor will call if
  # -----------------------------------------------------------

Anyway, I am not a RegEx expert, but 
_ANDROID_DEVICE_ID_PATTERN = re.compile('^[a-f0-9]{1,16}$')
IMHO matches with 6a33737a8962e422

Thanks
C.

**Comment by caschual** [comment]
So far nothing helped. The Windows client for instance works, browser interface as well.

I even tried password "a" with the Android client. Didn't work. Then I switched apache to debug mode. I saw that the username and password was correctly transmitted like "username=email%40domain.com&password=a", which works perfectly nice with the well known curl statement to test the token-thing (curl -k -d "username=email%40domain.com&password=a" mydomain/api2/auth-token).

BUT, when I took the full POST statement from the log:
curl -k -d "username=email%40domain.com&password=a&platform=android&device_id=6a33737a8962e422&device_name=A0001&client_version=1.4.2&platform_version=4.4.4" https://gizmo.dynpc.net/api2/auth-token/
I received this:
{"non_field_errors": ["invalid device id"]}

Any ideas? 

The respective log as written in /apis/serializers.py I coudn't find.

 # -----------------------------------------------------------
      f = open('/seahub/logs/erroneous_device_id.log','a+')
      f.write(device_id.lower()) # python will convert \n to os.linesep
      f.write(_ANDROID_DEVICE_ID_PATTERN)
      f.close() # you can omit in most cases as the destructor will call if
  # -----------------------------------------------------------

Anyway, I am not a RegEx expert, but 
_ANDROID_DEVICE_ID_PATTERN = re.compile('^[a-f0-9]{1,16}$')
IMHO matches with 6a33737a8962e422

Thanks
C.

**Comment by caschual** [comment]
So far nothing helped. The Windows client for instance works, browser interface as well.

I even tried password "a" with the Android client. Didn't work. Then I switched apache to debug mode. I saw that the username and password was correctly transmitted like "username=email%40domain.com&password=a", which works perfectly nice with the well known curl statement to test the token-thing (curl -k -l "username=email%40domain.com&password=a" mydomain/api2/auth-token).

BUT, when I took the full POST statement from the log:
curl -d "username=email%40domain.com&password=a&platform=android&device_id=6a33737a8962e422&device_name=A0001&client_version=1.4.2&platform_version=4.4.4" https://mydomain/api2/auth-token/
I received this:
{"non_field_errors": ["invalid device id"]}

Any ideas? 

The respective log as written in /apis/serializers.py I coudn't find.

 # -----------------------------------------------------------
      f = open('/seahub/logs/erroneous_device_id.log','a+')
      f.write(device_id.lower()) # python will convert \n to os.linesep
      f.write(_ANDROID_DEVICE_ID_PATTERN)
      f.close() # you can omit in most cases as the destructor will call if
  # -----------------------------------------------------------

Anyway, I am not a RegEx expert, but 
_ANDROID_DEVICE_ID_PATTERN = re.compile('^[a-f0-9]{1,16}$')
IMHO matches with 6a33737a8962e422

Thanks
C.

**Comment by freeplant** [comment]
Hi, I copied your statement and tried

```
curl -d "username=fr@163.com&password=p&platform=android&device_id=6a33737a8962e422&device_name=A0001&client_version=1.4.2&platform_version=4.4.4" https://cloud.seafile.com/api2/auth-token/
```

Works as expected.

From you log:

```
my-domain:443 80.187.123.123 - - [02/Feb/2015:23:22:42 +0100] "POST /seafile/api2/auth-token/ HTTP/1.1" 400 730 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; A0001 Build/KTU84Q)"
```

It should be GET request. How does it become a POST request? Maybe something wrong with your Apache configuration.

**Comment by caschual** [comment]
Are you sure about the POST request? According to the curl help the parameter -d specifies POST content. And it works without device information. For the simple curl request without device_id I can see that the POST request is working and Seafile responds with a token:

<pre><code>
curl -k -d "username=mail%40somain.com&password=a" https://mydomain/api2/auth-token/   
{"token": "e020e7942c4f9ba345667764fd6cd25117c594d5"}

Apache Log:
mydomain:443 remote_host - - [08/Feb/2015:13:31:03 +0100] - "POST /api2/auth-token/ HTTP/1.1" 200 2278 "-" "curl/7.22.0 (i686-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3"
</code></pre>

And now the same with the full statment including device_id:

<pre><code>
curl -k -d "username=mail%40somain.com&password=a&platform=android&device_id=6a33737a8962e422&device_name=A0001&client_version=1.4.2&platform_version=4.4.4" https://mydomain/api2/auth-token/  
{"non_field_errors": ["invalid device id"]}

Apache Log:
mydomain:443 remote_host - - [08/Feb/2015:13:45:31 +0100] - "POST /api2/auth-token/ HTTP/1.1" 400 2310 "-" "curl/7.22.0 (i686-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3"
</code></pre>

**Comment by lins05** [comment]
The android device id is valid as long as its a hex string of 1 - 16
characters long. See here (
https://github.com/haiwen/seahub/tree/739b32b02c4803448d5cb75b3e22ec0073930aed/seahub/api2/serializers.py#L24).


What is your server version?

**Comment by Fendorn** [comment]
@freeplant 
If you are not on the latest version you may have the issue with the ID validation code, see
https://github.com/haiwen/seahub/pull/181/files
for example. 
You can find the serializers.py file under <your installation>/seahub/seahub/api2/.
In version 4.0.5 the code is simply
{{{
        elif platform == 'android':
            # See http://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID
            # android device id is the 64bit secure id, so it must be 16 chars in hex representation
            # but some user reports their device ids are 14 or 15 chars long. So we relax the validation.
            if not _ANDROID_DEVICE_ID_PATTERN.match(device_id.lower()):
                raise serializers.ValidationError('invalid device id')

}}}
