### ISSUE TITLE
Chain certificates not supported

### ISSUE THREAD

**Issue by mathieu-mp** [haiwen/seadroid#242]
Solution given for https://github.com/haiwen/seafile-client/issues/208
breaks access from Seadroid (no error message but unable to access)

Using the certificate with no reference to the whole chain enables access from Seadroid but SSL Cert is not trusted as valid and user has to validate security warning.

**Comment by shoeper** [comment]
Again: chain certificates ARE supported. I'm using one successfully for month (startssl)

**Comment by mathieu-mp** [comment]
OK, I made it work with Apache2.
Have to use SSLCertificateChainFile, while SSLCAcertificatefile is not supported.
Chain Certificate can be checked at https://www.digicert.com/help/

My mistake, the issue is solved by server-side conf.
But Seadroid behaves as an obsolete browser regarding to SSL Certificates. Enabling support for SSLCACertificatefile would make Seafile-client/Seadroid closer to current browsers SSL Certs support (99% of the browsers).

**Comment by shoeper** [comment]
Seadroid behaves like any other Android App does.
Am 14.01.2015 11:13 schrieb "mathieu-mp" <notifications@github.com>:
