### ISSUE TITLE
Not working with private server

### ISSUE THREAD

**Issue by akumria** [haiwen/seadroid#243]
Hi,

I have installed a private server, it is located at https://... 
Both the web client and desktop clients work fine. Unfortunately the Android client does not.

My first problem is actually logging in.

It says "Server address should contain the port." in this case the seafile server is behind Apache, which is doing the https. If it use port 8000 it doesn't work. If I use port 443 it doesn't work. If I use port 80 it doesn't work either.

Suggestions?

Thanks,
Anand

**Comment by Logan676** [comment]
does it work if you remove the port?

**Comment by akumria** [comment]
Oddly, it now seem to work once I have rebooted the phone.

I wonder if the message was related to a problem with the network (it did appear to be operational when I initially attempted) rather than actually connecting to the remote server.

Thanks for your suggestion.

Regards,
Anand
