### ISSUE TITLE
Error whilst loading libraries

### ISSUE THREAD

**Issue by ayounggun** [haiwen/seadroid#246]
Hi there

Thanks for your work on the seafile android app =].

I get the following message when trying to use the seafile android app with my private seafile server: "Error whilst loading libraries."

I hoped you could help. Let me know if you need any more details

* seafile android app version: 1.4.1
* seafile server version: 4.0.5
* android os version: 5.0.1
* server os: ubuntu 14.04.1 64bit
* phone model: nexus 4
* server setup: nginx https frontend, mariadb database backend

**error in app activity tab**

```
GET /api2/html/events/

HTTP 403 FORBIDDEN Vary: Accept Content-Type: text/html Allow: GET, HEAD, OPTIONS 

{ "detail": "You do not have permission to perform this action." }
```

**error in nginx access log (error log empty)**
```
[ipaddress] - - [17/Jan/2015:21:43:59 +0000] "GET /api2/starredfiles/ HTTP/1.1" 403 75 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0.1; Nexus 4 Build/LRX22C)"
[ipaddress] - - [17/Jan/2015:21:44:02 +0000] "GET /api2/repos/ HTTP/1.1" 403 75 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0.1; Nexus 4 Build/LRX22C)"
[ipaddress]  - - [17/Jan/2015:21:44:05 +0000] "GET /api2/repos/ HTTP/1.1" 403 75 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0.1; Nexus 4 Build/LRX22C)"
```
** logs/ccnet.log **
```
...
../common/connect-mgr.c(210): [conn] incoming handshake fails.
...
```

I have tried
1. deleting and re-adding the account on the seafile android app
2. entering an incorrect password on the seafile app on purpose to see whether it generates a different error message (it does) so i don't think this is the problem
3. connecting with the seafile linux client, which can connect succesffully and sync files (HTTP protocol)

Thanks

**Comment by lins05** [comment]
Can you test your seadroid app with an account on seacloud.cc? That would
tell us whether the problem is on server side or on client side.

**Comment by ayounggun** [comment]
Hi lins05

thanks for your reply

I woke up this morning and the app was working!

That is to say, the error message "Error whilst loading libraries." had gone and I could see my libraries.

I tried adding an account at seacloud.cc anyway, and it worked immediately with the seadroid app.

I also tried deleting and readding my private seafile account, and that also now worked immediately unlike before.

Sorry to have wasted your time

ps: is there a place somewhere that lists what infomation you would like to have in a bug report?

I have seen some people link to (a template)[https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md] you can use which I thought you might find useful

cheers

Alex

**Comment by Logan676** [comment]
Sorry, we don\`t have such a template yet.
