### ISSUE TITLE
Build APK in Android Studio

### ISSUE THREAD

**Issue by OskarNorin** [haiwen/seadroid#253]
Hi
New to the project and must say, new to Android Studio also. Tried to import the project from GitHub straight into Android Studio and after tweaking library settings a bit for the modules that being imported I almost can compile the project.
Problem I run into is  
Error:Android Packager: [seadroid] java.util.zip.ZipException: duplicate entry: resources.arsc
Tried searching for solution but I can only find old bugs in Android Studio that should be solved and old workarounds is not working. 

Any help is greatly appreciated, this project is exactly what I have been looking for so I would like to contribute.
Regards 
Oskar N

**Comment by Logan676** [comment]
We didn\`t adopt the project to Android Studio platform yet, so there maybe some problems out there.
I am new to Android Studio as well, but I am using Intellij IDEA instead, it works fine.
