### ISSUE TITLE
Notifications on camera upload, download files etc

### ISSUE THREAD

**Issue by bjoernr-de** [haiwen/seadroid#254]
Hi,

first I hope it's ok to submit feature requests as an issue. If not, please tell me where else to make a proposal.

I'd like to bring up a cool new feature I know from other applications (like MEGA):
On camera upload, custom upload or downloading files add a notification containing information like how many pictures are uploaded, how much percent is the upload/download progress etc

**Comment by freeplant** [comment]
Can you attache a screenshot?

**Comment by bjoernr-de** [comment]
Sure, but I only can show you in German ;-)

This notification appears when uploading files. Same appears on camera upload and downloading files.
And if it's finished the notification "Uploaded [x] files successfully" remains. 

![notificationbar_mega_upload_in_progress](https://cloud.githubusercontent.com/assets/2854699/5959077/6943d0ec-a7cb-11e4-8529-4e3d10da1490.png)

**Comment by allo-** [comment]
For single file downloads this can include an "open" function. 
For uploads i am missing it too. "Are the new photos uploading? Are they finished? Did the upload fail? Is somewhere a retry button?" all these questions could be answered by such an notification.

**Comment by bjoernr-de** [comment]
Having app v1.6.0 but still don't see any notifications on camera upload... :disappointed:

**Comment by allo-** [comment]
I do not see such notifications, too. I think i had one one time, but on a upload when wifi is back on at least it does not work. maybe it works (only?) direct after taking a picture while online.

**Comment by Logan676** [comment]
sorry for the misunderstanding, download and upload notifications were not introduced into 1.6.0, instead they will be released in Seafile-1.7.0.
Also camera upload notification which keeps the service running from being killed even when OS on a low memory, will be released in Seafile-1.7.0 as well.

**Comment by bjoernr-de** [comment]
Yeah, just wondering as this was added to the 1.6 milestone :smiley:
