### ISSUE TITLE
Camera upload also uploads WhatsApp pictures

### ISSUE THREAD

**Issue by bjoernr-de** [haiwen/seadroid#255]
Hello,

the camera upload service also uploads pictures being received in WhatsApp chats.

Example:
* User A activated camera uploads in his Seafile Android App
* User B sends A a picture via WhatsApp
* Seafile app uploads the received picture from WhatsApp (the picture user B sent) to the Seafile server

Note: Problem may occur also with other applications that sends pictures (like Facebook Messenger, ...)

**Comment by Logan676** [comment]
Maybe Seadroid should provide a popup window to let user choose a custom directory, in order to upload photos, on SD card.

**Comment by bjoernr-de** [comment]
Are you sure this is really an enhancement? 
I would rather say it's a bug because currently the camera upload uploads also non-camera taken photos as this is obviously not the job of a camera upload service.

**Comment by Logan676** [comment]
ok, if it uploads non-camera taken photos, it sounds like a "bug". But here your just propose to implement this bug, to upload photos sent by other Apps. So what\`s your point?

**Comment by bjoernr-de** [comment]
Sorry for the misunderstanding, I don't want to propose to implement such a function.
Let me try it again, hope it will be more clear now:

Currently the Seafile Android app uploads non-camera taken photos. This happens to me, when I get a picture from someone via WhatsApp. It immediately uploaded it to the Seafile server.

As it is a **camera upload service** it should not upload any pictures coming from WhatsApp or other apps than the Camera.

**Comment by allo-** [comment]
I have the same problem, but not with new images from other apps, but with an empty camera folder.

Steps to reproduce:
- Activate Camera Upload
- Existing Pictures are uploaded
- Take some pictures, they are uploaded
- everything in the cloud? now delete the content of the Camera Folder (not the folder itself).

What happens:
- Seadroid starts uploading some other folder (i.E. WhatsApp Images).

What should happen:
- Nothing at all

**Comment by akopper** [comment]
I like the current behavior to upload all images on the phone. 
You could rename it to all images uploader.

**Comment by Logan676** [comment]
@allo- if that happened, it is a bug.

**Comment by allo-** [comment]
This happend several times, i thought this might be the same, when i wanted to create an bugreport. But i think it uploaded not the full folder, but like the first image or some.

**Comment by radry** [comment]
How does Seafile decide what to upload? Does it just upload all images files or a certain directory? In the first case it's not a bug since whatsapp images are images.

**Comment by bjoernr-de** [comment]
@radry Sure, WhatsApp images are images but it's a Camera upload service and as the word says it should upload Camera photos not WhatsApp images :smiley:
