### ISSUE TITLE
android client - can't sync with https/nginx

### ISSUE THREAD

**Issue by scuq** [haiwen/seadroid#257]
I can't sync with my android client, I'm using the recommended setup with https/ngnix.

adb logcat shows:

D/TransferManager( 6151): Upload exception 2 Network Error
D/TransferManager( 6151): Upload path: /storage/emulated/0/DCIM/Camera/IMG_20150128_214744.jpg

tcpdump shows that seadroid is trying to reach port tcp/8082

but

http://manual.seafile.com/deploy/using_firewall.html

states that 443,10001 and 12001 are enough open tcp ports for seafile, I don't care how may ports must be open, but I want to use encrypted connections only.

anyhow, shouldn't the ports be configurable on the client if they are on the server?

br
scuq

seafile-server-4.0.5

seafile.conf:
[network]
port = 12001

[fileserver]
port = 8082

[database]
type = mysql
host = 127.0.0.1
port = 3306
user = ****
password = ****
db_name = seafile-db
connection_charset = utf8

seahub_settings.py:
....
        'FILE_SERVER_ROOT': 'https://seafile.example.org:8443/seafhttp',
        'HTTP_SERVER_ROOT': 'https://seafile.example.org:8443/seafhttp',
....

nginx site conf:
....
        location /seafhttp {
                rewrite ^/seafhttp(.*)$ $1 break;
                proxy_pass http://127.0.0.1:8082;
                client_max_body_size 0;
                proxy_connect_timeout  36000s;
                proxy_read_timeout  36000s;
        }

....

**Comment by lins05** [comment]
Can you upload/download files in a web browser?

BTW, if you deploy seafile behind apache/nginx, you need to set
FILE_SERVER_ROOT in seahub_settings.py:

FILE_SERVER_ROOT = "https://example.com/seafhttp"

Check http://manual.seafile.com/deploy/https_with_nginx.html

**Comment by scuq** [comment]
sry,  "https://example.com/seahttp" instead of  "https://example.com/seafhttp" was a typo, yes I can up and download files from a web browser, from the windows client and the osx client, just don't know why the android client keeps trying 8082

**Comment by scuq** [comment]
oh, you mean FILE_SERVER_ROOT as python variable, a damn I've wrote it as json ... I'll try it

**Comment by scuq** [comment]
and all of a sudden… it works like a charm, thx!! and sorry it's late and somehow I got confused by the fact that the windows and osx clients haven't had any problems.
