### ISSUE TITLE
Opening files doesn't work properly

### ISSUE THREAD

**Issue by shoeper** [haiwen/seadroid#258]
Same bug existed few versions before (maybe it's still the same one). When clicking on a file the progressbar is shown and never finishes. When clicking back the file is cached and can be opened.

**Comment by Logan676** [comment]
Which tab were you using when you came across this bug? Library tab, Starred Tab or Activities tab?
Please provide more detailed info in order that I can reproduce this bug. Thanks.

**Comment by shoeper** [comment]
Library tab, then I've clicked on a library and then I've navigated throw 
some folders. At the end I've clicked on a relatively small file while 
having a very fast connection. When clicking on a big file the progressbar 
works. But when I open a small file it's just there without showing the 
status and without opening the file on finish.


Am 4. Februar 2015 11:05:05 schrieb Logan Guo <notifications@github.com>:
