### ISSUE TITLE
Save password of encrypted libraries

### ISSUE THREAD

**Issue by githubomane** [haiwen/seadroid#26]
Hi, 

It would be great if the seafile android client saved the password of encrypted libraries so it won't be necessary to enter it everytime one tries to access the libraries.

Thanks

**Comment by SenorLAN** [comment]
+1 on this. An option within the app to save password (for at least the poweron session) would be great. As patcon mentioned many security minded people have device encryption and device passwords on their android/ios devices and thus feel safer having these devices store sensitive credentials. Encryption on the server is very important, but the client penalty can be a nuisance. Keep up the great work!

**Comment by shoeper** [comment]
I think this should be an option. E.g. cache it for one hour by default and allow the user to cache it on the device for 1 day, 7 days, 30 days or forever (the one our option is the default one).
