### ISSUE TITLE
Camera files do not upload in the background

### ISSUE THREAD

**Issue by jeroenpraat** [haiwen/seadroid#265]
Files are saved in a queue and only when I open the seafile app the files are uploaded. 

Using CyanogenMod 11.

**Comment by Logan676** [comment]
this was caused by the OS runtime optimization, if you opened a lot of Apps and have left Seafile working at the background, Android OS may stop the camera upload service when lacking of resource.

As you mentioned, when resumed the Seafile App, it gets back a higher runtime priority, so files are started to be uploaded.

**Comment by jeroenpraat** [comment]
Yes I already thought that this was the cause, but there must be a way to fix this. Because other android apps don't have this problem.

**Comment by Logan676** [comment]
We are about to release Seafile-1.5, which includes optimizations of transfer service. You can test it then.

**Comment by jeroenpraat** [comment]
Great. I will do that.

**Comment by radry** [comment]
Not sure if it is the same isse but it only uploads one image PER HOUR on my phone. The wifi is fast enough and I left the Seafile client open to ensure it has high priority. The queue doesn't show any file although there are many photos on the phone. There seems to be no way of forcing a sync of camera photos.

**Comment by shoeper** [comment]
You can stop android from putting the app in background by showing a permanent notification while uploading (at least that's afaik how other apps are doing it)

**Comment by bjoernr-de** [comment]
@shoeper this feature is already mentioned in #254 but as far as I know the Seafile team postponed the notification for the background service. Maybe @Logan676 can comment on that.

**Comment by Logan676** [comment]
yes, I postponed the notification for the background service. Because I will implement this feature in another way. Have been writing this module these days.

**Comment by Logan676** [comment]
It\`s a pity that we will not publicly release a new version to fix this issue according to our plan. 

But the code for implementing the feature was already finished. 
For those of you who have this specific requirements, please go to [download the build apk](https://github.com/Logan676/seadroid/releases/tag/1.6.3-custom) or view the source code in this [pull request](https://github.com/haiwen/seadroid/pull/328)

Thanks :-)
