### ISSUE TITLE
Default download directory for file

### ISSUE THREAD

**Issue by dszymczuk** [haiwen/seadroid#272]
I want to set default directory for download files for external SD, not internal memory.

**Comment by Logan676** [comment]
+1

**Comment by Logan676** [comment]
Since Google have denied the write access to external SD card from Kitkat (API 14), so it has little benefits to implement this feature because more than half of Seadroid users using Kitkat.

see the closed patch "Custom download directory #319"

**Comment by dszymczuk** [comment]
But some people have rooted phone - for example me. So I don't have restrictions.
Think about this.
This feature should not be very hard to implement.

**Comment by Logan676** [comment]
@dszymczuk I have already implemented that, see #319, but we won\`t release a version which including custom download directory according to the develop plan.
You can build one from that branch on your own.

**Comment by Logan676** [comment]
see also https://forum.seafile-server.org/t/seafile-android-cache-on-sd/812
