### ISSUE TITLE
Camera upload function dumps all subdir files into single dir

### ISSUE THREAD

**Issue by MiG29** [haiwen/seadroid#277]
The camera upload function currently ignores any directory structures in the camera dir and just dumps them together in the target dir. Would it be possible to have seadroid respect and replicate the existing structure on the phone? For example:

DCIM\Camera\img1234.jpeg -> Camera Uploads\img1234.jpeg
DCIM\Camera\London trip (autumn 2014)\img2345.jpg -> Camera Uploads\London trip (autumn 2014)\img2345.jpg
DCIM\Camera\todo\house\img3456.jpeg -> Camera Uploads\todo\house\img3456.jpeg

**Comment by lins05** [comment]
This is a good suggestion, and really makes sense to me.  @Logan676 @freeplant

**Comment by shoeper** [comment]
It would also be a nice option if one could not only upload to a specific library but also to a folder in it.

But I'm not sure if it wouldn't be the best to include desktop like sync (maybe also oneway) and people could just add their folder directory to sync instead of writing an extra photo upload.

**Comment by MiG29** [comment]
tbh, I'd prefer sync to be two way as much for photos as for regular files.

In the case of photos I tend to sort them on my desktop and laptop rather than on the phone itself, as using a larger screen and faster interface (keyboard/mouse, photoshop nearby) is much more convenient. Was hoping for the photo sync function to be an improvement over making the phone emulate a USB mass storage device and doing things manually.

**Comment by shoeper** [comment]
Yeah of course. I'd just think of cases where one hasn't got enough space on it's phone. Still most devices are delivered with only 16GB which isn't that much. So e.g. nexus users might be interested in being able to delete photos on there phone without deleting them from their private cloud.

**Comment by MiG29** [comment]
Good point. Toggle setting for deletion propagation perhaps?

**Comment by schwabe** [comment]
For me the current master version now does this.
