### ISSUE TITLE
Camera upload fails when filename contains colon

### ISSUE THREAD

**Issue by rsipka** [haiwen/seadroid#278]
Hello, Camera Upload fails to upload files which contain colon (:)

example of filename:
IMG_20150210_205534:nopm:.jpg

Since it retries those files only, "normal" files won't get uploaded.

On server side, this is part of the fileserver.log:
[03/04/2015 12:23:55 AM] upload-file.c(445): [upload] Bad filename.

On Android, tested version is 1.5.0
On server, version 3.1.7 is running.

**Comment by Logan676** [comment]
duplicate with Auto picture upload fails #120

**Comment by rsipka** [comment]
Yes, it's duplicate but it seems that original issue is Closed? So, there is no plan to ignore the files with colon in name? Thx,

**Comment by freeplant** [comment]
You can upgrade server to version 4.0, which accept these files.
