### ISSUE TITLE
hide Activities-tab

### ISSUE THREAD

**Issue by DrAzraelTod** [haiwen/seadroid#280]
there is no need for that Activities-Tab on private Servers, since it doesn't do anything.

It should be hidden or at least explained better.
Currently all a user sees is a (missplaced, no margin left/right) red text that tells something might not work.
There is a lot of white space here. No need to be so brief.

"this will only work when..."

**Comment by shoeper** [comment]
Same with search button.

**Comment by Logan676** [comment]
Activities-tab and Search functions are only for Pro editions, you can upgrade your service. Thanks.

**Comment by DrAzraelTod** [comment]
What? that doesn't even make sense.
You don't change the text to "this function will work when..." because it will work in this single case?

great idea!

**Comment by freeplant** [comment]
We will change the text.
