### ISSUE TITLE
Version 1.5.0 Export not working

### ISSUE THREAD

**Issue by digital2k** [haiwen/seadroid#289]
The Export-function to other apps is broken since 1.5.0.

Exporting only shows the download dialog, but the progressbar never moves.
(1.4.2 worked)

Infos:
Device: Nexus 5 Stock Android 5.0
Seafile-Server: 4.0.6 (self hosted)

**Comment by Logan676** [comment]
I have reproduced this error, turned out to be a bug introduced into 1.5.0. Thanks.

**Comment by shoeper** [comment]
seems to be related to the bug where a file did not open after download and showed infinite progressbar instead but file was cached when clicking back.

**Comment by Logan676** [comment]
right, the bug was introduced by "Opening files doesn't work properly" #258, will fix it soon.
