### ISSUE TITLE
Download folder feature does not work

### ISSUE THREAD

**Issue by silberzwiebel** [haiwen/seadroid#290]
Hi,

I've tried seadroid 1.5.0 with a samsung galaxy tab, installed via google play and with a motorala defy+ smartphone, installed via f-droid. My Seafile server is running on a raspberry pi, b+. 

On both devices, however, the new (and highly needed) "download folder" feature does not work. 
Seadroid just prints the message: "Network error, please try again later" (or similar) -- although network (WiFi) is working fine and single files can be downloaded.

 I saw a similar error that someone posted in the seafile forum, but I can't find it anymore. However, at the google play store also someone is complaining that the feature does not work for him.

Thanks for fixing this,
silberzwiebel

**Comment by Logan676** [comment]
This is a already known error, will fix it soon. Thanks for report.

**Comment by Logan676** [comment]
BTW, do you have any idea of how to reproduce the error, I failed to reproduce it, seems that the error doesn\`t regular occur.

**Comment by silberzwiebel** [comment]
For me it never worked. Maybe it is because of WiFi only network,
because I never use other networks?
