### ISSUE TITLE
Camera Upload causes ANR

### ISSUE THREAD

**Issue by jbbr** [haiwen/seadroid#291]
I have enabled camera upload and I have a lot of pictures on my phone (~16GB, > 3000 images).

With WIFI enabled (=Camera Upload enabled) the Seafile App is completely unusable for about 10 seconds (or even longer). When I try to tap on any button inside the app nothing happens except of the appearance of the Android "App not responding" dialog.
With WIFI disabled (=Camera Upload disabled) the Seafile App is usable.

Interesting information from the error report:

* "Load: 10.56 / 13.6 / 11.77 - CPU usage from 3500ms to -4920ms ago: 97 % 1234/com.seafile.seadroid2: 94% user + 3.2% kernel"
 
-> This means the seadroid process is using almost 100% of one CPU core and is probably causing a lot of IO (which would explain the exceptional high unix load of ~11)

* Activity: com.seafile.seadroid2/.ui.activity.BrowserActivity

I'm using the latest Seadroid 1.5.0 (package version 29) on a OnePlus One phone running on Android 5.0.2 (But same issue with Android 4.4 too)

It seems as if the Camera Upload scanner does not run asynchronously so it blocks the UI. So probably the blocking time is not as high for less images/less files on the phone storage.

**Comment by Logan676** [comment]
It\`s not acceptable if camera upload causes ANRs, even with large amount of files being uploaded. Will optimize that right away, thanks for your info.

**Comment by Logan676** [comment]
@jbbr you can use this optimized apk to test this, thanks for your help. [download apk](https://cloud.seafile.com/f/3b89eca891/)

**Comment by jbbr** [comment]
Thanks for the quick response and fix!
I haven't had any ANRs with the optimized apk yet.
