### ISSUE TITLE
Seafile cannot upload files from non-local sources

### ISSUE THREAD

**Issue by forouher** [haiwen/seadroid#297]
(created issue from comment by @Logan676 in #287)

When I trying to upload a file from one Seafile account to another, it shows "unable to upload, no path available".

Steps to reproduce

- Login Seafile with two accounts, A and B
- Choose account A to open its LIBRARY tab
- Navigate into one library and choose upload menu
- Choose other option from the popup dialog window
- It opens the document provider and lists accounts A and B
- Click B and navigate into a library and choose a file to upload
- It shows "unable to upload, no path available"

**Comment by forouher** [comment]
This is a bug in BrowsersActivity etc.. The code can only handle local files. It also fails e.g. with Google Drive. The specific bug observed originates in https://github.com/haiwen/seadroid/blob/master/src/com/seafile/seadroid2/util/Utils.java#L503 where unexpectedly the column "_data" is missing (I don't know enough about using Intents to immediately see why).

But the issue runs deeper, as BrowsersActivity,

**Comment by Logan676** [comment]
It din\`t take remote files into consideration when writing this module, in order to handle remote files in SAF, can we simply add a new method specifically used for parsing Uri for remote files?

**Comment by forouher** [comment]
I don't think a workaround for remote Uris is necessary. One just has to handle the result of ACTION_GET_CONTENT a bit differently. See https://stackoverflow.com/a/24153223 for the same issue.

Fetching the file via ContentResolver.openInputStream() would probably the right way to do it. And then do either

- handle the InputStream over to the UploadTask, or
- writing the Stream out into a temporary file which is then uploaded.

**Comment by Logan676** [comment]
Yeah, maybe we need to implement this like dropbox, downloading the file to local storage first, and then upload it.
