### ISSUE TITLE
Inconsistency in camera upload sync

### ISSUE THREAD

**Issue by troed** [haiwen/seadroid#301]
The following is valid for a Sony Xperia Z3 Compact. I don't know if it's valid for all Androids.

1) Take picture - name might be DSC_0297.JPG
2) Let picture sync using seadroid's automatic camera upload feature
3) Delete picture (on mobile & in libraries)
4) Take new picture - name will again be DSC_0297.JPG
5) The new picture will never sync

This is unexpected behavior and might cause users to believe their photos are backed up when they aren't. If filename are used to know what to sync then maybe hashes of content might be needed instead.

**Comment by shoeper** [comment]
As a temporary fix you could check if you can enable timestamps for files names in your camera settings.

Technically there is a problem with the FileObserver (honestly I'm not 100% sure if one is used - if not it imho should be used) or the methods handling the events.
It could also be that the FileObserver is not running all time.

**Comment by Logan676** [comment]
> Take new picture - name will again be DSC_0297.JPG

This is the reason why it does\`t sync any more, because Camera Upload Service marked the photo as synced via its name into local database.
To fix that, you can go to OS Apps manager --> Seafile --> App Info --> `Clear cache` (to remote the database).

**Comment by shoeper** [comment]
Seafile could use FileObserver to also delete files when they are deleted and upload files on modify and on create. In addition if that shouldn't be done seafile could honor last modification time / creation time.

**Comment by troed** [comment]
@Logan676 It's clear _why_ the issue happens - but it's unexpected behavior and will cause loss of trust. It's common for users of mobile phones to delete camera photos - and if those photos had been automatically backed up using Seadroid the new photos taken (filling up the holes in the naming scheme) will _never_ be backed up/uploaded. Since the user hasn't taken an action where they could expect such behavior there should be no need for them to perform manual workarounds.

Checking vs last modification/creation time in addition to the name in the database entry would work fine as a solution.

**Comment by Logan676** [comment]
Thanks for your comment, will add this feature soon.

**Comment by tomchiverton** [comment]
Add for the next release ?
