### ISSUE TITLE
Can't download/upload a file with Android client except I'm connected to LAN.

### ISSUE THREAD

**Issue by PocketSam** [haiwen/seadroid#303]
I've got a seafile server at home, and I can access it with a web interface or with my windows sync client from work. No problem at all.
But there is a problem with Android client. I can view folder contents and move across folders, but I can't neither download nor upload a file. It's possible only if I'm in my home network (connected to home Wi-Fi).

Server has no firewall, it's behind a router with mapped ports.

I have no idea how can I troubleshoot a problem. Any ideas?

Thank you.

**Comment by shoeper** [comment]
How did you setup seafile?
Behind nginx/apache?

Also have a look at manual.seafile.com.

**Comment by PocketSam** [comment]
I have used this manual http://manual.seafile.com/deploy/using_mysql.html
No nginx/apache. Seafile itself. I didn't want to use additional software. 

What differences are between how PC and Android are synced?

**Comment by shoeper** [comment]
See this: http://manual.seafile.com/overview/components.html

most important information for you:
This is how dekstop clients interact with the server:
![](http://manual.seafile.com/images/seafile-sync-arch.png)

And here you can see how web and mobiles clients work:
![](http://manual.seafile.com/images/mobile-arch.png)

And this is how it'd work with nginx/apache:
![](http://manual.seafile.com/images/seafile-arch-new-http.png)

**Comment by tomchiverton** [comment]
If you can't even browse from the remote network, you are missing a proxy setting, probably for /seafhttp, but either way it's not an issue with Seadroid. Works fine for me.

**Comment by PocketSam** [comment]
I've found a problem. Android can't download/upload if server redirects mobile client woth 301 code. I've changed FILE_SERVER_ROOT in seahub_settings.py to the httpS://site.tld:443/ and it started to function with no problems!
