### ISSUE TITLE
Cannot open .kdb and .kdbx files - app crashes

### ISSUE THREAD

**Issue by tschiew** [haiwen/seadroid#304]
When I try to open a .kdb or .kdbx file (Keepass Password Safe), the seafile app crashes (App-Version 1.5.1, Server-Version 4.0, Android 4.4.2).
Other file types (jpg, pdf, ...) can be opened without any problems and the .kdb files can be opened in other apps (e.g. Dropbox) without any problems. The .kdb file will then be displayed with the app "KeePassDroid". 
If the App "KeePassDroid" has been uninstalled, the seafile app crashes anyway when clicking on the file. So it doesn't seem to be a problem with the Keepass app (or the connection between seafile and this app), but with the file itself. 

Stacktrace: http://www.patrick-albert.de/download/SeafileStacktrace.png
Example kdb file: http://www.patrick-albert.de/download/KDBTest.kdb (Password: 12345)

This issue is the only cause for still using dropbox parallely to seafile :(

**Comment by tschiew** [comment]
Update:
The stacktrace contains the information "permission denial [...] cmp=org.wikipedia/settings.LicenseActivity". When I uninstall the wikipedia app, it's possible to open the kdb file from seafile. 
After reinstalling the wikipedia app, the error (seafile app crashs when clicking on kdb file) occurs again. 
What's the connection between seafile, the kdb file type and the wikipedia app??

**Comment by Logan676** [comment]
I have installed `KeePassDroid` and `Wikipedia` and reproduced this error, but
> According to this answer: [android.permission.INTERACT_ACROSS_USERS_FULL is a signature level permission](http://stackoverflow.com/a/21825156/3962551). Your app will not be able to use it until and unless it has the same signature as the system.

> Which is not something you can achieve unless you either are the creator or the system build, or collaborating with them such that they are willing to sign your apk with their certificate. In other words, this is off limits for most developers.  

But as a workaround you can first download the file and open it in KeePassDroid. 
I will continue looking into this issue.

**Comment by tschiew** [comment]
Thanks for your answer. 
I removed the original wikipedia app and installed a third-party wikipedia app - and then, it works fine. That's ok for me (=> dropbox account disabled :D), but I don't understand yet the correlation between seafile, the file type "kdb" and wikipedia. 
Why "kdb" (e.g. "gpx" files can be opened correctly with the GPS app "Locus" - opening strange file types so doesn't seem to be a problem) and why wikipedia (and not xing or AngryBirds)?
