### ISSUE TITLE
Automatic camera upload, uploads files in loop if library is password protected and not unlocked

### ISSUE THREAD

**Issue by difto** [haiwen/seadroid#324]
I upgraded to Lollipop yesterday and updated to the latest version of Seafile on the market. I could select my DCIM folders for automatic upload and it was working (I could not do it before so only photos on the internal memory were uploaded). However my library for photos is password protected (as I want the files to be encrypted on the server which is a Raspberry Pi), now automatic photo upload still tries to upload every single file (including videos) in the library but cannot obviousely. It used 13 GB on wifi in a couple of hours (I don't have 13 GB of images/videos) on my phone, I was just asking myself why it was always hot. 

Now what would be logical is that:

1) Seafile store the password on the phone for the library and open it if it wants to upload something (ideal, I don't understand why it is the case on Windows and not on Android)
2) Wait for the library to be opened before uploading anything (which is also fine as I can backup it periodically)

**Comment by Logan676** [comment]
Since the camera upload configuration helper automatically filtered (hide) the encrypted libraries, that is, you can\`t choose to upload photos to an encrypted library. So I wonder how could you set up the encrypted library for uploading?

Sorry that I didn\`t get your point.

> Seafile store the password on the phone for the library and open it if it wants to upload something (ideal, I don't understand why it is the case on Windows and not on Android)

Do you mean that the App can upload things under an encrypted library? I wonder what exactly the case is that occurs on Windows not on Android.

> Wait for the library to be opened before uploading anything (which is also fine as I can backup it periodically)

Do you mean that backup only works when the app was left at the foreground?

It will be easier for us to debug if you can tell how to reproduce the issue.

Thanks.

**Comment by Logan676** [comment]
If you have configured the camera backup service before 1.6.0, and have problems after upgrade. That may caused by inconformity of legacy App version. 
But again, the encrypted library was not supported for photo  backup service.

**Comment by difto** [comment]
1 ) Well you are right that encrypted library are hidden in this version but they were not in the past when I setup the automatic upload in an older version, the setting survived the updates.

![screenshot_2015-04-11-15-50-45](https://cloud.githubusercontent.com/assets/9381815/7101650/9f6124ba-e063-11e4-8541-c6d9d3106b6e.png)
![screenshot_2015-04-11-15-50-27](https://cloud.githubusercontent.com/assets/9381815/7101651/9f710b6e-e063-11e4-986c-00ee5102ca3f.png)

I did not know that support was dropped or not planned at all for encrypted libraries. 

2) My point with Windows Seafile client is not automatic photo upload but the fact that the Windows client is able to store the encrypted libraries password and sync them without re-asking the password, I do not understand why Seadroid do not to store encrypted libraries passwords, if it did, it would be able to upload by itself in encrypted library as it does in unencrypted libraries.

3) Actually the automatic photo upload works in encrypted library if you unlock the library in the app, it works for a while until the library is relocked (if the app is closed I think), but if the library is locked the upload service tries nevertheless continuousely to upload (but fails). My point is that it should not try to upload if it cannot access the library in the first place.

**Comment by midi** [comment]
@Logan676 Thank you for adding video support.
So if I understand you correctly, auto uploading for encrypted libraries is currently not supported?

Is that something you want to add support for eventually?
I currently unlock the library once in a while and then it will upload the photos, which is nice, but of course a fully automated way of doing it would be much appreciated.

For reference, here's a related issue that was closed:  #201

**Comment by Logan676** [comment]
I tend to support uploading to encrypted library enventually. But it may takes for a while
