### ISSUE TITLE
self-signed certificate may not download file

### ISSUE THREAD

**Issue by xinbindai** [haiwen/seadroid#326]
If the seafile web site use self-signed SSL certificate, I was able to connect to remote server and also listed files in libraries using the latest seadroid. However, none of files can be downloaded. On the other hand, no-SSL link, namely 80 port, works fine for download.

**Comment by xinbindai** [comment]
Seadroid version is 1.6.0 and server side is 4.1.2. enabled "syncing with http protocol".

**Comment by dovydasvenckus** [comment]
I got same problem. Every time I try to download file from my https server download fails.

**Comment by shoeper** [comment]
If port 80 works fine seafile seems to be configured wrong.

**Comment by xinbindai** [comment]
@shoeper, at least the desktop client works fine with the same SSL configuration. If necessary, I can upload my nginx setting for both 80 and 443 port.

**Comment by shoeper** [comment]
Desktop and mobile clients work in different way. The Desktop client receives blocks and combines them itself. The mobile client receives complete files. Your nginx and seafile configs could be helpful.

**Comment by shoeper** [comment]
https://github.com/haiwen/seadroid/issues/114#issuecomment-92697447

**Comment by xinbindai** [comment]
Yes,  #114 fixed the download issue. What we need to do is to change FILE_SERVER_ROOT value in seahub_settings.py to fit https.
