### ISSUE TITLE
Upload View unclear on failed upload

### ISSUE THREAD

**Issue by allo-** [haiwen/seadroid#337]
I find it quite unclear, what happens on the upload list with failed uploads. They are marked as failed in the list and can be restarted one by one via long press. Okay.

But i do not see, if they will be retried later, if i have the risk of losing the list of files i need to restart, if i.e. the photo upload folder will be synced again when possible.

So, i think there should be a few more things:

- Multi-Selection
- "Retry all" Button
- "Clear finished" Button
- "Clear failed" Button (Maybe)
- "Clear all" Button
- Maybe: "Pause" / "Resume" or even "Pause Selection"

**Comment by Logan676** [comment]
that\`s pretty much the requirement we need to support.
