### ISSUE TITLE
broken uploader

### ISSUE THREAD

**Issue by TehEnforce** [haiwen/seadroid#339]
since last update the app refuses to upload 200mb+ files and just puts into cache And shows message Uploadin file but in transfer menu EMPTY
result: 200mb cache size but no upload

Also problem with 1GB files and up

**Comment by shoeper** [comment]
Does your server allow such "big" uploads?

**Comment by TehEnforce** [comment]
Yes. I uploaded 500mb+ files on earlier versions of the app without issues.

**Comment by Logan676** [comment]
> since last update the app refuses to upload 200mb+ files

Can you upload big files via Seahub (the web interface)?
Please keep the App running in the foreground when uploading big files.

**Comment by TehEnforce** [comment]
Dont know if via seahub can. Its so slow I never use it. Only use the
windows and android app.

Yes its running in background i even try with app on fulltime but no work

**Comment by shoeper** [comment]
On what hardware do you run seafile? Memcached could help increasing seahub. And are you using mysqlite oder mysql as database?

**Comment by TehEnforce** [comment]
DigitalOcean VPS. Sqlite and no idea how memcached works

**Comment by shoeper** [comment]
Ok, I'd recommend using MySQL. And memcached is very easy to setup.

See http://manual.seafile.com/deploy/add_memcached.html for setting up memcached.
And http://manual.seafile.com/deploy/migrate_from_sqlite_to_mysql.html explains how to migrate to mysql. You could leave your sqlite db intact to switch back if mysql does not improve speed.

**Comment by TehEnforce** [comment]
Hmmm k.

but the android app is still broken so if a dev can look at it

**Comment by shoeper** [comment]
I did a test. The app works. Was able to upload a ~350MiB file without any issues.

**Comment by TehEnforce** [comment]
Try and upload a 500mb or 1,20GB file.

Also what android version you have and what phone?
(Mine is android 4.2.2, samsung s4 for comparison)

**Comment by shoeper** [comment]
S4, Android 4.3

1.6GB upload finished successful.

**Comment by shoeper** [comment]
Btw. what is in your seafile-data/seafile.conf file?
