### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by TehEnforce** [haiwen/seadroid#340]
Option to remove folders and progress bar of download/uploads in notificationbar when app closed (like the MEGA app has)

Also way to select multiple files and do actions such as download, delete etc. Would be good.

**Comment by bjoernr-de** [comment]
Notifications on upload/download already mentioned in #254 and will be released with version 1.7.0 (see #254)

**Comment by Logan676** [comment]
> Option to remove folders

done


> progress bar of download/uploads in notificationbar

done

> select multiple files

support select multiple files via SAF (Storage Access Framework) if OS is Kitkat upwards or normal file chooser if OS is pre-Kitkat to upload 

> do actions such as download, delete etc.

support download folder (or with sub folders)
support delete file
