### ISSUE TITLE
Viewing encrypted library sends password to server

### ISSUE THREAD

**Issue by jimbo1qaz** [haiwen/seadroid#348]
When I enter encrypted library password on Android, I can instantly login over the web interface. This means that the password is being sent directly to the server, violating the security guarantees of client-side encryption. The PC version does not suffer from server-side decryption.

**Comment by shoeper** [comment]
It is documented somewhere that client side en/decryption for browsers have been dropped at some time. For mobile clients it has never been there.
The password is being cached for some time on the server. Desktop clients do not send it to the server.

**Comment by shoeper** [comment]
see http://manual.seafile.com/security/security_features.html.

**Comment by bjoernr-de** [comment]
But isn't Seafile guaranteeing client-side encryption on their homepage?

And reading "From version 4.1, Seafile uses HTTP syncing protocol by default." makes me confused..
Might be that I understand wrong but syncing via unencrypted HTTP?

**Comment by freeplant** [comment]
HTTP syncing protocol means using HTTP or HTTPs, depending on whether you have configured HTTPs on Nignx/Apache.

**Comment by bjoernr-de** [comment]
Thanks for explaining @freeplant

**Comment by shoeper** [comment]
Just read what I've posted and you know what is getting enrypted on client side and what not.
So 
> It is documented somewhere that client side en/decryption for browsers have been dropped at some time. For mobile clients it has never been there.
The password is being cached for some time on the server. Desktop clients do not send it to the server.

is still the answer on your question. Nothing will change by asking 20 times again.

**Comment by bjoernr-de** [comment]
Yes but promoting Seafile with "Client-Side Encryption,
Better Protecting your Privacy" (see http://seafile.com/en/home/ 3rd slide) is then absolutely wrong. (as you say, there is no client side en/decryption for browsers and mobile clients)

That's the reason I just asked someone who is developing Seafile ;-)

**Comment by shoeper** [comment]
Ok right, it's a bid misleading. There should be a hint somewhere that this is only the case with desktop clients.
But on the other hand the "read more" (first box bottom, left) links to the same page I linked above.

**Comment by freeplant** [comment]
Client side encryption for Android/iOS client will be added. But browser-side will not be added. (It is too complicated and hard to maintain from our previous experience).

**Comment by dreua** [comment]
There is still no client side encryption in Android client 2.1.9. Is this anywhere on the roadmap?

**Comment by shoeper** [comment]
According to the changelog there is support since 2.1.0.

See https://github.com/haiwen/seadroid/releases/tag/2.1.0

**Comment by dreua** [comment]
Yet I cat reproduce the behavior exactly as described by @jimbo1qaz with the Seafile Android client 2.1.9 (the latest I got from Google Play). So this is not intended behavior? Is this here sufficient or should I report a bug elsewhere?

**Comment by shoeper** [comment]
Afaik you've to enable client side encryption manually.

**Comment by dreua** [comment]
You are right @shoeper , I missed that one. Sorry and thanks for the help!

(Maybe it should be on by default or there should be a warning that your encryption password is send to the server but that's just my opinion and this might be the wrong place to discuss it.)
