### ISSUE TITLE
Camera upload to encrypted library requires password each time

### ISSUE THREAD

**Issue by radry** [haiwen/seadroid#355]
Automatic camera upload fails to upload when the target library is encrypted. To make it work the password has to be entered every time (don't know how long the "timeout" is until it forgets the password).
This kinda defeats the purpose of "automatic" upload.

What I also noticed but is probably a different problem is that the upload only starts when I start the app. The service (if there is one) doesn't do anything in the background.

App Version 1.6.2

**Comment by Logan676** [comment]
duplicate with #324

**Comment by radry** [comment]
Duplicate is closed although it is not solved. Should be changed to feature request then.

**Comment by Logan676** [comment]
> Automatic camera upload fails to upload when the target library is encrypted

the encrypted library was not supported for camera backup service now, the feature may be implemented 
in the future

> What I also noticed but is probably a different problem is that the upload only starts when I start the app. The service (if there is one) doesn't do anything in the background.

see "keep camera upload service running in background" #328
