### ISSUE TITLE
Whitespace after email address doesn't get stripped in new account setup

### ISSUE THREAD

**Issue by szponek** [haiwen/seadroid#357]
It would be worth to strip leading/trailing whitespace characters from email address entered in the account setup dialog. My email address got auto completed with a space at the end and I got 'wrong password' message, which was confusing for a couple of seconds.

This might be even more annoying when after 3rd attempt, login limit gets reached - less technical users might give up on trying out seadroid after that.

**Comment by bjoernr-de** [comment]
+1
and should be easy to implement (```Java.String.trim();```)
