### ISSUE TITLE
can't download files with spaces in the name

### ISSUE THREAD

**Issue by ejb1123** [haiwen/seadroid#359]
When I try to download a file that has a name like `2015_4_3.5.6.jpg` it fails. I think the reason is that there are more than one `.` in the file name.

**Comment by Logan676** [comment]
It\`s a pity that I couldn\`t reproduce the issue, from my testing, files can be successfully downloaded both via Seadroid and Web interface. Seems like the period in file name doesn\`t cause any errors when downloading.

For investigations,
* Which Seadroid version are you using?
* Which Seafile server are using?
* Could you download a file via [Seacloud](https://seacloud.cc/)?

**Comment by ejb1123** [comment]
seadriod:1.6.2
seafile server 4.0.6
downloading through the web is fine
---
the issue does not happen with seadroid 1.6.3

**Comment by ejb1123** [comment]
i am using iis url rewrite as a reverse proxy and here are the rules i am using
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <clear />
                <rule name="files" stopProcessing="true">
                    <match url="^seafhttp(.*)$" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
                    <action type="Rewrite" url="http://127.0.0.1:8082{R:1}" appendQueryString="true" logRewrittenUrl="true" />
                </rule>
                <rule name="ReverseProxyInboundRule1" stopProcessing="false">
                    <match url="(.*)" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
                    <action type="Rewrite" url="http://127.0.0.1:8000/{R:1}" logRewrittenUrl="true" />
                </rule>
            </rules>
            <outboundRules>
                <preConditions>
                    <preCondition name="ResponseIsHtml1">
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/html" />
                    </preCondition>
                </preConditions>
            </outboundRules>
        </rewrite>
        <security>
            <requestFiltering allowDoubleEscaping="true" />
        </security>
    </system.webServer>
</configuration>

```

**Comment by Logan676** [comment]
> The file name is 2015-05-08 21.53.30.jpg which does not download
> It work with seadroid if the file is 2015-05-08_21.53.30.jpg

I have renamed a picture like this `2015-05-08 21.53.30.jpg` and upload it to a folder on [Seacloud](https://seacloud.cc/) via the browser. When I try to download it from Seadroid, it works fine.

**Comment by shoeper** [comment]
haiwen/seahub#202
https://groups.google.com/d/msg/seafile/LBBe2quCwuk/kIu_rWC93qMJ

**Comment by Logan676** [comment]
#104
