### ISSUE TITLE
Latest seadroid 1.7 removes all but active account on installation

### ISSUE THREAD

**Issue by caniwi** [haiwen/seadroid#365]
I had a number of seafile accounts on different servers and could switch between them.  On upgrading to seafile 1.7 from google play it wiped out all the accounts except the currently active.  This should not happen and did not happen on previous upgrade.

**Comment by caniwi** [comment]
This has happened to another user that I know.  He upgraded before I could warn him.

**Comment by Logan676** [comment]
Sorry, but Seafile-1.7.0 has added a new table "ServerInfo" to the "account" database. 
In order to upgrade the database to the latest version, the table has been dropped and recreated again.

**Comment by shoeper** [comment]
Better would have been a migration method.
Get all necessary information (account names, servers, tokens) drop database recreate it reimport data and fill missing data in.
