### ISSUE TITLE
Hard to find other file options

### ISSUE THREAD

**Issue by tomchiverton** [haiwen/seadroid#366]
After tapping a file, a list of options drops down.
There is no visual indication that further options are available by swiping this list sideways. On my Android 4.4 Sony Z1Compact the option squares fit exactly across the screen, so no partial 'next' item is visible.

Common affordances here would be a tint/fade on the side that led to more, or an arrow.

**Comment by tomchiverton** [comment]
Is this closed because the future task is done ?

**Comment by Logan676** [comment]
right, we will support this feature in this way #378

**Comment by Logan676** [comment]
right, we will support this feature in this way #378
