### ISSUE TITLE
Image gallery jumps back to first image on screen rotate

### ISSUE THREAD

**Issue by forouher** [haiwen/seadroid#373]
Steps to reproduce:
1. go to a directory with multiple images
2. open an image by tapping
3. slide left/right to see other images
4. rotate screen
5. the gallery reverts to the image tapped on in step 2

PS: Thank you *very* much for implementing the image gallery! :-)

**Comment by Logan676** [comment]
I have reproduced the issue, will fix it soon. Thanks.
