### ISSUE TITLE
Application Crashes while trying to View Image

### ISSUE THREAD

**Issue by ploedman** [haiwen/seadroid#377]
Hello,
I already posted about this issues in the Seafile [Forums] 
(https://lio.p1o3.cc/LO8TY)

First it was a Issues with the Accounts, after I deleted all the Account information and also the Folders of Seafile on my Smartphone I thought it will Help, but the problem now happens with Image files. Music, Videos, Text files opening without any CTD. I tried the file extensions .gif, .jpg, .png and its always the same with the Crash, just a Pop-Up with the Info " Seafile stopped "

Seafile 1.6.3 works fine, the same happens also with 1.7.0. Version 1.6.3 asked me on the Images files which Application I want to use to open it, but can't remember if he asked me the same about Text, Music and Video. 1.7.0 and 1.7.1 does not ask me on Image files which application I want to use, instead it stops to work.

I added a Catlog with the Application " Catlog " from Google Store, I hope it helps, I also edited the line 189 because of the Account information (was not sure about the Password Hash).

[Catlog]
(https://lio.p1o3.cc/YfghL)

Using:
Sony Xperia Z1
Android 5.1 CM Resurrection Remix

**Comment by ploedman** [comment]
The Version from F-Droid causes the Image Opening crash.
The Version form Google Appstore works fine, without any crash.

https://forum.seafile-server.org/t/seafile-android-app-1-7-1-crashes-while-accessing-settings/1898/6?u=ploedman

**Comment by Logan676** [comment]
duplicate with #372
