### ISSUE TITLE
Better Filetype-Detection

### ISSUE THREAD

**Issue by DrAzraelTod** [haiwen/seadroid#388]
since 1.8.0 seadroid always asks if a file should be opened as Text/Image/... (except files that seafile knows, like .md or jpeg)

while that might be a feature that someone believed to be useful, it's kinda crap because it breaks androids autodetection. Previously i could just click on a .txt-file and since its clearly a textfile and my editor ([ted](https://f-droid.org/repository/browse/?fdfilter=text+editor&fdid=fr.xgouchet.texteditor) in my case) opened the file. Same goes for less well known file extensions like smc-roms (SNES-Emulator).

Yes, this will help if there is no app registered that handles that filetype. (i.e. opening a shell-script with whatever is default texteditor). But since there is no way to set a default ("always open .txt as textfile", "always use other") it needs an additional step to open each file.

So either implement some kind of windows-like file-registration or try to detect it based on unix filetype detection ("file foo.txt" -> "UTF-8 Unicode text")

**Comment by Logan676** [comment]
> But since there is no way to set a default ("always open .txt as textfile", "always use other") it needs an additional step to open each file.

Thanks for your feedback, we will support the "set default App" feature. When opening a file at the first time, Seafile pops up a "open as" window to let user to set the default opening App, then save the settings and always open the file by default App in the future.

Maybe user wants to change the default opening settings one day, so it would better to support a default App management option in Seafile Preference menu.

**Comment by DrAzraelTod** [comment]
> When opening a file at the first time, Seafile pops up a "open with" window to let user to set the default opening App, then save the settings and always open the file by default App in the future.

"the file" or "files of this type"? Imho you are building yourself a huge problem here. I don't really think seadroid should undergo the effort of deciding what file is of what type and how it should be handled. That's clearly a task that should be done by the OS (and Android has it's way of doing this, so interfering there just creates two points a user has to look for those settings)

I'm not against giving the user the ability to do those things (i.e. context-menu -> "open as...", "always open as..."), but default should always be "let android decide"

**Comment by forouher** [comment]
Out of curiosity: Could you point me to the SNES emulator app you're using?
I've tried out a number, but none seem to register itself for *.smc files.

**Comment by DrAzraelTod** [comment]
mostly [Snes9x EX+](http://www.explusalpha.com/home/snes9x-ex)

just had to check if it really registered for .SMC (it does) because i wasn't that sure anymore. :D

**Comment by DrAzraelTod** [comment]
whoops... hit the wrong button (and not for the first time -.-)

**Comment by forouher** [comment]
Thanks! Hm... doesn't register for me (on Android 5.1.1). 
I've tried two file managers (cyanogenmod file manager; ES File Manager) and neither offers it up (well, ES File explorer does, but only in the full list of all apps).

**Comment by DrAzraelTod** [comment]
works on the file-manager [that came with my z3c](https://play.google.com/store/apps/details?id=com.mobisystems.fileman&hl=de) (Android 5.1.1 too), i'll try it with more common tools later. (there are none installed on that phone, but back home i got some other devices)

but it does look like the same kind of registered apps like most other stuff uses including the 2 apps that have registered for ANYTHING (cgeo and OpenKeyChain, the later i kind of understand, the first is just stupid) what appear always and for all filetypes.

**Comment by forouher** [comment]
Hm, that file manager doesn't offer Snes9x EX+ either.
However, it /does/ offer up [SNES Emulator] (https://play.google.com/store/apps/details?id=cl.deimosapp.snnes). Any chance you're using that one?

**Comment by DrAzraelTod** [comment]
Nope, really using that EX+-Port. (and that app you just linked to looks suspiciously like it infringes on opensource software licenses)

but we've gone really offtopic here, would be better to continue via mail, xmpp (dat@g33ky.de) or irc (freenode/#zanzibar) if you need more information about stuff that isn't really related to this ticket

**Comment by forouher** [comment]
Thanks! Well its not that far off topic.

Basically I'm trying to see if there is way the behaviour of Seadroid (1.9.0) could be improved. I'm not sure there is. Seadroid seems to offer the same apps for opening as most file managers (and the "Downloads" app) do. 

True, that "File Commander" app seems to be able to match file types with installed apps more intelligently. However that looks like atypical behaviour to me and I'm suspecting that its authors have put some magic sauce into it. However without access to its source code, I wouldn't know how to replicate that in Seafile.

At the moment the behaviour of Seadroid seems to be the best possible. If I click on a .smc file, it opens one of those "catch-all" apps (business calendar in my case, probably openkeychain in your case). But I don't see how Seadroid can do much about that  (as annoying as it is, I fully understand).

**Comment by forouher** [comment]
@DrAzraelTod please check out #425, it should address the issue.

The problem was that .smc is an unkonwn file extension on android. And Seadroid doesn't handly unknown extensions very well at the moment.
