### ISSUE TITLE
Downloading folder is disabled for read-only shared library

### ISSUE THREAD

**Issue by DevCybran** [haiwen/seadroid#393]
When sharing a library as read-only to another user, that user can't download a folder from the library using the seafile android app. The option to download a folder is present, but grayed out and not selectable.
When sharing a library as read-write, downloading the folder is working properly.
I would assume that this behavior is not intended, but a bug. Please correct me if I'm wrong.

**Comment by Logan676** [comment]
> I would assume that this behavior is not intended, but a bug.

No, that\`s not a bug.
The "Download  folder" menu will be grayed out under which directory who doesn\`t have write permission. 
Below is the code segment to enable or disable the menu.
```
if (navContext.inRepo() && hasRepoWritePermission()) {
    menuDownloadFolder.setEnabled(true);
} else {
    menuDownloadFolder.setEnabled(false);
}
```

**Comment by Logan676** [comment]
> I would assume that this behavior is not intended, but a bug. Please correct me if I'm wrong.

Sorry but it indeed a bug, will fix that soon, thanks for your report.
