### ISSUE TITLE
Picture preview

### ISSUE THREAD

**Issue by bogprs** [haiwen/seadroid#402]
Hi guys. 
Android app works amazingly. Small request: please display thumbnails for jpeg instead of generic pic icon.
Thanks in advance.

**Comment by Logan676** [comment]
@bogprs which version are you using, we supported to display thumbnails since [seafile-1.6.0](https://github.com/haiwen/seadroid/releases/tag/1.6.0).

**Comment by bogprs** [comment]
I've just updated to 1.8.1 and it is still not working.
When I click on a JPEG file it shows black background and a white silhouette of a picture and video frame. 
Maybe it is matter of size of the photo? (~5MB)

Thanks for a quick answer.

Best,
Bogdan

**Comment by forouher** [comment]
It should work then. Do you have a recent enough Seafile server? At least 4.1.x is necessary, IIRC.

**Comment by forouher** [comment]
Also, thumbnail generation is done on the server. if the server is very slow (e.g. a Raspberry Pi), then thumbnail generation might take a long time or even time out.

**Comment by bogprs** [comment]
Server is quite recent and a powerful Linux machine.
OK, I guess I need to update to version 4.1.x.

Many thanks!

Best,
Bogdan
