### ISSUE TITLE
Seafile client: Sync problems with Win10

### ISSUE THREAD

**Issue by irmlerc** [haiwen/seadroid#407]
Hello,

I'm using seafile for nearly a year, absolutely without problems. But now I've installed a fresh installation of Win10 on my notebook and installed the seafile 4.2.8 client, which doesn't sync :(

I see all the libraries inside the seafile-box, but if I click at "Sync library", it just comes the message "connecting with server..." (messages are translated from German, they will be a little bit else in English, I guess).

And then it tries to connect and connect and connect...
I already tried to disable the windows firewall, but it didn't change the situation.

It works fine with other clients on Win7, Win8.1 and Android, so it's a problem with the client.

Could you please tell me, how I can get run seafile also under Win10?
Oh: I also tried seafile 4.3.0 - it has the same effect...

**Comment by irmlerc** [comment]
Addition info: Server version is "seafile-server-3.1.6"

**Comment by Logan676** [comment]
I think your problem is not very much related to Seafile Android client, so please post your problem in [seafile-client](https://github.com/haiwen/seafile-client/issues) or [seafile](https://github.com/haiwen/seafile/issues)
