### ISSUE TITLE
Build Failure: Missing android jar

### ISSUE THREAD

**Issue by vishwanathsingh** [haiwen/seadroid#429]
I have cloned today from master and got a build failure. 
>Failed to execute goal on project seadroid: Could not resolve dependencies for project 
>com.seafile.seadroid2:seadroid:apk:1.8.0: Failure to find android:android:jar:5.0.1_r2 in >https://github.com/haiwen/maven-repo/raw/master was cached in the local repository, resolution will not >be reattempted until the update interval of custom maven repository has elapsed or updates are forced -> [Help 1]

looks like a missing jar file.

**Comment by Logan676** [comment]
You need to install the android jar, please follow the [README](https://github.com/haiwen/seadroid/blob/master/README.md) to establish the build environment locally.

**Comment by vishwanathsingh** [comment]
I have followed that..
Here is the complete log. There is a warning about missing pom.
>
$ mvn clean package
[INFO] Scanning for projects...
[WARNING] The POM for android:android:jar:5.0.1_r2 is missing, no dependency information available
[WARNING] The POM for com.github.astuetz:pagerslidingtabstrip:aar:1.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building seafile android client 1.8.0
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.375 s
[INFO] Finished at: 2015-09-22T23:09:00-04:00
[INFO] Final Memory: 14M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project seadroid: Could not resolve dependencies for project com.seafile.seadroid2:seadroid:apk:1.8.0: Failure to find android:android:jar:5.0.1_r2 in https://github.com/haiwen/maven-repo/raw/master was cached in the local repository, resolution will not be reattempted until the update interval of custom maven repository has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by Logan676** [comment]
you need to install android jar locally like below
```
cd /tmp/
git clone https://github.com/mosabua/maven-android-sdk-deployer.git
cd maven-android-sdk-deployer
mvn clean install -pl platforms/android-21
```

**Comment by vishwanathsingh** [comment]
Thanks. It worked for me. I am looking into the android client's source code to understand the content-defined chunking algorithm used by seafile. Is there any documentation of this for android client ? Or where shall I look in the source code. I could see plain HTTPRequests being sent for updateFile and uploadFile requests. 
Does this mean that AndroidClient doesn't support chunking???

**Comment by shoeper** [comment]
> I could see plain HTTPRequests being sent for updateFile and uploadFile requests. Does this mean that AndroidClient doesn't support chunking???

Afaik CDC is currently not being used by the android client. It uses the web api instead.

**Comment by vishwanathsingh** [comment]
@shoeper I am now moving to look into desktop client's code to read CDC's implementation. Any pointers on where to look??

**Comment by freeplant** [comment]
The Android client don't use CDC. The CDC is not quite useful for the desktop client too. So we are planning to remove it.

**Comment by vishwanathsingh** [comment]
@freeplant thanks for the answer. When you say its not useful do you mean CDC is not giving you good dedupe ratio or its just too computationally intensive?

**Comment by Logan676** [comment]
I will close this as it already fixed the build problem.
