### ISSUE TITLE
Camera upload not working

### ISSUE THREAD

**Issue by damianorenfer** [haiwen/seadroid#430]
Hello,

I tried Seafile Android client 1.9 on a Sony Xperia running Android 5.1. I configured camera upload and nothing happens, no upload.

**Comment by bjoernr-de** [comment]
Duplicate issue - Comment to #423 instead :)

**Comment by damianorenfer** [comment]
Didn't see it, sorry.

**Comment by bjoernr-de** [comment]
No problem :smiley:
