### ISSUE TITLE
Seafile Download Notification does not disappear.

### ISSUE THREAD

**Issue by Vadammt** [haiwen/seadroid#432]
Im using Seafile for Android v1.9.1

When I download a file from my own seafile Server I get a Seafile Download Notification, but that does not disappear and I cant remove it manually.
It says (German) "Dateien werden heruntergeladen" [en: Downloading files].

**Comment by Logan676** [comment]
There are several ways to remove the notification message
you can 
* long click the notification, click the exclamation mark symbol --> App notifications --> Block (Tested on Nexus 6)
* or long click the notification, then the block symbol appears --> Block
* or Settings --> Apps --> Seafile --> Force Stop

Hope it helps.

**Comment by Vadammt** [comment]
Thanks, but these solutions seem hacky.

Isn't it more useful to make Seafile replace the "Download Notification" with an "Open notification"? Or at least remove the Download notification when the download has finished becouse I can see the Download progress in the APP.

**Comment by freeplant** [comment]
The download notification can disappear on my mobile phone with Android 5.0.2. What is your device type and Android version?

**Comment by Vadammt** [comment]
I have a Samsung S6 with Android 5.1.1 and the notification sticks to the title and cant be removed (by swiping it away).

**Comment by Logan676** [comment]
Actually the notification will disappear when it finished downloading, but if the downloading is in progress the notification is not removable. Did you have finished downloading the file by the way?
