### ISSUE TITLE
Long-pressing a library crashes seadroid

### ISSUE THREAD

**Issue by bnw** [haiwen/seadroid#437]
Long-pressing any library in the libraries screen will crash the app.

Android 5.1.1
App version 1.9.2
Language German

**Comment by daun20** [comment]
Hi, I can confirm the described longpress force close behaviour in combination with a private server (raspberry on raspbian; server version 4.4.3) as well as for a demo account on https://cloud.mein-seafile.de . Sorry, but this is not a "maybe-bug".

Tested on:
Nexus 5 @ Android 6.0
Galaxy Tab S LTE 10.5 @ Android 5.0.2
App Version 1.9.2
Language German

Do you need any Logs?

**Comment by Logan676** [comment]
That is indeed a bug, I will fix it soon. Thanks for your report.
