### ISSUE TITLE
Seafile for Android crashes when fast switching beetween folders

### ISSUE THREAD

**Issue by daun20** [haiwen/seadroid#443]
Hello, I'd like to report a bug - the title contains the whole Information. Seadroid quits with: " Unfortunately, seafile has stopped." Tested on:

Nexus 5 Android 6.0 / App Version 1.9.2 (English & German)
Samsung Galaxy Tab S Android 5.0.2 / Same App Version (German)

**Comment by daun20** [comment]
just an additional info: i using a raspberry as a server with server version 4.4.3. I will soon update my server and check back. Sometimes seafile closes after a few (eg. 3 to 4) folder switches, sometimes I can make up to 10 or 20 switches and then seadroid crashes. Can't figure out what is caused this.

**Comment by Logan676** [comment]
@daun20 I can\`t reproduce the error, can you use the server [https://seacloud.cc/](https://seacloud.cc/) and try again?
