### ISSUE TITLE
Android app activity tab

### ISSUE THREAD

**Issue by Schnuecks** [haiwen/seadroid#448]
Hello,

when I click activities, and then click a folder, its contents will be listed, even though it is password protected. Going to a subfolder, he asks for a password as normal.

**Comment by Logan676** [comment]
Do you mean that Seafile didn\`t ask you to input password for an encrypted library when browsing files in ACTIVITIES tab?

**Comment by Schnuecks** [comment]
Yes, thats it. But only the content is listed if you try to open a file it asks for a password.
But the first access lists table of content without password.

**Comment by Logan676** [comment]
What\`s the version of Seafile are you using, and what do you mean by "the first access via activity tab lists table of content without password", again, it is normal if the App asks you for a password because the folder was encrypted. 

Sorry but I can\`t get your point, can you attach some screenshot?

**Comment by Schnuecks** [comment]
Here are the screenshots.

1.) Protected library
2.) Click on library in activity tab
3.) Content of protected library listed without entering a password

![screen1](https://cloud.githubusercontent.com/assets/4294371/11378652/86209378-92ec-11e5-86f9-66efea0632d1.png)
![screen2](https://cloud.githubusercontent.com/assets/4294371/11378658/89f511d6-92ec-11e5-80e2-a47aa2ac90ff.png)
![screen3](https://cloud.githubusercontent.com/assets/4294371/11378661/8c9e5f64-92ec-11e5-8466-1ff991cd921b.png)

**Comment by Logan676** [comment]
Thanks for your patience, I have reproduced the bug, will fix it soon.

**Comment by shoeper** [comment]
I'm not sure if this is bad. The list is likely to come from the local cache and the files can't accessed without the password anyway.
Furthermore according to the information I have metadata ist not encrypted anyway.

**Comment by Schnuecks** [comment]
On the desktop client the password protection works if i click on and must enter password, on linux the same.

So it's not very bad but all clients should show the same behaviour.
