### ISSUE TITLE
Seadroid SSL "Untrusted Connection" error won't go away

### ISSUE THREAD

**Issue by vr2262** [haiwen/seadroid#457]
I am running Android 5.1 and the Seadroid version is 1.9.3.

I set up a Seafile server and used an SSL certificate from Let's Encrypt. When I try to add the server in Seadroid an "Untrusted Connection" window pops up with all the fields set to "not available." When I select "Yes" for whether I want to continue, the window just comes up again.

I tweaked my server setup and tested the SSL configuration with various tools but as far as I can tell nothing is wrong. My Nginx configuration looks like this:

```
ssl_certificate /etc/letsencrypt/live/my.domain/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/my.domain/privkey.pem;
ssl_protocols TLSv1.1 TLSv1.2;
```

I also tried a few other domains to see what would happen... both `https://helloworld.letsencrypt.org:80` and `www.google.com:80` gave the same error.

**Comment by forouher** [comment]
Could you please test your HTTPS server with

https://www.ssllabs.com/ssltest/

to make sure that there are no issues with the server configuration (e.g. missing intermediate certs)?

> https://helloworld.letsencrypt.org:80 and www.google.com:80

Uhm, https and port 80 ?

**Comment by vr2262** [comment]
Oof... I was trying `https://my.domain:8082`. I should have tried `:443`.
