### ISSUE TITLE
Shibboleth Login account

### ISSUE THREAD

**Issue by matejap** [haiwen/seadroid#458]
After creating Seafile account using "Shibboleth Login", sign-in to Seafile Android application is successful but after signing  out from application and trying to relogon using account just created, I'm redirected to "Other Seafile Server" application form and I can't relogin to my account. Only workaround is to remove account and re-create account with "Shibboleth Login" form.

**Comment by egroeper** [comment]
@freeplant @killing I would really appreciate if there would be a fix for this soon, as we would like to invalidate old auth tokens regularly in the near future.

Is there anything I can do? 
If you don't like my quick solution of PR #632, how would an acceptable solution look like?
I thought about making the shibboleth property of an a account an android account feature.
Having an additional account type would be possible, too.
But these solutions would mean bigger changes in the codebase.

Are there any plans for refactoring account / account-manager code?
Would merging my PR to have a quick solution and replacing it with a better solution as a further step be an option?

**Comment by freeplant** [comment]
We have tested the PR. It is fine. We will give a detailed review this week.
