### ISSUE TITLE
Photos only upload if I open the app

### ISSUE THREAD

**Issue by hpoon** [haiwen/seadroid#459]
Android version: 5.1.1
ROM: Oxygen 2.0.3 (OnePlus Two)
App version: 1.9.3

I notice that when I take pictures, pictures do not upload right away.  When I open the Seafile app, then everything uploads to the server.  As a user, I expected that the images would upload in the background.

**Comment by shipownik** [comment]
I have the same problem. No sync in background. A Seafile process with three different services (FileMonitorService, CameraUploadService and TrensferSevice) is listed as running, but the synchronization begins only if program is open.

**Comment by forouher** [comment]
Please try Seadroid 2.0.1 (released a couple of days ago into the Play Store). It should address these issues.

**Comment by hpoon** [comment]
Looks like it started working for me a few days before I even updated the app.  I didn't change any configurations on my phone or anything.  Closing issue.
