### ISSUE TITLE
Camera upload doesn't work on Android 6

### ISSUE THREAD

**Issue by shuhaowu** [haiwen/seadroid#461]
So I know about this: https://github.com/haiwen/seadroid/issues/459 

However this is not about this. Even if I go to the transfer list, on Android 6, nothing happens. No photos are picked up and no upload task happens.

**Comment by excieve** [comment]
Same here. Doesn't upload even if the app is open.

**Comment by Logan676** [comment]
please try the latest version on google play

**Comment by excieve** [comment]
Camera upload works for me now but uploads go to "<library>/My Photos/Camera" directory instead of "<library>/Camera Uploads". Also there doesn't seem to be a notification when upload is finished.

**Comment by forouher** [comment]
@excieve Glad to hear that! Regarding these two issues: Both are design choices. A notification for every photo taken would be annoying. You can see the transfer status in the Transfer List. The directory change to "My Photos/$AlbumName" was done to properly separate media from different image albums (e.g. "Screenshots" and "Camera").
