### ISSUE TITLE
Folder name with ampersand ("&") breaks creation of new child folders

### ISSUE THREAD

**Issue by ERamseth** [haiwen/seadroid#463]
Currently I have a folder structure like this:

```
My Library
|-Folder Name 1
|-A & B Folder
```

If I try to create a new folder in `My Library/A & B Folder` called `folder3` it fails miserably and makes a mess. What I end up with is then:

```
My Library
|-Folder Name 1
|-A & B Folder
|-A
```

So it creates a new folder called `A` and no folder called `folder3`. So far I can only recreate this issue where the parent folder has an ampersand in it.

Details: Seafile CE 5.0.3 & Seafile App (seadroid) 1.9.3 downloaded from Google Play Store

**Comment by shoeper** [comment]
I can confirm this. Look very much like missing url encoding.

**Comment by ERamseth** [comment]
This is not entirely fixed. folder creation now works, but folder deletion behaves erratically and copying files from within an ampersand subfolder to anywhere else in seafile doesn't work (I get a "BAD REQUEST" message).

Using Seadroid 2.0.1 downloaded direct from github

**Comment by ERamseth** [comment]
I think overall the code for creating, copying, moving, and deleting files and directories needs to be scrubbed for correct url encoding.
