### ISSUE TITLE
"Activity" tab in BrowserActivity visible on non-pro servers

### ISSUE THREAD

**Issue by forouher** [haiwen/seadroid#468]
Search-bar is hidden (correctly). so I guess it is likely a UI issue.

**Comment by shoeper** [comment]
it has always been like that but I agree that it could get optimized

**Comment by forouher** [comment]
If I remember correctly, the tab was there in the past, however with a message along the lines of "your cheap-ass server doesn't support this cool feature" ;) But at some point this was changed and the Activity-tab went into hiding on non-pro servers.

However on current master the tab mirrors the "Starred files" tab, which seems unintended.
