### ISSUE TITLE
please update the app in Google Play store

### ISSUE THREAD

**Issue by alick** [haiwen/seadroid#472]
I see version 1.9.5 and 2.0.0 are tagged, but not pushed to Google Play store for some time. Please consider to submit the update.

The new versions are on FDroid, but with different signature, and thus uninstalling first is needed.

**Comment by shoeper** [comment]
Such tickets are of no value. Just be patient.

**Comment by Logan676** [comment]
Will release on Google Play soon, thanks for your report.
