### ISSUE TITLE
No "Rename" option for folders

### ISSUE THREAD

**Issue by gschintgen** [haiwen/seadroid#476]
Hi, in seadroid (1.9.3) there's no apparent way to rename a folder.
For files I just have to tap the light triangle on the right side of the screen and then choose "Rename". But for folders this action is not available.
Maybe a simple oversight?

**Comment by Logan676** [comment]
Please upgrade to Seafile-2.0.2 from GooglePlay, it supports to rename a folder.

**Comment by gschintgen** [comment]
Oops, sorry, due to the changed permissions the app wasn't auto-updated and I didn't notice.
Thanks for your great work!
