### ISSUE TITLE
[Feature Request] Download library on external sdcard on android version >= 4.4

### ISSUE THREAD

**Issue by zangetsu05** [haiwen/seadroid#484]
Hi all, i use seafile on my desktop with no problems,and also use it on mobile device, smartphone and tablet. I started to use it heavily on my tablet to read a large number of documents, because request for work. I didn't take a look on the space used until a warning on low space on the internal memory of the tablet. I said ok, the internal is 8GB, i can use the sdcard, 128GB to store the library....but there isn't
this possibility on the mobile client, so in the end there is no way to set where to sync the library on the mobile version of seafile. This is a big problem, because the internal storage is important for other things, mail sync, apps cache, address book sync and if you reach a low space warning all those service stop the sync process.
I'm here writing a simple request, i know that now, with the latest version of Android, to write on the external sdcard you can do it only in the Android directory dedicated directory, better than nothing! 
I'm using the 2.0.2 version on Android version 5.0.

**Comment by forouher** [comment]
As I had exactly the same need, I wrote a patch a short while ago. :) It's not yet PR-ready, as some details have to worked out (handle removing SD card, replacing SD card, code cleanup). However it works pretty well for me personally. I'll see if I can find the time to finish it up over the next weeks.

In case you're interested in bleeding-edge code, you can find it [here](https://github.com/forouher/seadroid/commits/feature/select_storage).

**Comment by Crafter6432** [comment]
+1

**Comment by 1karu5** [comment]
+1
