### ISSUE TITLE
Orbot support

### ISSUE THREAD

**Issue by JasperWeiss** [haiwen/seadroid#485]
Would it be possible to add orbot support for Seafile on Android. I'm running Seafile on a tor hidden service. (Tor hidden services are somewhat more secure than regular https connections.)

This way I can just use the .onion adress on the android client.

**Comment by Logan676** [comment]
From my searching, orbot supports encrypt your Internet traffic, which turns out to be useful. We take network security seriously too, but according to our plan, we will support client side encryption and decryption instead. So this won\`t be fixed.

**Comment by shoeper** [comment]
@Logan676 the given information is wrong. Just to clearify it: Tor helps to anonymize traffic but it's encrpytion is useless (it just makes sure that none of the nodes between you and the exit node are able to intercept traffic). The exit node is always able to intercept traffic, so server side TLS encryption is the way to go and using TOR wouldn't add any improvements in terms of data security.

**Comment by JasperWeiss** [comment]
The point is that I want to run seafile on my raspberry pi and I don't want to go ahead and setup HTTPS, buy a certificate, etc.

@shoeper wrong. Connecting to a .onion domain encrypts the connection end-to-end (if and only if the server you're connecting to is a tor hidden service.)
The security advantage is that the .onion domain itself is a hash/fingerprint of the servers public key meaning no certificate authority is needed. There's no need to trust any node or authority as long as you've got the right .onion address.

Then there's the fact that some users may actually want an anonymous connection to a server.

What's more, some firewalls may block seafiles data transfer ports and require a proxy to bypass it.

I can think of so many reasons someone would want proxy support in this app, not just for my specific use.

**Comment by shoeper** [comment]
Seafile transfers data on port 443 using nginx + ssl. And if you want to use TOR you can use the orbot app to tunnel the traffic.

**Comment by JasperWeiss** [comment]
@shoeper except the app itself needs to support orbot. (You could use root for a transparent proxy but this is not recommended) using orbots VPN feature isn't very reliable either.

**Comment by shoeper** [comment]
The Orbot app should work without Seafile customization. If it does not you'll need to root your phone. You're the first one demanding this and there are many other things on the todo list, more people are going to benefit from.
