### ISSUE TITLE
Shibboleth account creation not working since 2.0.0

### ISSUE THREAD

**Issue by egroeper** [haiwen/seadroid#488]
Hi,
we already made a post to the seafile educational forum, but without reply. Perhaps it's better to place such bugs here.

Since version 2.0.0 Seadroid crashes, if you try to create a Shibboleth account using https.
At least when connecting to our server.

The following patch at least fixes the crash and makes account creation work, but after creating the account, seadroid returns to the form, where the user entered the Shibboleth server URL.
You can the go back and the account is usable.
Obviously the real fix should perform better than that, but currently Seadroid simply doesn't work for new users, because they can't create an account.

```
diff --git a/app/src/main/java/com/seafile/seadroid2/account/ui/ShibbolethAuthorizeActivity.java b/app/src/main/java/com/seafile/seadroid2/account/ui/ShibbolethAuthorizeActivit
index 178f327..ecebf0b 100644
--- a/app/src/main/java/com/seafile/seadroid2/account/ui/ShibbolethAuthorizeActivity.java
+++ b/app/src/main/java/com/seafile/seadroid2/account/ui/ShibbolethAuthorizeActivity.java
@@ -186,8 +186,10 @@ public class ShibbolethAuthorizeActivity extends BaseActivity implements Toolbar
     }
 
     private void returnAccount(Account account) {
-        if (account == null)
-            finish();
+        if (account == null) {
+            //finish();
+            return;
+        }
 
         Intent retData = new Intent();
         retData.putExtras(getIntent());
```

Hope this gets fixed soon. We first reported this critical bug 16 days ago.

**Comment by freeplant** [comment]
It will be fixed in the next week. We have Chinese New Year holiday in the past two weeks. This postpone the fix.

**Comment by forouher** [comment]
Very likely 4c346a14eb667b2dcf92aab86edc482f681be98e is responsible for the regression. 

The patch by @egroeper is a good fix for the crash. The following patch should address the 2nd issue that the ShibbolethActivity has to be closed manually (can't test it myself):

```
--- a/app/src/main/java/com/seafile/seadroid2/account/ui/ShibbolethActivity.java
+++ b/app/src/main/java/com/seafile/seadroid2/account/ui/ShibbolethActivity.java
@@ -172,6 +172,7 @@ public class ShibbolethActivity extends BaseActivity implements Toolbar.OnMenuIt
         // pass auth result back to the SeafileAuthenticatorActivity
         if (requestCode == SHIBBOLETH_AUTH) {
             setResult(resultCode, data);
+            finish();
         }
     }
 }
```

**Comment by Logan676** [comment]
@forouher another issue was introduced by 3ffaf512b5ffb08ba937f9759c1003ce38782985, in the commit, you commented the method
```
@Override
        public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
            Log.d(DEBUG_TAG, "onReceivedSslError " + error.getCertificate().toString());

            // Ignore SSL certificate validate
            handler.proceed();
        }
```
which caused failure (login page got totally blank) when trying to login the private certificate server.

**Comment by Logan676** [comment]
@egroeper I have build a fixed version, and tested it on my server, it works fine. Not sure if it can work well on your server. You can get the apk from [here](https://github.com/Logan676/seadroid/releases/tag/2.0.2_alpha).

**Comment by forouher** [comment]
@Logan676 I'd happily take the blame, but it was more likely d33c7c2a3bc2a8bcbaf785145ec81117b6143474 ;-)

**Comment by egroeper** [comment]
@Logan676 Thanks. I can confirm, that with your additional finish()-call everything works as expected again.

But you must be kidding, if you want to deactivate SSL certificate validation by default (and without any notifications)!
We are using Seafile at a professional level and large scale at our university. Of course you then have proper certificates in place and by deactivating SSL certificate checks you are putting our users and our infrastructure at risk.

If you don't validate the certificate, you can simply use plain http.
If you nevertheless want to support self-signed certificates, you need to make this a configurable option (with proper warnings) in the client.

I'm a little scared, that apparently disabling of certificate checks was in place for a longer timespan and was only removed by accident.

@freeplant Okay. So we had bad timing with this.

**Comment by Logan676** [comment]
Sorry for that mistake, I have fixed the error and updated the APK. Now it will popup a "unsafe connection dialog" to ask if trust the connection.

**Comment by egroeper** [comment]
I'm fine with that solution. Thanks!
