### ISSUE TITLE
cannot open settings since 2.0, problem persists in all 2.x

### ISSUE THREAD

**Issue by derschueddi** [haiwen/seadroid#491]
Hello,

since version 2.0 I have the problem that I cannot open the settings dialog anymore - the app crashes without any further information than just that the app was terminated.
Currently I use the version 2.03 from f-droid repository on a Cyanogenmod 12.1 (Android 5.1). I use HTTPS to connect to my own server.

Thanks for any help

**Comment by Logan676** [comment]
Does it still crash if you try the 2.0.3 downloaded from Google Play?

I have test it on several  Android 5.1 devices, it turns out they work fine. So it may be a device related or Cyanogenmod OS related bug. 

In order to reproduce the bug, I need some info about your device, e.g. manufacturer, model number.

**Comment by derschueddi** [comment]
> Does it still crash if you try the 2.0.3 downloaded from Google Play?
I don't have google play store installed so I cannot test this. The only thing I could try is downloading it from seafile.com directly.

> I have test it on several Android 5.1 devices, it turns out they work fine. So it may be a device related or Cyanogenmod OS related bug.
Do you need any logs? If so, how could I get them?

> In order to reproduce the bug, I need some info about your device, e.g. manufacturer, model number.
Samsung S3 Mini GT-I8190
Android 5.1.1 / CynanogenMod 12.1-20160209 from www.novafusion.pl

Thank you for your response.

**Comment by derschueddi** [comment]
I downloaded the app now from seafile.com, problem is still there.

**Comment by Logan676** [comment]
to get your crash log, you can install a App like [CatLog - Logcat Reader!](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat)

**Comment by derschueddi** [comment]
Thanks, there you go

`02-24 08:40:58.291 I/Timeline(28927): Timeline: Activity_launch_request id:com.seafile.seadroid2 time:74673974
02-24 08:40:58.293 I/ActivityManager(2158): START u0 {flg=0x4000000 cmp=com.seafile.seadroid2/.ui.activity.SettingsActivity} from uid 10182 on display 0
02-24 08:40:58.305 V/WindowManager(2158): addAppToken: AppWindowToken{195b9878 token=Token{1148f5db ActivityRecord{d33aeea u0 com.seafile.seadroid2/.ui.activity.SettingsActivity t5098}}} to stack=1 task=5098 at 1
02-24 08:40:58.338 W/InputEventReceiver(28927): Attempted to finish an input event but the input event receiver has already been disposed.
02-24 08:40:58.339 D/BrowserActivity(28927): onPause
02-24 08:40:58.339 D/DefaultAppLock(28927): onActivityPaused
02-24 08:40:58.373 I/AppCompatViewInflater(28927): app:theme is now deprecated. Please move to using android:theme instead.
02-24 08:40:58.387 D/SettingsFragment(28927): onAttach
02-24 08:40:58.408 D/SettingsFragment(28927): onCreate
02-24 08:40:58.455 D/SettingsFragment(28927): onViewCreated
02-24 08:40:58.570 D/AndroidRuntime(28927): Shutting down VM
02-24 08:40:58.578 E/AndroidRuntime(28927): FATAL EXCEPTION: main
02-24 08:40:58.578 E/AndroidRuntime(28927): Process: com.seafile.seadroid2, PID: 28927
02-24 08:40:58.578 E/AndroidRuntime(28927): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.seafile.seadroid2/com.seafile.seadroid2.ui.activity.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.os.Looper.loop(Looper.java:135)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at java.lang.reflect.Method.invoke(Native Method)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at java.lang.reflect.Method.invoke(Method.java:372)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
02-24 08:40:58.578 E/AndroidRuntime(28927): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at com.seafile.seadroid2.cameraupload.GalleryBucketUtils.getVideoBuckets(GalleryBucketUtils.java:99)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at com.seafile.seadroid2.cameraupload.GalleryBucketUtils.getMediaBuckets(GalleryBucketUtils.java:44)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at com.seafile.seadroid2.ui.fragment.SettingsFragment.refreshCameraUploadView(SettingsFragment.java:326)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at com.seafile.seadroid2.ui.fragment.SettingsFragment.onViewCreated(SettingsFragment.java:258)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.app.Activity.performStart(Activity.java:6006)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2321)
02-24 08:40:58.578 E/AndroidRuntime(28927): 	... 10 more
02-24 08:40:58.584 W/ActivityManager(2158):   Force finishing activity 1 com.seafile.seadroid2/.ui.activity.SettingsActivity
02-24 08:40:58.593 W/ActivityManager(2158):   Force finishing activity 2 com.seafile.seadroid2/.ui.activity.BrowserActivity`

**Comment by forouher** [comment]
Thanks, looks like is related to Camera Upload. It scans the list of Image/Video album names for the settings dialog. The Android Media Gallery is returning a NULL for something that should be filesystem path... It's trivial to workaround, but I'd like to find out why this happens in the first place.

- Do you have any videos in your Media Gallery?
- On which filesystem path are the videos stored on the device?
- If they are stored on removable media: Is the removable media present when the bug occurs? Can you play the videos using the Gallery app?

**Comment by derschueddi** [comment]
> Do you have any videos in your Media Gallery?

Yes, some.

> On which filesystem path are the videos stored on the device?

They are stored on internal flash memory: /storage/emulated/0/Seafile/mail@address.com

> If they are stored on removable media: Is the removable media present when the bug occurs? Can you play the videos using the Gallery app?

They are not stored on removable media. Gallery app plays my videos.

Please ask if you need more details on this.

**Comment by forouher** [comment]
Thanks! So the only videos are the ones downloaded through Seadroid itself?

**Comment by derschueddi** [comment]
> So the only videos are the ones downloaded through Seadroid itself?

No, I have all kinds of videos in my gallery.

**Comment by derschueddi** [comment]
Just to make sure, I tested to go down to version 1.9.2. I can open the settings there.

**Comment by forouher** [comment]
Hm, thanks. Still not sure why that happens, but I've opened a PR that should fix the crash.

**Comment by derschueddi** [comment]
Ok. Thanks a lot!

**Comment by derschueddi** [comment]
Hey,

sorry for bringing this up again. I was very pleased to see that 2.0.4 is avaiable which contains this bugfix. But when testing I saw that the bug still exists.

So I did some debugging again with CatLog and saw that the application crashed  with the same error in the same file at line 150. I found out that the same if-statement is there.

I downloaded seafdroid source and Android APK and fixed that line as well. That version finally works on my machine.

So my question is, can you fix that as well in the next release, so I don't have to use my own branch/compilation in the future.

Thank you, Henning

**Comment by forouher** [comment]
Yes, you're right. Sorry about that, should have been obvious. Will open a 2nd PR to fix this one as well.
