### ISSUE TITLE
Edit markdown file

### ISSUE THREAD

**Issue by yopito** [haiwen/seadroid#493]
Hello, 

When I push the button Edit when previewing a *.md file, the only message I have is (translated from french): 
```
no application available to open this file
```
My environment: Seafile 4.2 and Android 5.x 

My thoughts:
1. It does not propose a list of application to use. What kind of setting is needed ? 
2. Consider adding a light Markdown editor within Seadroid application would be really nice.

Many thanks.

**Comment by forouher** [comment]
You need to have an app installed that registers itself for "text/markdown" or "text/plain" mime types. Have a look at the app store, there are likely dozens of them.
