### ISSUE TITLE
Since 2.0 not working on Android 4.3 / 5.1.x

### ISSUE THREAD

**Issue by linuxmail** [haiwen/seadroid#494]
hi,

I hassle since 2.x with the Seafile Android client :-(. First I thought, that my Fairphone2 (Android 5.1) is the problem, but today I updated the Seafile client from a Samsung Galaxy S3 phone, which has the native Android 4.3 installed (both non-rooted). Now it has the same problem. I open the client and thrown back to the "add new account" screen. It was fully working with the latest 1.9.x client.
On my Faiphone2 I have nearly the same problems. I can't add my private server anymore. After adding the credentials and enter ... the screen jumps back to the "add account". Also the back button doesn't work. Killing the app is the only way to get out.
I installed the latest 1.9.4 version I found, and it works again with my server (5.0.4 pro / subfolder / Apache2 / Lets Encrypt cert ) . Only the camera upload service can't be activated (what was the reason to upgrade to 2.x).

What can I do, to help?

**Comment by forouher** [comment]
Hm, could be a caused by a refactoring in 2.0.0. But could also be caused by other things.
I have a checklist of questions, if you don't mind :)

* Which version of Seadroid are you running?
* Is this the only server you have configured in Seadroid?
* Is the "add new account" page showing your account? Or is the list empty?
* Could you try creating an account on https://seacloud.cc and testing that one?
* Starting with 2.0.0, Seadroid requires some additional permissions regarding accounts access. Do you have any special apps/modifications installed that might restrict the permissions of the Seadroid app?

**Comment by linuxmail** [comment]
hi,

- was the latest version from Play Store
- Yepp, the only one
- First I've got the list with the Seafile cloud services and "other" Seafile-server, after choose "other" ... fill out the requirements ... "Login" ... and I'm back on the create account ... no error messages. 
- How could I create an account on seacloud.cc I don't find a button :-) ...
- No, plain installation

What I found out: after installation 1.9.4 (+ login) and upgrading via Play Store, I was able to use the existing account. But enable camera upload service isn't possible.

**Comment by forouher** [comment]
Thx! Hm, looks like account creation on seacloud.cc is currently disabled.

Could you go into more detail regarding the "camera upload service isn't possible" issue?

Other that, a log file of when you're adding a new account (and enabling the camera upload) would be very helpful. It's a bit tricky, but doable, on an non-rooted device:
1. you'll need to follow [this](https://techloverhd.com/2015/06/how-to-enable-developer-options-and-usb-debugging-on-android/) tutorial to enable ADB debugging.
2. install adb
3. run "adb logcat" (see e.g. https://developer.android.com/tools/help/logcat.html )

**Comment by linuxmail** [comment]
It instandly disable the switch, after switching on. I try out the debug mode.

**Comment by forouher** [comment]
> It instandly disable the switch, after switching on.

So you never see the Wizard? That's really strange...
Just for confirmation: On which phone, Android version and Seadroid version did you observe this?

> I try out the debug mode

Thanks, the logs might illuminate the situation

**Comment by linuxmail** [comment]
Ui, a lot of output :-)

Uninstalled Seafile, reinstalled the 4.2 from playstore. Opened ... filled login credentials .... 

```
grep -i seafile  fp2.log  --color
D/ApplicationRunInfoManager( 1773): Fairphone - Qs : 0 : Most Used : Adding ComponentInfo{com.seafile.seadroid2/com.seafile.seadroid2.ui.activity.BrowserActivity} to first position
W/PackageManager( 1773): Failure retrieving resources for com.seafile.seadroid2: Resource ID #0x0
D/ApplicationRunInfoManager( 1773): Logging application : ComponentInfo{com.seafile.seadroid2/com.seafile.seadroid2.ui.activity.BrowserActivity} : 3
I/GrantAccessActivity(10621): GrantAccessActivity - com.seafile.seadroid2
F/PrivacyImpactService(  867): Querying Package name: com.seafile.seadroid2
I/Timeline(10621): Timeline: Activity_launch_request id:com.seafile.seadroid2 time:64882137
I/Timeline( 4348): Timeline: Activity_launch_request id:com.seafile.seadroid2 time:64882265
F/PrivacyImpactService(  867): Querying Package name: com.seafile.seadroid2
I/Timeline( 4348): Timeline: Activity_first_launch com.seafile.seadroid2 time:64882278
I/GrantAccessActivity(10621): GrantAccessActivity - com.seafile.seadroid2
F/PrivacyImpactService(  867): Querying Package name: com.seafile.seadroid2
I/Timeline(10621): Timeline: Activity_launch_request id:com.seafile.seadroid2 time:64882343
I/ActivityManager(  867): Displayed com.seafile.seadroid2/.ui.activity.AccountsActivity: +106ms (total +327ms)
I/Timeline(  867): Timeline: Activity_windows_visible id: ActivityRecord{3f4d6595 u0 com.seafile.seadroid2/.ui.activity.AccountsActivity t1235} time:64882480
D/SeafileAuthenticator( 4348): addAccount of type com.seafile.seadroid2.account.api2
I/Timeline( 4348): Timeline: Activity_launch_request id:com.seafile.seadroid2 time:64883589
F/PrivacyImpactService(  867): Querying Package name: com.seafile.seadroid2
I/Timeline( 4348): Timeline: Activity_first_launch com.seafile.seadroid2 time:64883615
I/GrantAccessActivity(10621): GrantAccessActivity - com.seafile.seadroid2
F/PrivacyImpactService(  867): Querying Package name: com.seafile.seadroid2
I/Timeline(10621): Timeline: Activity_launch_request id:com.seafile.seadroid2 time:64883667
D/SeafileAuthenticatorActivity( 4348): onCreate
I/ActivityManager(  867): Displayed com.seafile.seadroid2/.account.ui.SeafileAuthenticatorActivity: +152ms (total +206ms)
I/Timeline(  867): Timeline: Activity_windows_visible id: ActivityRecord{2324c8bd u0 com.seafile.seadroid2/.account.ui.SeafileAuthenticatorActivity t1235} time:64884212
I/Timeline( 4348): Timeline: Activity_launch_request id:com.seafile.seadroid2 time:64884932
F/PrivacyImpactService(  867): Querying Package name: com.seafile.seadroid2
I/Timeline( 4348): Timeline: Activity_first_launch com.seafile.seadroid2 time:64884962
I/GrantAccessActivity(10621): GrantAccessActivity - com.seafile.seadroid2
F/PrivacyImpactService(  867): Querying Package name: com.seafile.seadroid2
I/Timeline(10621): Timeline: Activity_launch_request id:com.seafile.seadroid2 time:64885034
I/ActivityManager(  867): Displayed com.seafile.seadroid2/.account.ui.AccountDetailActivity: +242ms (total +336ms)
I/Timeline(  867): Timeline: Activity_windows_visible id: ActivityRecord{2e2124d6 u0 com.seafile.seadroid2/.account.ui.AccountDetailActivity t1235} time:64885685
I/Timeline(  867): Timeline: Activity_windows_visible id: ActivityRecord{2e2124d6 u0 com.seafile.seadroid2/.account.ui.AccountDetailActivity t1235} time:65009687
V/WindowManager(  867): Adding window Window{44dbb09 u0 PopupWindow:26df03e5} at 23 of 29 (after Window{28e2b862 u0 com.seafile.seadroid2/com.seafile.seadroid2.account.ui.AccountDetailActivity})
W/PackageManager( 1276): Failure retrieving resources for com.seafile.seadroid2: Resource ID #0x0
W/PackageManager( 1276): Failure retrieving resources for com.seafile.seadroid2: Resource ID #0x0
I/Timeline(  867): Timeline: Activity_windows_visible id: ActivityRecord{2e2124d6 u0 com.seafile.seadroid2/.account.ui.AccountDetailActivity t1235} time:65080789
V/WindowManager(  867): Adding window Window{1bbeb725 u0 PopupWindow:b80f961} at 23 of 29 (after Window{28e2b862 u0 com.seafile.seadroid2/com.seafile.seadroid2.account.ui.AccountDetailActivity})
V/WindowManager(  867): not Base app: Adding window Window{3201b920 u0 com.seafile.seadroid2/com.seafile.seadroid2.account.ui.AccountDetailActivity} at 23 of 29
D/SeafileAuthenticatorActivity( 4348): onActivityResult
I/Timeline(  867): Timeline: Activity_windows_visible id: ActivityRecord{3f4d6595 u0 com.seafile.seadroid2/.ui.activity.AccountsActivity t1235} time:65086579
```
Attached file -> Log .. uninstalled Seafile 2.4, installed 1.9.4 and started camera upload service.
[Uploading seafile-debug.txt…]()

**Comment by forouher** [comment]
That was fast, thx! Unfortunately, grepping for seafile is not enough.

Of interest is this part:

> D/SeafileAuthenticatorActivity( 4348): onCreate
[<--- very interesting]
> D/SeafileAuthenticatorActivity( 4348): onActivityResult
[<--- very interesting]
[up till one of these messages comes up:]
> D/DefaultAppLock: onActivityResumed
> D/AccountsActivity: refreshView

**Comment by forouher** [comment]
(this is for the first case, adding a new account)

**Comment by forouher** [comment]
After some debugging via email, turns out the bug is specific to the Fairphone. The Fairphone runs a modified version of Android 5.1, and these modifications cause bugs in various apps:

https://forum.fairphone.com/t/misbehaving-apps-will-be-fixed-with-first-update-workaround-re-enable-privacy-impact/11721
https://forum.fairphone.com/t/seafile-android-client-2-x/15104/1

So it is my understanding that this issue can be closed.

**Comment by linuxmail** [comment]
Yepp, it can be closed. Thanks for debugging :-)
