### ISSUE TITLE
Your English language version needs corrections

### ISSUE THREAD

**Issue by jult** [haiwen/seadroid#504]
And I'm the one to do it for you. ;-)
For example
_"Seafile will now uploading files from your selected folders"_
needs to be
_"Seafile will begin uploading files from your selected folders after you confirm below"_

and so on. It's really sloppy language in your Android app.

**Comment by shoeper** [comment]
Feel free to submit improvements to transifex. https://www.transifex.com/haiwen/seadroid/

**Comment by jult** [comment]
I'm asking here because there is no English version on transifex to work on or apply for.. It's considered finished, probably.

**Comment by shoeper** [comment]
Thanks for pointing that out.

**Comment by jult** [comment]
I've asked to join for Dutch though, because that's my first language, and I'm quite good at writing (UI/technical stuff) so if I find the time I'll add translations for seafile.

**Comment by Logan676** [comment]
Already accepted your request on transifex. 😃

**Comment by freeplant** [comment]
@Logan676 Isn't the English version should be modified in the source code directly?

**Comment by shoeper** [comment]
I think this is the file you're looking for https://github.com/haiwen/seadroid/blob/master/app/src/main/res/values/strings.xml editing it using Github Webeditor should be fine ;)

**Comment by Logan676** [comment]
done!
