### ISSUE TITLE
Camera/photo upload simply does not work

### ISSUE THREAD

**Issue by jult** [haiwen/seadroid#505]
I went through all the Left swipes about 4 times now, Confirmed at the end, and nothing happens.
Also restarted the app, restarted the Android system, to no avail. In the transfer list under Upload list ït remains silent with "No upload tasks yet".

Yes, I'm logged in, all is fine, I'm on WiFi.

This is all for Android 5.01 on a Samsung Note 4.

**Comment by forouher** [comment]
Did you stick with "Auto scan device" or did you manually select some gallery albums? In case of the former, could you please try again with manually selecting some albums? (Maybe the auto scan didn't work on your device)

**Comment by jult** [comment]
Of course I started by custom selecting camera folders. Still nothing is uploading.

**Comment by forouher** [comment]
Hm, okay.

Could you try one more thing:

Please go to Android Settings -> Accounts -> Seafile -> [your account]
- What "Last time synched" timestamp is currently displayed there?
- When you select "Sync now" (in the options menu), is the timestamp updated to present time?

**Comment by jult** [comment]
Apparently sync was turned off by the OS itself. Thanks! Why does it require or depend on that? I don't want my Android syncing google, or any other app that is listed under accounts. You should at least mention that after confirming, that it depends on the "sync" feature of android itself, I don't think it's self-explanatory. Would never have thought of that.

**Comment by forouher** [comment]
Glad to hear!

Android SyncAdapters are the preferred way of doing server/client data sync on Android. The API offers a lot of nice features like

- automatic retry on network errors
- grouping of pending sync operations to save battery
- ...

SyncAdapters are not related to GCM or other Google-related services. The SyncAdapter API is part of the AOSP Framework and works even when one uses a firmware that doesn't contain Google-related apps.
Therefore I don't think the typical user will take any objections with the fact that Seadroid uses SyncAdapters. In any case the Seadroid should advertise it by claiming the WRITE_SYNC_SETTINGS permission.

**Comment by Logan676** [comment]
@forouher So do you think we should show a snake bar to train the users?

**Comment by forouher** [comment]
@Logan676 I'm not sure, what a snake bar is. :) But I have an idea for a patch that completely disables camera upload in the SettingsFragment, if synchronisation is globally disabled in all of Android. Will create a PR later.

**Comment by jult** [comment]
Let's be clear on this: Both the syncthing app and the tresorit app did not suffer from this. They synced when you asked it to sync.

**Comment by shoeper** [comment]
> But I have an idea for a patch that completely disables camera upload in the SettingsFragment, if synchronisation is globally disabled in all of Android. 

I'm not sure if this is a good idea. The global settings can get changed like the user wants. This would lead to a behaviour where the menu is sometimes there and sometimes not. Better just show a toast or something similiar stating that the camera upload only works as long as account synchronization has not been disabled in the android settings.

**Comment by forouher** [comment]
@shoeper The menu entry is still there, only grayed out. But you're making a good point. I've added a text info in the summary-field, explaining why its disabled (see #509).

**Comment by forouher** [comment]
@jult Let's have a look at that setting and the warning that Android displays:

![screenshot_2016-04-14-16-38-26](https://cloud.githubusercontent.com/assets/676900/14532669/26550efc-0262-11e6-9e4d-2a48568c6ac2.png)

You're assumption was that Seadroid camera upload is not connected with "auto-sync data". And that's a valid assumption to make. This warning speaks about information, and certainly never mentions photo upload.

But at the same time, I'd wager that there are other users who *will* draw the connection and might even *expect* Seadroid to stop syncing files. After all, they've just globally disabled data sync, haven't they?

PR #509 adds some UI changes that should make it clearer that camera upload is dependent on global auto-sync. If you have any other ideas on how to make the UI better match user experience, I'm listening.

**Comment by shoeper** [comment]
> But at the same time, I'd wager that there are other users who will draw the connection and might even expect Seadroid to stop syncing files. After all, they've just globally disabled data sync, haven't they?

I agree on this and think it's good to use what Android provides natively.

**Comment by Logan676** [comment]
The patch just merged, you guys rock! 😃
