### ISSUE TITLE
Android and iOS Apps Inconsistent

### ISSUE THREAD

**Issue by werkkrew** [haiwen/seadroid#515]
After reading through PR 444, https://github.com/haiwen/seadroid/pull/444

I am aware of some of what the team does and does not want to do with respect to the camera upload feature set.  This issue is to explore the possibility of making the iOS and Android apps consistent in how they implement photo upload, specifically with respect to the path photos are uploaded.

For example, on the android app if I choose the library "Photos" to be my photo destination they will go into:

`Photos -> My Photos -> Album name (e.g. camera)`

On iOS they will go to:

`Photos -> Camera Uploads`

I am not certain if the development teams for the two apps work together at all but it would be nice if the apps were consistent.  My reason for this is that I have two phones, one iPhone and one Android phone, and I would like all of my camera uploads to land in the same place, if possible.

**Comment by Logan676** [comment]
Thanks for your report, we will discuss about it and comment back soon.
