### ISSUE TITLE
64 kB file size download limit on Android?

### ISSUE THREAD

**Issue by lulingar** [haiwen/seadroid#521]
Running seafile server stack version 5.1.1-1 on ArchLinux armv7h (Raspberry Pi 2), with MariaDB (MySQL) behind nginx, with a real SSL certificate (from lets-encrypt).

I can download whatever file I want from the desktop client and the web interface on a desktop, but on Android (Marshmallow), only files as large as **64 KB** or smaller can be downloaded via the web interface (i.e. Firefox for Android) or this client, and the rest fail with the "download failed" error. I tracked that limit down experimentally, trying randomly generated files of various sizes. I show my config files below:

- ccnet.conf

```
[General]
USER_NAME = a_name
ID = an_id
NAME = a_name
SERVICE_URL = https://mydomain.co

[Network]
PORT = 10001

[Client]
PORT = 13418
```
- seafile.conf

```
[network]
port=12001

[fileserver]
port = 8082
```
- seahub_settings.py

```
SECRET_KEY = 'censored'
FILE_SERVER_ROOT = 'https://mydomain.co:443/seafhttp'
```
- Nginx configuration

```
server {
    listen       80;
    server_name  www.mydomain.co mydomain.co;

    location / {
        return 301  https://mydomain.co$request_uri;
    }
}

server {
    server_name mydomain.co;
    listen 443;
    #...SSL stuff...

    access_log /srv/http/log/seahub/access.log main;
    error_log  /srv/http/log/seahub/error.log  error;

    proxy_set_header X-Forwarded-For $remote_addr;
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
    server_tokens off;

    location / {
        fastcgi_pass    127.0.0.1:8000;
        fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
        fastcgi_param   PATH_INFO           $fastcgi_script_name;

        fastcgi_param   SERVER_PROTOCOL     $server_protocol;
        fastcgi_param   QUERY_STRING        $query_string;
        fastcgi_param   REQUEST_METHOD      $request_method;
        fastcgi_param   CONTENT_TYPE        $content_type;
        fastcgi_param   CONTENT_LENGTH      $content_length;
        fastcgi_param   SERVER_ADDR         $server_addr;
        fastcgi_param   SERVER_PORT         $server_port;
        fastcgi_param   SERVER_NAME         $server_name;
        fastcgi_param   REMOTE_ADDR         $remote_addr;
        fastcgi_param   HTTPS               on;

        access_log      /srv/http/log/seahub/cgi.access.log;
        error_log       /srv/http/log/seahub/cgi.error.log;
    }

    location /seafhttp {
        rewrite ^/seafhttp(.*)$ $1 break;
        proxy_pass http://127.0.0.1:8082;
        client_max_body_size 0;
        proxy_connect_timeout  36000s;
        proxy_read_timeout  36000s;
        proxy_send_timeout  36000s;
    }

    location /media {
        root /home/seafile/seafile-server/seahub;
    }
}
```

**Comment by lulingar** [comment]
I thought of monitoring changes in log files across the entire software stack, and I see this kind of error creeping in the nginx access log:
```
2016/05/07 20:57:35 [crit] 1352#1352: *4216 open() "/var/lib/nginx/proxy/2/04/0000000042" failed (13: Permission denied) while reading upstream, client: 192.168.1.184, server: emlin.co, request: "GET /seafhttp/files/034a2f4d-788e-4a39-8a5e-0cfcf91c50a8/algo.txt HTTP/1.1", upstream: "http://127.0.0.1:8082/files/034a2f4d-788e-4a39-8a5e-0cfcf91c50a8/algo.txt", host: "emlin.co"
```
where `algo.txt` is a file I generate randomly to test the file size threshold for success/failure when attempting to download.

As commented before, this error does not happen when trying to download from desktop browser/seafile client.

**Comment by lulingar** [comment]
I thought of monitoring changes in log files across the entire software stack, and I see this kind of error creeping in the nginx access log:
```
2016/05/07 20:57:35 [crit] 1352#1352: *4216 open() "/var/lib/nginx/proxy/2/04/0000000042" failed (13: Permission denied) while reading upstream, client: 192.168.1.184, server: emlin.co, request: "GET /seafhttp/files/034a2f4d-788e-4a39-8a5e-0cfcf91c50a8/algo.txt HTTP/1.1", upstream: "http://127.0.0.1:8082/files/034a2f4d-788e-4a39-8a5e-0cfcf91c50a8/algo.txt", host: "mydomain.co"
```
where `algo.txt` is a file I generate randomly to test the file size threshold for success/failure when attempting to download.

As commented before, this error does not happen when trying to download from desktop browser/seafile client.

**Comment by lulingar** [comment]
I thought of monitoring changes in log files across the entire software stack, and I see this kind of error creeping in the nginx access log:
```
2016/05/07 20:57:35 [crit] 1352#1352: *4216 open() "/var/lib/nginx/proxy/2/04/0000000042" failed (13: Permission denied) while reading upstream, client: 192.168.1.184, server: mydomain.co, request: "GET /seafhttp/files/034a2f4d-788e-4a39-8a5e-0cfcf91c50a8/algo.txt HTTP/1.1", upstream: "http://127.0.0.1:8082/files/034a2f4d-788e-4a39-8a5e-0cfcf91c50a8/algo.txt", host: "mydomain.co"
```
where `algo.txt` is a file I generate randomly to test the file size threshold for success/failure when attempting to download.

As commented before, this error does not happen when trying to download from desktop browser/seafile client.

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile-server.org/.

**Comment by lulingar** [comment]
@shoeper Sorry for the noise. I have opened [a topic in the forum](https://forum.seafile-server.org/t/64-kb-file-size-download-limit-on-android/4847/1), and I have seen what the issue is. It had to do with a subtle Nginx configuration inconsistency I had introduced.

**Comment by Logan676** [comment]
At the very beginning, I thought it was an [Building Apps with Over 64K Methods](http://developer.android.com/intl/zh-cn/tools/building/multidex.html) issues, the title is a little bit misleading by the way.
