### ISSUE TITLE
Activity feed bug

### ISSUE THREAD

**Issue by shoeper** [haiwen/seadroid#524]
Clicking on an entry added / modified xyz and one more file always leads to an error and suggests to check connection.

Everything else works and the connection is 100% stable (the server as well, 5.0.4 pro).
Clicking on an entry with added or modified xyz opens file and clicken on an entry added or modified xyz and 10 more files shows the list of all changes.

Experienced using the most recent gplay version (as of Jan 29th 2016).

**Comment by Logan676** [comment]
Can you tell me how to reproduce the bug?

**Comment by shoeper** [comment]
Ok I just moved the issue from seahub to seadroid. Looks like it has been fixed in the current gplay version.
