### ISSUE TITLE
Multiple folder for the same library and duplicate files

### ISSUE THREAD

**Issue by tntodorov** [haiwen/seadroid#525]
Hi,

I have a private server and use it with multiple Windows and Android clients. The issue I am describing below affects the Android client.

Recently I noticed the disappearance of some files that I had previously synchronized with my private server (i.e. the icon under the file name showing locally downloaded files was gone), and I had to download them again. This happened multiple times. When I investigated further, I realized, that the client has multiple folders for the same library - named in the manner **Library**, **Library (1)**, etc. See screenshot for an example. Looking into the folders themselves, I found all the files I had already downloaded, but earlier files were in folder **Library** (later these appeared to be gone), and more recently synced files were in folder **Library (1)**. All files that I re-downloaded since they were "lost", were to be found in both folders.

So when I sync a specific file for a second time, I an only creating duplicates on my local system and it is eating up space,..

So far I have not been able to figure out when the client creates a new folder for the same library and switches to it. Also, the only way to fix this, is to delete the associated account on the Android device, forcibly stop the client from the Apps settings, manually delete the top Seafile folder, and re-connect the account again. Then it will be ok for a while, but at some point it will start duplicating library folders again.

My client version is 2.0.6
Android 5.1.1 on Nexus 10 tablet
Server version is 4.4.3 running on Ubuntu 14.04 LTS server (64bit) 

![screenshot_2016-05-21-15-55-47](https://cloud.githubusercontent.com/assets/9284623/15450670/d50f7818-1f6f-11e6-9cd0-c889a7120ab6.png)

**Comment by freeplant** [comment]
This maybe caused by an old version. In version 2.0.6, the storage code is rewritten, which may already solved this problem. We will wait and check whether this problem is still there.

**Comment by forouher** [comment]
> So far I have not been able to figure out when the client creates a new folder for the same library and switches to it.

Technically, this will happen whenever the "RepoDir" SQLite table is cleared, which is done during a database upgrade. Recently some new Seadroid releases required a database upgrade, causing the issue you observed as a sideeffect (IIRC that were upgrades to version 2.0.6 and 2.0.0).
