### ISSUE TITLE
Adoptable Storage

### ISSUE THREAD

**Issue by fr500** [haiwen/seadroid#533]
With adoptable storage I noticed that even if the app is moved to the SD card, the cache is still kept in the internal SD card folder.

Are there any possible workarounds?

**Comment by forouher** [comment]
Hi @fr500,

I'm assuming

- you are using Android 6.0
- you are using Seadroid 2.0.6 or later
- you are using the novel "Adoptable storage" feature of Android 6.0

Is this correct?

Hm, what you are describing should be technically impossible. So

- Could you please provide some info on how you came to that conclusion?
- What is the size of the internal storage of your device?
- What is the size of the SD card of your device?
- What "free/total" sizes is Seadroid showing in its preferences when selecting "Select storage location"?

**Comment by shoeper** [comment]
The cache location can be selected in settings. Could imagine this is the reason why the internal storage is being used.

**Comment by Logan676** [comment]
> With adoptable storage I noticed that even if the app is moved to the SD card, the cache is still kept in the internal SD card folder.

It doesn\`t make any sense to move the app for moving cache purpose. In order to move the cache from internal SD card to external storage, please use the adoptable storage settings.

**Comment by fr500** [comment]
@forouher @Logan676 seafile stores the data cache in /sdcard/Seafile. That is not moved together with the application by using adoptable storage, as simple as that. 

@forouher 
Correct
My device is an NVIDIA Shield Tablet running 6.0.1.

Current status before testing:

- My device has 16GB internal storage and a 32GB SD card
- Adoptable storage is enabled, in 'Seafile' in android applications Storage Used reads: 'SD card'
- Space used in the same page is 3.61MB
- Right now I have 8.16GB used (of 40.51GB) as reported by 'Storage & USB' in android settings, it shows both storage spaces (Internal Storage 6.28 GB/11.95 GB) (SD Card 1.88 GB/28.56 GB)
- Cache size under seafile reads 859MB

Now I am gonna download roughly 2 GB to the device

**Comment by forouher** [comment]
Looks fine to me so far. With adoptable storage, all the directory paths stay the same. The storage switch is done underneath by Android using mount and directory links.

Please go to the *Seafile Prefetences*, and select *Choose storage location*. There you will see the free size of the device Seafile is actually using.

Am 19. Juni 2016 23:40:24 MESZ, schrieb "Andrés" <notifications@github.com>:

**Comment by fr500** [comment]
Yes, and it shows the space of the internal storage, not of the external storage.
I understand that the dirs don't change and that is the problem, the "home dir" or whatever you want to call it stays in the internal sdcard apparently, for example chrome downloads or anything like that keeps going there.

**Comment by forouher** [comment]
Okay, are you certain that adoptable storage is actally enabled? IIRC unless the vendor did it, you have to do it yourself.

Am 20. Juni 2016 07:04:10 MESZ, schrieb "Andrés" <notifications@github.com>:

**Comment by fr500** [comment]
Yes I can take screenshots in the morning of you wish

**Comment by forouher** [comment]
Well, just be sure. Anyways, if Chrome is not using the external SD card as well, the problem isn't with Seadroid.

Am 20. Juni 2016 08:56:09 MESZ, schrieb "Andrés" <notifications@github.com>:
