### ISSUE TITLE
Clicking transfer list causes force close

### ISSUE THREAD

**Issue by ERamseth** [haiwen/seadroid#534]
Clicking transfer list causes a force close every time.  

Device: HTC10
Android version: 6.0.1
Seafood version: 2.1.0

**Comment by ERamseth** [comment]
Erm, that should read "seadroid" not "seafood"

**Comment by nidomiro** [comment]
I have the same issue after removing the 2.0.6 version from G-Play and installing the 2.1.0 from F-Droid. But I would say the App Crashes - not force close.

Device: Galaxy S5
Android version: 5.0.1
Seadroid version: 2.0.1
Reproducible: every time

**Comment by nidomiro** [comment]
The Camera-Fileupload also doesn't work for me

**Comment by Logan676** [comment]
@ERamseth @nidomiro  Could you please try to use the latest version from [here](GitHub. com/haiwen/Seadroid/release) and try again

**Comment by nidomiro** [comment]
For me everything is working again, thanks

**Comment by nidomiro** [comment]
With this version I discovered that I'm unable do download any file from an encrypted Library (with clientside encryption active). I have tested only this configuration, so I cannot say which other config may work. I switched to 2.0.6 again, which is working.

**Comment by Logan676** [comment]
@nidomiro Can you first try to upload a file to your enc library and then download it again, does it work?
