### ISSUE TITLE
Cannot download files from encrypted library with client encryption enabled

### ISSUE THREAD

**Issue by nidomiro** [haiwen/seadroid#537]
Everything is tested with an encrypted library on the (selfhosted) server.
If I disable clientside encryption, everything works as expected.
With clientside encryption enabled downloading an existing file fails with the messages (translated) "Download failed" followed by " The file "<filename>" has been deleted.
Creating an file through the app and uploading an existing file works fine. If I upload an existing txt-file containing "test", results in an file containing the word "test" followed by the null-character until an filesize of 2k is reached.
Downloading the file created through the app immediately after creation results in an crash of seafile.
Deleting the uploaded file inside the "Android/media/com.seafile.seadroid2/<accountname>/<Libname>/" folder and trying to download it again results in the same errors mentioned before.

Device: Galaxy S5
Android version: 5.0.1
Seadroid version: 2.1.0 ( [from here](https://github.com/haiwen/seadroid/issues/534#issuecomment-224305772) )
Reproducible: every time

**Comment by Logan676** [comment]
What\`s your server configuration?
FYI, make sure your server side supports [Repo encryption version 2] (https://github.com/haiwen/seafile/commit/43fdaae5027820579db02f7b953e9bcb8e76b64f) and seahub supports encryption related APIs, e.g.`api2/repos/%s/files/%s/blks/%s/download-link/`

> With clientside encryption enabled downloading an existing file fails with the messages (translated) "Download failed" followed by " The file "" has been deleted.

The error message`some file has been deleted` only appears in following two cases
1. For downloading and exporting a file to other apps
2. For download the file within the app
which one is yours?

**Comment by nidomiro** [comment]
> The error messagesome file has been deleted only appears in following two cases
> 1. For downloading and exporting a file to other apps
> 2. For download the file within the app
> which one is yours?

I just touched the file inside the app, so I would say 2.

> What`s your server configuration?

My server-version is 5.0.2 and running behind apache2 with mysql - the rest of the config is stock. Since this commit is from 2013 I would say my server should support it ;)

**Comment by Logan676** [comment]
Only server version  5.1+ supports those APIs, so you should upgrade your server version before using the feature.

**Comment by nidomiro** [comment]
Maybe you could implement some warning inside the app instead.
I'll upgrade my server and test it again.
Thanks

**Comment by Logan676** [comment]
Will do

**Comment by nidomiro** [comment]
So, with the server version 5.1.3 it's working nearly as expected ;)
The bug with the `null-characters` still exists.
Steps to reproduce:
Android App: client-side encryption enabled
1. Create an textfile with the content `test` through the app in an encrypted library
2. Let it sync to your PC (in my case Win 7 and client-version 5.1.2)
3. Open the file with an editor, which can display "unreadable" files (in my case notepad++) or simply an Hex-Editor. There you see the word `test `followed by many `null-caracters` (in hex `74 65 73 74 ` followed by `00` until address `0x001FFFFF`)

You get the same result if you create the file on the PC, download it with the app and view the file on the phone (`Android/media/com.seafile.seadroid2/...`)

**Comment by Logan676** [comment]
So could you please help to confirm that the "null-characters" bug only exists under enc libraries? Did you try the normal libraries?

**Comment by nidomiro** [comment]
Normal libraries have no "null"-caracters-bug and encrypted librarys with clientside encryption disabled also work normal.

**Comment by Logan676** [comment]
> Downloading the file created through the app immediately after creation results in an crash of seafile.
> Deleting the uploaded file inside the "Android/media/com.seafile.seadroid2///" folder and trying to download it again results in the same errors mentioned before.

I reproduced the crash and seems like both client side and server side don\`t specifically handle the newly created files under enc libraries. So when try to download the file, the block list of the file is empty and that caused a crash.

**Comment by Logan676** [comment]
> 1. Create an textfile with the content test through the app in an encrypted library
> 2. Let it sync to your PC (in my case Win 7 and client-version 5.1.2)
> 3. Open the file with an editor, which can display "unreadable" files (in my case notepad++) or simply an Hex-Editor. There you see the word testfollowed by many null-caracters (in hex 74 65 73 74 followed by 00 until address 0x001FFFFF)

I have no idea about this, maybe it caused by the "PKCS7Padding". I use neither `Windows` nor notepad++, and I have tried to reproduce the bug like below with no success.
1. normal libraries, created a `test.txt` file with content `test` in seahub (the web), sync to the phone and view it without any null-characters, my viewer is a app called WPS
2. pull the `text.txt` file to my laptop and view by `Sublime Text` with Settings-Preference-Users-`"draw_white_space": "all",` turned on, everything works fine
3. encrypted libraries, upload the above `test.txt` file, download it via seahub, view it by `Sublime Text` and all works fine, no null-characters were found.
4. created the file `text2.txt` with content `test2` on seahub and sync to the phone and view it by `Sublime Text` and no null-characters were found as well.

**Comment by nidomiro** [comment]
I have no idea whats going on... now after reenableing clientEnc I cannot upload my changed textfiles anymore... it always says "Upload failed".
Update:
After removing both Files from `Android/media/com.seafile.seadroid2/...` everything works again (both settings, serverEnc and clientEnc). I have no idea how this bug could happen. Maybe because I used the text-editor that comes with the app `Root Browser` (which has root rights). But after deleting the files I did the exact same thing: Download it via the app, open it via the app, edit it, save it, upload it via the app.
So I have no way of reproducing the error right now.

I'll append the file with the "null"-caracters from the tests before so that you can see the mysterious result.
[localtestfile.txt](https://github.com/haiwen/seadroid/files/316646/localtestfile.txt)

**Comment by Logan676** [comment]
@nidomiro This snapshot should fix the "null-character" bug as you observed. You can get and download it from [here](https://github.com/Logan676/seadroid/releases/tag/2.1.0_fix_null_characters_bug)
