### ISSUE TITLE
Client not trusting Let's Encrypt certificate

### ISSUE THREAD

**Issue by der-eismann** [haiwen/seadroid#544]
As @silberzwiebel reported it first in a different project (https://github.com/haiwen/seafile-client/issues/813):
Seadroid 2.1.0 doesn't trust Let's Encrypt certificates. I have no problems with the desktop clients, web interface or version 2.0.6. Is this a known bug? Because 2.0.6 remains the latest version in the Play Store.

![screenshot_2016-06-25-00-35-14](https://cloud.githubusercontent.com/assets/10406217/16352331/b723f798-3a6d-11e6-9773-3d0f6a3bb3f7.png)

**Comment by Logan676** [comment]
I guess it was fixed in f8d768a828f56e286a9124c03601cefbc8536d86, please try the latest version from [here](https://github.com/haiwen/seadroid/releases/tag/2.1.0)

**Comment by der-eismann** [comment]
You're right, problem was fixed. Maybe someone should push this update to F-Droid.

**Comment by Logan676** [comment]
@der-eismann I already tagged the [2.1.1]( https://github.com/haiwen/seadroid/releases/tag/2.1.1) and F-Droid version will be auto released soon. Also you can get the latest version from here [2.1.1]( https://github.com/haiwen/seadroid/releases/tag/2.1.1)
