### ISSUE TITLE
Natural sorting for files and folders

### ISSUE THREAD

**Issue by FlorianLoch** [haiwen/seadroid#545]
I use to prepend names of folders with numbers in case I have more than 5 subdirectories... I guess this is quite common therefore I would really appreciate if the Android app would be able to sort my items in a more natural way like Finder, Explorer, ls etc. do.

![image](https://cloud.githubusercontent.com/assets/5587805/16361680/5e5bc5b0-3b98-11e6-9080-c83dc38b96c6.png)

vs.

![image](https://cloud.githubusercontent.com/assets/5587805/16361686/9abbf516-3b98-11e6-8978-e3aa086f80d1.png)

If there is a chance this feature would get merged into the project I would implement it and open a pull request.

**Comment by Logan676** [comment]
> If there is a chance this feature would get merged into the project I would implement it and open a pull request.

@FlorianLoch We also think this feature is nice and look forward to your contributions. 😄
