### ISSUE TITLE
Crash when opening KeePass .key file

### ISSUE THREAD

**Issue by serathius** [haiwen/seadroid#551]
Crashes every time I try to open the file.

App Version: 2.0.6
Os CyanogenMod: 12.1-20151007 android: 5.1.1
Standard KeePass2 key file.
extension: .key
File in question was used for testing, it's not private.

**Comment by Logan676** [comment]
1. Does it crash if you try to open other extension files?
2. Under which tab, Libraries, Activities or Starred did it crash when you try to open the file
3. Does it work if you try to use the [latest version](https://github.com/haiwen/seadroid/releases/tag/2.1.2)?
