### ISSUE TITLE
Refreshing the list of libraries doesn't work as expected

### ISSUE THREAD

**Issue by 0x64746b** [haiwen/seadroid#558]
# Reproduction

 - Open the Android app
 - Select the `LIBRARIES` tab
 - Create a new lib on the server via the web interface
 - Pull to refresh the list of libraries

# Observed behaviour

 - The list of libraries does not change

# Expected behaviour

 - The newly created library should appear in the list

# Cause

When [pulling to refresh](https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java#L137) the `forceRefresh` parameter [defaults to `false`](https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java#L336), which [leads](https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java#L370) to the list of libraries being [read from the local cache](https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java#L371) instead of being [fetched from the server](https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java#L383).

# Possible fix

I cannot think of a situation where an explicit pull to refresh is not supposed to sync with the server (especially since the current version doesn't have the ability to locally manipulate libraries). Therefore I would suggest to just call `refreshView()` with `forceRefresh=true`.

Am I missing sth here? :)
dtk

**Comment by zekrg** [comment]
For me not only the library list won't get refreshed but also the file list inside of a library won't refresh as well when doing pull to refresh.

**Comment by 0x64746b** [comment]
Ah, yeah, that's the same fragment, so the same code path [up to a point](https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java#L347), and after that it's the same pattern: if [`forceRefresh` isn't set](https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java#L411), the [cached `Dirents`](https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java#L412) are shown instead of fetching them [from the server](https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java#L425).

So that would be automagically fixed as well.
