### ISSUE TITLE
[BUG] Android N - not supported

### ISSUE THREAD

**Issue by soakes** [haiwen/seadroid#577]
[SNIP]

Please accept my sincere apologies for the noise.

I have managed to track down the issue after closer examination and found it to be located on the server.  Even tho the web and desktop client was responding fine/correctly, for some reason the Android client/OS seems to be more picky.  

The problem was linked to the SSL cert and i'm not sure if Android N seems to be more picky or what but anyway, problem is now all resolved and have a nice solid A+ like it should be.

FYI, if anyone has issues, double check with ssllabs.com if you have CERT issues and see if that fixes your problem especially if your on Android N.

**Comment by fuelflo** [comment]
So what did you need to fix exactely, please?

I have a friend with Android 7 who cannot connect anymore with seadroid, but my SSL config actually is as desired.

**Comment by soakes** [comment]
There was an issue with the cert (escapes me right now of exactly what) but it was detected on ssllab and after fixing that, everything started working as it should including on Android N (version 7).

Go here: https://www.ssllabs.com/ssltest/index.html and stick in your fqdn of your seafile server and make sure you get your A+ rating and things should be fine after that.

**Comment by fuelflo** [comment]
mhm... thx. I already have A+ all the way. Must be sth. else....looks like I have to investigate further.

**Comment by soakes** [comment]
no worries, sorry can't be any more help but if anything comes to mind, I will drop you a quick message.
