### ISSUE TITLE
/Seafile/ is indexed by the Gallery

### ISSUE THREAD

**Issue by deathmarine** [haiwen/seadroid#588]
After reading and inspecting [StorageManager.java](https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/data/StorageManager.java) on Android Version 6.0.1, the temp folder is indexed by Gallery. I have several thousand dir-_md5hash_ images indexed. I would recommend that having at least the ability to simply use a hidden location (/.Seafile/) to store cache and temporary storage and would benefit me greatly.

**Comment by deathmarine** [comment]
Disregard the commit. I attempted to add a fix myself however the rest of the app doesn't function correctly. I assumed that considering it was a static class, this was a single point where each section of the app would retrieve the storage path.

**Comment by shoeper** [comment]
Placing .nomedia file in the cache folder would be enough afaik.

**Comment by deathmarine** [comment]
Thank you.
