### ISSUE TITLE
Should implement GET_CONTENT or OPEN_DOCUMENT

### ISSUE THREAD

**Issue by schwabe** [haiwen/seadroid#59]
I think it would be beneficial you should save/open files from other applications. This would make using the seafile client easier. Google Drive and Dropbox implement the feature as well.

**Comment by forouher** [comment]
OPEN_DOCUMENT is supported by Seadroid since version 1.4.0. However it requires Android 4.4 or newer.

**Comment by schwabe** [comment]
I see it being implemented. However for some reason it does not show in my file manager. E.g. When I try to upload a file from Google Drive (only given as example here) it shows a lot of document  providers but not seafile. Seafile Version is 1.4.2

**Comment by forouher** [comment]
Ah, yes. File writing/uploading is not implemented yet. :) Downloading should work, though (e.g. when adding mail attachments in k9mail or gmail).

I started writing on the write/upload implementation in the Storage Access Framework, but it's not finished yet. Can you point me to a (free) app, that supports file creation/modification through the SAF? At the moment I only know of OpenKeychain. Another app or two would be great for testing.

**Comment by schwabe** [comment]
Strange even in Gmail when I click on attach files it does not show Seafile. Logcat tells me:

I/ActivityManager(  996): START u0 {act=android.intent.action.CHOOSER cmp=android/com.android.internal.app.ChooserActivity (has extras)} from pid 30048
I/ActivityManager(30048): Timeline: Activity_launch_request id:com.android.documentsui time:517650014
I/ActivityManager(  996): START u0 {act=android.intent.action.GET_CONTENT cat=[android.intent.category.OPENABLE] typ=*/* flg=0x3080000 cmp=com.android.documentsui/.DocumentsActivity (has extras)} from pid 30048

**Comment by forouher** [comment]
- You're running Android 4.4/5.0?
- You have created at least one Seafile Account in Seadroid?

Other than that, maybe try rebooting your phone once. I noticed a bug that Seadroid refreshes its SAF roots not as often as it should.

**Comment by schwabe** [comment]
Yes. Sony Xperia Z1 Compact. Rebooting does not really help. If I have time later, I will look into the source code was is going wrong.

**Comment by forouher** [comment]
Very strange. This log message should pop up when accessing the SAF for the first time:

https://github.com/haiwen/seadroid/blob/master/src/com/seafile/seadroid2/provider/SeafileProvider.java#L105

**Comment by schwabe** [comment]
Okay found what was causing the bug in case. Something completely different. Although I was logged into my account and settings showed my account under account, there was no account under the accounts menu (that prompted my to add an account), after adding the account again in the account menu it now started working. 

That behaviour might be caused by upgrading from an old version or adb backup/restore or something similar (no idea).

**Comment by forouher** [comment]
Okay, that's good to hear. :)

Do you know by chance a (free) app, that makes use of either
- ACTION_OPEN_DOCUMENT 
- ACTION_OPEN_DOCUMENT_TREE
- ACTION_CREATE_DOCUMENT

There aren't many out there, which makes testing a bit difficult (and hard to motivate ;)

**Comment by freeplant** [comment]
This should have been implemented.
