### ISSUE TITLE
Uploading 2gb video

### ISSUE THREAD

**Issue by bbsmack** [haiwen/seadroid#598]
Files/videos upload fine but just down to this one 2.14GB mp4 video and Seafile instantly crashes with the 'unfortunately, seafile has stopped' message.  (I have to move this file outside of the instant camera upload directory so the crashing stops).

------------------------------------------------------
Seafile android client 2.1.6
Logs: not sure where error logs are for android client

Seafile Server Version: 5.1.3
Apache/2.4.10 (Debian)
mysql  Ver 15.1 Distrib 10.1.14-MariaDB
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64
MemTotal:  1696140 kB  MemFree: 106036 kB  MemAvailable: 802968 kB
SwapTotal:  392188 kB   SwapFree: 391692 kB
Logs: no relevant info (new log data) in the logs directory (seafile.log was the only one updated today but no events within the hour where this error happened)

**Comment by freeplant** [comment]
Fixed in version 2.2.2.
