### ISSUE TITLE
POST /api2/auth-token/ redirect is not handled as expected

### ISSUE THREAD

**Issue by beac0n** [haiwen/seadroid#606]
My server does a redirect to domain.tld/seafile/ when domain.tld is accessed:

> POST /api2/auth-token/ HTTP/1.1
> Content-Type: application/x-www-form-urlencoded; charset=UTF-8
> User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1; device Build/device)
> Host: domain.tld
> Connection: Keep-Alive
> Accept-Encoding: gzip
> Content-Length: 171
> 
> username=username&password=passwd&platform=android&device_id=serviceid&device_name=devicename&client_version=2.1.7&platform_version=5.1HTTP/1.1 301 Moved Permanently
> Date: Thu, 29 Dec 2016 09:29:15 GMT
> Content-Type: text/html
> Content-Length: 178
> Connection: keep-alive
> Location: https://domain.tld/seafile/api2/auth-token/
> Server: Apache
> 
> 301 Moved Permanently

The app then handles the redirect incorreclty, by sending a GET request instead of a POST request:

> GET /seafile/api2/auth-token/ HTTP/1.1
> Content-Type: application/x-www-form-urlencoded; charset=UTF-8
> User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1; device Build/device)
> Host: domain.tld
> Connection: Keep-Alive
> Accept-Encoding: gzip
> 
> HTTP/1.1 405 METHOD NOT ALLOWED
> Date: Thu, 29 Dec 2016 09:29:15 GMT
> Content-Type: application/json
> Transfer-Encoding: chunked
> Connection: keep-alive
> Vary: Accept-Language, Cookie
> Content-Language: en
> Allow: POST, OPTIONS
> Server: Apache
> 
> 28
> {"detail":"Method \"GET\" not allowed."}
> 0

If I change the server URL in the app to domain.tld/seafile instead of domain.tld, the app works as expected:

> POST /seafile/api2/auth-token/ HTTP/1.1
> Content-Type: application/x-www-form-urlencoded; charset=UTF-8
> User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1; device Build/device)
> Host: domain.tld
> Connection: Keep-Alive
> Accept-Encoding: gzip
> Content-Length: 171
> 
> username=username&password=passwd&platform=android&device_id=deviceid&device_name=devicename&client_version=2.1.7&platform_version=5.1HTTP/1.1 200 OK
> Date: Thu, 29 Dec 2016 09:35:47 GMT
> Content-Type: application/json
> Transfer-Encoding: chunked
> Connection: keep-alive
> Vary: Accept-Language, Cookie
> Content-Language: en
> Allow: POST, OPTIONS
> Server: Apache
> 
> 34
> {"token":"#####################"}
> 0
> 
> GET /seafile/api2/account/info/ HTTP/1.1
> Authorization: Token ########################
> User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1; device Build/device)
> Host: domain.tld
> Connection: Keep-Alive
> Accept-Encoding: gzip
> 
> HTTP/1.1 200 OK
> Date: Thu, 29 Dec 2016 09:35:47 GMT
> Content-Type: application/json
> Transfer-Encoding: chunked
> Connection: keep-alive
> Vary: Accept, Accept-Language, Cookie
> Content-Language: en
> Allow: GET, HEAD, OPTIONS
> Server: Apache
> 
> 90
> {"login_id":"","name":"username","institution":"","department":"","contact_email":"","usage":1234567,"total":-2,"email":"email@provider.tld"}
> 0

**Comment by shoeper** [comment]
Yeah, it would be better if the app wouldn't follow redirects at all.

**Comment by beac0n** [comment]
@shoeper shouldn't the login of the app be equivalent to the login in the browser? Maybe a hint, that the server sends a redirect would be sufficient?
