### ISSUE TITLE
Photo Backup Failure

### ISSUE THREAD

**Issue by rschulman** [haiwen/seadroid#618]
I just installed Seafile on my server and am now trying to backup the photos on my android phone. Seafile has recognized the photos that need uploading and placed them all in the upload list, but they are all (700 of them) listed as "Upload failed". Every once in a while the app appears to go through them and try again.

Nothing in seahub.log or in nginx access.log or error.log that seems related.

**Comment by forouher** [comment]
Hm, could you please try to manually upload some of these images via the Seafile app?

**Comment by rschulman** [comment]
Trying this has the same effect. It shows a progress bar in the upload list for a few seconds, but eventually returns to "Upload failed"

**Comment by forouher** [comment]
Hm, then this is likely not a camera upload issue and more likely a webserver config issue.
I've no real clue what the cause might be, but maybe your webserver has problems handling POST requests? Can you upload files via the Seafile Web UI?

**Comment by rschulman** [comment]
Huh, that's odd. The Seafile desktop client (mac) seems to be working fine, but no, using the web UI I also get an error: Unknown error.

**Comment by forouher** [comment]
the desktop client almost certainly uses a different API, that would explain the difference.

Maybe the issue lies with how you configured the proxy-passing to the seafhttp server?

**Comment by rschulman** [comment]
I copy/pasted from the example in the installation guide: 

```
server {
    listen 443 ssl;
    server_name <domain>;

    ssl_certificate /etc/letsencrypt/live/<domain>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<domain>/privkey.pem;
        proxy_set_header X-Forwarded-For $remote_addr;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
        server_tokens off;

        location / {
            fastcgi_pass    127.0.0.1:8000;
            fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
            fastcgi_param   PATH_INFO           $fastcgi_script_name;

            fastcgi_param   SERVER_PROTOCOL        $server_protocol;
            fastcgi_param   QUERY_STRING        $query_string;
            fastcgi_param   REQUEST_METHOD      $request_method;
            fastcgi_param   CONTENT_TYPE        $content_type;
            fastcgi_param   CONTENT_LENGTH      $content_length;
            fastcgi_param   SERVER_ADDR         $server_addr;
            fastcgi_param   SERVER_PORT         $server_port;
            fastcgi_param   SERVER_NAME         $server_name;
            fastcgi_param   REMOTE_ADDR         $remote_addr;
            fastcgi_param   HTTPS               on;
            fastcgi_param   HTTP_SCHEME         https;

            access_log      /var/log/nginx/seahub.access.log;
            error_log       /var/log/nginx/seahub.error.log;
            fastcgi_read_timeout 36000;
        }
        location /seafhttp {
            rewrite ^/seafhttp(.*)$ $1 break;
            proxy_pass http://127.0.0.1:8082;
            client_max_body_size 0;
            proxy_connect_timeout  36000s;
            proxy_read_timeout  36000s;
            proxy_send_timeout  36000s;
            send_timeout  36000s;
        }
        location /media {
            root /data/seafile/seafile-server-latest/seahub;
        }
}
```

**Comment by forouher** [comment]
Sorry, I don't know enough about nginx to comment on this. :/

Quick idea: Since uploading via webbrowser fails as well, how does the upload fail when looking at it via the dev console in your browser (usually F12). Is maybe the URL wrong? What error code are you getting?

**Comment by rschulman** [comment]
Interestingly, I'm getting a mixed secure content warning. The web page is trying to load `http://<domain>:8082/upload-aj/cb648395-c22d-4246-bab5-8feab7972448` (not https). Going to see if there's somewhere I haven't set something right...

**Comment by forouher** [comment]
Now we're getting somewhere... Double check HTTP_SERVER_ROOT in conf/seahub_settings.py

**Comment by rschulman** [comment]
seahub_settings.py is one line only: the SECRET_KEY

**Comment by rschulman** [comment]
I found the settings in the web admin interface for SERVICE_URL and FILESERVER_ROOT and corrected those, and that has solved the problem. Thank you very much for your help!
