### ISSUE TITLE
thumbnail for jpeg should auto rotate by exif

### ISSUE THREAD

**Issue by max32002** [haiwen/seadroid#635]
after download real jpg to client side, viewer auto rotate the image, but the server side does not auto rotate, or we need auto rotate in seadroid (client side).

```
_orientation_to_rotation = {
    3: 180,
    6: 90,
    8: 270
}

```

**Comment by freeplant** [comment]
The thumbnail is rotated if you using the latest server version.

**Comment by max32002** [comment]
confirmed, thank you.
