### ISSUE TITLE
Activating of contact backup does not work

### ISSUE THREAD

**Issue by S-B-V** [haiwen/seadroid#680]
Hi there,
I am using Android 7.1.1, App-Version 2.1.16, Server-Version 6.1.2 everything is on the newest possible version!
When I try to activate the contact backup under settings can I see that the switch is turning to the right and is getting green and the app is asking me for the target, after choosing and confirming the switch is grey again. It is not possible for me to activate it and it does not matter which folder I choose. I am using this function also on IOS where it is working without any issues.

Cheers

SBV

**Comment by 92lleo** [comment]
Android 7.1.1, App 2.1.16, Server 6.2.0
Same here. Activating contacts permission manually doesn't help

**Comment by Wurzelmann** [comment]
Same here.

Android 7.1.2, App  2.1.20, Server 6.1.2 (Community)

**Comment by ugjka** [comment]
same here the contacts file is not uploaded

**Comment by rekby** [comment]
same, android 8.0.0

**Comment by wsw70** [comment]
Same here, Android 8.0.0 in a Samsung S9+, app v. 2.2.1

After installing the app the contacts authorizations were not requested. I enabled them manually but the issue is the same.

**Comment by scuttlefish** [comment]
Same problem, Android 8.0.0, Samsung S8, app v 2.2.1

Storage and Contacts permissions granted manually.

**Comment by Malizor** [comment]
Same here on Lineage OS 15.1, seafile 2.2.4.

`logcat | grep seafile` gives me the following:
```
08-25 15:32:54.691  1211  6052 I ActivityManager: START u0 {cmp=com.seafile.seadroid2/.cameraupload.ContactsUploadConfigActivity (has extras)} from uid 10091
08-25 15:32:54.955  1211  1316 I ActivityManager: Displayed com.seafile.seadroid2/.cameraupload.ContactsUploadConfigActivity: +185ms
08-25 15:32:57.690  1211  9297 W ActivityManager: Duplicate finish request for ActivityRecord{5fcd8cb u0 com.seafile.seadroid2/.cameraupload.ContactsUploadConfigActivity t104 f}
```
Let me know if I can help with further debugging.

**Comment by wsw70** [comment]
Has this feature been  abandonned?

**Comment by Wurzelmann** [comment]
It seems like it, at least it's gone from the app (Android version 2.2.21)

**Comment by freeplant** [comment]
The feature is removed.
