### ISSUE TITLE
Password lost on client decryption if app is closed

### ISSUE THREAD

**Issue by dbet1** [haiwen/seadroid#689]
Since the update to 2.1.17 on Android passwords of libraries are lost on app close. In the settings I use client decryption. Yesteday I received the update, before this update I don't had this problem.
I installed an older version but the problem still exists. I have tried 2.1.16, 2.1.15, 2.1.14, 2.1.13 and 2.1.12.

**Comment by shoeper** [comment]
Afaik it is the designed behavior. Could be wrong on this, though.

**Comment by dbet1** [comment]
Before the client decryption was implemented it was normal. After an hour I had type in the password again. Since the client decryption is implemented, the passwords were saved as in the desktop seafile client. Since yesterday I lost this feature because of the update.

**Comment by sgebauer** [comment]
Same problem here. I first noticed this with client version 2.1.16, after updating my server to 6.1. I'm using random passwords for my libraries, so this behavior, intended or not, is quite annoying. It's also inconsistent with the behavior of the desktop client.

**Comment by dbet1** [comment]
It is also inconsistent with the behavior of the iOS client.
Ah, yes, I also have updated my server from 6.0 to 6.1. It is therefore a change on the server, not on the android client.

**Comment by dbet1** [comment]
The problem still exists with 2.2.1. Encrypted Libraries are almost unusable except I have the password in my mind.

**Comment by dbet1** [comment]
On my tablet I have reinstalled version 2.1.13 because of a bug with Android 7 (cannot open file to edit). With version 2.1.13 the library passwords are remembered. After I close the app and reopen it it shows the password dialog for fewer as a second and then disappears. After that I can open the library without to type in the password.
But on my device with Android 6 this "workaround" does not work. I have to type in the library password each time after I started the app.
I am not willing to type in the password again and again and again.

**Comment by dbet1** [comment]
I had an Update on my Android 7 Tablet (patch level 1. January 2018) and since then, the "password workaround" does not work again. That means that I have to retype the library passwords each time I reopened the app also with version 2.1.13.

**Comment by libeanim** [comment]
Yep I have the same error on Android 8 and seadroid 2.2.1 :/

Any updates on that? :relaxed:

**Comment by freeplant** [comment]
The fix will be included in the next version.

**Comment by dbet1** [comment]
I have tested it with version 2.2.3 where you have wrote fix password lost on client decryption if app is closed.
I cannot test it because after I give in the password for the library I receive the message FORBIDDEN. If I give a wrong password there is the message "password incorrect". But I give the right password there is always the message FORBIDDEN.
Do you have tested to connect to encrypted libraries?

**Comment by freeplant** [comment]
@dbet1 The latest is https://github.com/haiwen/seadroid/releases/tag/2.2.4 , which is the version I tested.

**Comment by dbet1** [comment]
I have tested version 2.2.1 and 2.2.4 with two devices which have two different Android versions. The test scenario was to open an encrypted library, then open a file, change something in this file and save the file. Afther that I checked that it is uploaded to the library. The same I tested with unencrypted libraries.

*** Version 2.2.1 ***

Samsung Galaxy Note 8.0 mit Android 4.4.4
- After closing the app passwords for encrypted libraries are forgotten if I use "encrypt data local".
- Download of documents, the change and upload are OK. It works with encrypted and unencrypted libraries.

Samsung Galaxy Tab S3 mit Android 8.0.0
- After closing the app passwords for encrypted libraries are forgotten if I use "encrypt data local".
- Documents were downloaded as new file, I have to save it local, then uploade to seafile. This is unusable.


*** Version 2.2.4 ***

Samsung Galaxy Note 8.0 mit Android 4.4.4
- After closing the app passwords for encrypted libraries are forgotten if I use "encrypt data local".
- Documents are downloaded, but after a change they cannot be upload. The error message is not helpful: Upload failed.
- During a second try there was an app abort during download. After that, I can't download any file in an encrypted library. I had to change to "encrypt data on the server", after that I could download the file again, but upload also failes.
- Documents in unencrypted libraries can be downloaded but also not uploaded: Upload failed.

Samsung Galaxy Tab S3 mit Andorid 8.0.0
- Passwords for encrypted libraries were not accepted at all! If I type the password correct, I receive the error FORBIDDEN, if I made a typo in the password, I receive "Wrong password", which is correct.
- Documents were downloaded as new file, I have to save it local, then uploade to seafile. Tested only with unencrypted libraries because of the error with passwords.

*** Conclusion ***
Because the Note 8.0 I don't use anymore I have still to stay with version 2.1.13. With this version the Dowload/Upload is correctly also on the Tab S3. But passwords of encrypted libraries are forgotten if I use "encrypt data local". If I use "encrypt data on server" they are forgotten after an hour or so. This is normal and by design, but if I use "encrypt data local" passwords should be saved as in the desktop version or the one for iOS.

Seafile is a wonderful piece of software, but the android app is a pain.
