### ISSUE TITLE
Share Library among users

### ISSUE THREAD

**Issue by a2t2** [haiwen/seadroid#700]
I am testing the Seafile app for Android and am looking for the feature to allow one user to share a library with another user. When I click the down arrow on a library, I only see the options rename and delete. I can share libraries between users on the Seafile web application.

I want to ask whether this feature exists in the Android open source app. I tried both the Play store version (v 2.1.18) and the F-droid version (v 2.1.17) and I don't see this feature.

Thanks.

**Comment by freeplant** [comment]
sharing settings can only be done via web interface currently.
