### ISSUE TITLE
Enabling camera upload option crashes Android App  

### ISSUE THREAD

**Issue by mbelgin** [haiwen/seadroid#701]
Enabling camera upload option (on a fresh installation on the phone) immediately crashes the app. I use server 6.2.2 on Raspbian. I have used this option for more than a year without problems, but started seeing this issue after making these changes:

* Upgraded to server  6.2.2
* Enabled Apache
* Clean installation using a subdirectory of my domain
* Added self-signed SSL   

Everything else (desktop clients, browser interface) is working flawlessly, this only happens with the android app!

I'll be happy to provide more details. I've already filed a crash report directly from Android with system logs etc.

Thanks.

**Comment by freeplant** [comment]
Can you paste the crash report here?

**Comment by mbelgin** [comment]
I would love to, but I don't know how to access/export log files from my android phone. When SeaFile client crashes, it says "Seafile has stopped" and gives me an option to Send feedback, which is what I did. Are those logs stored somewhere on my phone that I can reach?

**Comment by nianxy** [comment]
I have the same problem, so I have to use `2.1.17` instead.
My phone is *Huawei Honor 8 (FRD-AL10)*

**Comment by metinc** [comment]
@freeplant here is the logcat output when activating camera upload:
[camera upload crash.txt](https://github.com/haiwen/seadroid/files/1432428/camera.upload.crash.txt)

**Comment by SaudM** [comment]
https://github.com/haiwen/seadroid/issues/702#event-1326818983

**Comment by mbelgin** [comment]
After the last update, it works again! Thanks!!
