### ISSUE TITLE
Add -> Upload file -> Other -> nothing happens ?

### ISSUE THREAD

**Issue by ghost** [haiwen/seadroid#703]
Hi,

trying to upload a file with Seafile Android (v2.1.18 installed via PlayStore) via Add -> Upload file -> Other -> (File) there is no reaction: no file upload indicator and no file uploaded on my server (CE 6.2.2 for RPi).

The Android version is 4.2.2. Any suggestions how to solve this problem?

Thank you!
sj7

**Comment by otherpaco** [comment]
Hello try to deintsall your Seafile on Android, get version 2.1.13 from this git here.

https://github.com/haiwen/seadroid/releases/tag/2.1.13

Install that .apk and try again.

When this helps your bug might be related to #691

**Comment by saljut7** [comment]
Upload under `2.1.13` works now, thx!
