### ISSUE TITLE
App crashes in Android Oreo (8.0.0)

### ISSUE THREAD

**Issue by arjones85** [haiwen/seadroid#706]
Nexus 6p, Android 8.0.0.

Attempting to start the app fails with an instant crash.  Unable to proceed any further than that.

**Comment by mhermstein** [comment]
Similar for me with Android 7.1.1 Resurrection Remix 5.8.0
I just get to the point where I should enter my server and password. After that the app crashes and so for every attempt to restart it.

**Comment by SaudM** [comment]
fix crash  in  seafile 2.2.0
