### ISSUE TITLE
wrong app launched

### ISSUE THREAD

**Issue by Silvernerd1** [haiwen/seadroid#709]
Hi Seadroid-Community,

I use Seafile app 2.1.20 on my OnePlus 3T with Android 7.1.1. Keepass2Android app is installed to open KDBX-files and Planmaker for XLSM-files. When I reset all file associations in both apps apps and open a KDBX-file with Seafile for the first time, I am prompted, which app I want to use. I select Keepass2Android und use option 'always'. Everything fine up to here.
My issue: When I try to open a XLSM-File (Excel with macros), Keepass2Android is opened, too. I am not prompted, which app I want to use. When I first open an XLSM-file after clearing the file associations, vice cersa both file types are opened with Planmaker. The issue seems to be, that both filetypes are always opened with the same app.
To doublecheck, whether it is a Seafile or an Android issue, I copied the same files to the documents-folder and opened them with ES-file-explorer: Reliably, KDBX-file is opened with Keepass2Android and XLSM-file is opened with Planmaker.
Can anyone help?
Thanks in advance.
--
Bfn
Michael

**Comment by shoeper** [comment]
Looks like the document type is not being properly determined.
