### ISSUE TITLE
When I clicked on settings, APP crash

### ISSUE THREAD

**Issue by mstbetter** [haiwen/seadroid#710]
When I clicked on settings, APP burst,
and logcat: Attempt to invoke virtual method 'void android.preference.Preference.setSummary(java.lang.CharSequence)' on a null object reference
 at com.seafile.seadroid2.ui.fragment.SettingsFragment.onViewCreated(SettingsFragment.java:148)

**Comment by freeplant** [comment]
Do you still have the problem with version 2.2.0?

**Comment by jodason** [comment]
Hi,
I have the same problem. I can go to settings but it is loading very long and it seems to be unresponsive. A few seconds later the page is loaded. But if i klick on any Option the App crashes completly.

Seafile Server Version 6.2.3
Seafile App Version 2.2.0
Device Sony Xperia Z3 D6603
Android Version 6.0.1
Kernel Version 3.4.0-perf-gc14c2d5
Build Number 23.5.A.1.291

**Comment by mstbetter** [comment]
@freeplant  my version is too old
