### ISSUE TITLE
小米手机无法自动同步，但手动上传正常，其他机型正常

### ISSUE THREAD

**Issue by icyomik** [haiwen/seadroid#711]
嗨，我使用小米Note安装Seafile 2.1.20版本时，设置了相册自动同步但并没有生效（手动上传文件正常）。
换了另外的红米Note 3也遇到了一样的问题，但使用魅蓝Note（同样版本）和iPhone 6（2.6.10）却正常。
服务端版本是6.2.3，系统CentOS 7.0的，请问下是否小米机型需要设置什么呢？谢谢~

**Comment by freeplant** [comment]
试试在系统的 “设置” -> “账号” -> “其他账号” -> “Seafile” 勾选同步。
