### ISSUE TITLE
Password encrypted starred files are accessible from stock android file manager

### ISSUE THREAD

**Issue by laserstrike** [haiwen/seadroid#712]
Is this intentional? 

Because in the seafile app, selecting a password encrypted file from the starred label requires the password. 

But if you go to it through the seafile account built in to the stock file manager, it can be opened. 

To recreate, just star any file from password encrypted folder, then
go to Settings>Storage>Internal Shared Storage>(scroll to bottom) Explore> 
(Open left drawer) Select seafile account>Select Starred> Select the file from Starred

In my case, my (password) encrypted starred pdf file was opened. 

I kind of thought it would force close because if you follow the steps above and select the folder that it's in with the key on it it causes a force close...

May be similar to https://github.com/haiwen/seadroid/issues/552 but in this case the starred file is accessible through the stock file manager instead of (opening the intent) through the seafile app.

**Comment by shoeper** [comment]
It is intentional. Files are only being saved encrypted on the server.

The password in the app is to check for a newer version.

**Comment by laserstrike** [comment]
Ah, ok. Will close the issue then. Thank you.
