### ISSUE TITLE
The app crashes when I try to open context menu for a file on Android 8.0.0

### ISSUE THREAD

**Issue by thetraumer** [haiwen/seadroid#713]
First of all, thanks a lot for the great app. Have been really enjoying it since I installed it and I really appreciate your effort.
Issue details:
Device: Nexus 5X. Android 8.0.0. Security patch level: November 5, 2017. App version: 2.1.20
It seems that the issue occurred after the latest security patch, although I am not sure. Doesn't matter if I choose a folder, or a file of any type, the app instantly crashes as soon as I press on the right side of the item's name. Crash system log screenshot is below.
![crashscreenshot](https://user-images.githubusercontent.com/1180365/33039278-b1ce56d0-ce37-11e7-893c-5eb743a4a85c.jpg)

**Comment by berserkwarwolf** [comment]
To illustrate what he's saying, here's how to reproduce it:

[1) Tap on a file or folder's context menu](https://imgur.com/f0XUyVN)

[2) Crash happens](https://imgur.com/rVTNOOL)

This bug is at least a month old, any comments on the priority to fix it ?

**Comment by berserkwarwolf** [comment]
It keeps crashing for me after the update. I've already sent the crash log.

**Comment by Huxly72** [comment]
Still happening for me as well after updating. Log sent

**Comment by thetraumer** [comment]
The fix was introduced after the release 2.2.0, so we will have to wait until the next one
