### ISSUE TITLE
Large file uploads fail

### ISSUE THREAD

**Issue by spfannemueller** [haiwen/seadroid#721]
Upload of (video)files > 1.5 GB via autoupload always fail to upload and then restart. 

Referring to this thread: https://forum.seafile.com/t/seafile-android-client-large-file-uploads-fail/5029

Seafile-Server Version: 6.2.3 - on Debian 9.3
Seafile Android Version: 2.2.1 - on Android 8.0.0

**Comment by Cisco30** [comment]
I have the same problem, android 7.0., seafile server pro 6.2.4,  Debian 9.3 ,  seafile android 2.2.1

**Comment by freeplant** [comment]
How much time does it take to upload the file?

**Comment by spfannemueller** [comment]
Upload fails after about 60 seconds. My Seafile Server is located in my LAN and I'm uploading with about 350 Mbit/s.

**Comment by freeplant** [comment]
Do you have any error log in the server side (Nginx log or seafile.log)?

**Comment by spfannemueller** [comment]
Neither the nginx nor the seafile.log show any errors. If I upload the same file trough Seahub or the Seafile Client it works great.

**Comment by Cisco30** [comment]
The upload all the files is canceled by the android app after a few minutes. I made a screen shot. 
![screenshot_20180109-113158](https://user-images.githubusercontent.com/29772453/34716898-89ed2a62-f531-11e7-8244-275b421622d9.png)
![screenshot_20180109-113250](https://user-images.githubusercontent.com/29772453/34716903-8a7fe49c-f531-11e7-8836-297dc1b6544c.png)

**Comment by mstbetter** [comment]
Upload of (video)big files   autoupload always fail to upload ,Progress bar shows about 10%,and then restart .

**Comment by mstbetter** [comment]
cause by: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

Seafile Android Version: 2.2.0 - on Android 6.0.1

**Comment by shoeper** [comment]
Out of memory somehow indicates that uploading does use as much memory as the size of the file. Looks like some kind of buffering is required.

**Comment by freeplant** [comment]
Fixed in https://github.com/haiwen/seadroid/pull/728
