### ISSUE TITLE
App crashes when clicking on "server address" field in "Log In" view in 2.2.1 on android 8

### ISSUE THREAD

**Issue by 92lleo** [haiwen/seadroid#723]
Phone: HTC U11, Android 8.0.0, Appversion 2.2.1-2.2.3

When setting up the app the first time and adding a custom seafile server the app crashen when the "server address" textedit is clicked (and another part of the view had focus before).

Steps to reproduce:
Add account > other seafile server > click the server address field

Workaround: 
Enter server address before giving another view component focus

For Logcat see #736

**Comment by 92lleo** [comment]
Seems to be fixed in [2.1.13](https://github.com/haiwen/seadroid/releases/tag/2.1.13)

**Comment by 92lleo** [comment]
Thought the release in github was the latest, my bad. It still worked in 2.1.13, but doesn't work in 2.2.1, easy to reproduce

**Comment by mpern** [comment]
Same problem here, and I think #736 is also the same issue.
Unfortunately, this makes the app unusable 😞
