### ISSUE TITLE
[feature request] add an option to delay auto upload 

### ISSUE THREAD

**Issue by vin-c** [haiwen/seadroid#727]
Hi,

It's really nice to have an automatic upload of pictures and videos.

But sometimes the shot is not perfect...

It would be great to have a delay option in order to be able to sort the pics (or delete them...) before they are sent.

Also a button or entry menu to force the sync with some display about the result. 

Another approach would be to set a planning of syncs like a crontab. 

Hope you understand what I mean.

**Comment by freeplant** [comment]
We don't have a plan to add such feature.
