### ISSUE TITLE
File modified time is not preserved after upload

### ISSUE THREAD

**Issue by janulis** [haiwen/seadroid#729]
Dear Seadroid Maintainers,

I am a new user of Seafile and very happy so far.

The only issue I noticed that file modified timestamp is not preserved after picture upload. Is this a known issue and planned to be fixed?

Note that the desktop Seafile clients are setting the modified file timestamp correctly from the original to the uploaded file. The issue is only present in the Android app and this prevents me from using it.

Many thanks for creating great and open software!

**Comment by freeplant** [comment]
This is a known issue. Only files uploaded via file syncing from desktop is modified time preserved.
