### ISSUE TITLE
Camera upload with quota hit = infinite retry

### ISSUE THREAD

**Issue by foxel** [haiwen/seadroid#733]
A couple of days ago I've hit a quota limit on my Seafile CE instance and it leads to unexpected behavior of the Android application: 
* once file ends uploading it retries twice and then shows an error in uploads list
* after some time (in background) upload starts again.
* no error is shown for background uploads faile
* no statement about quota hit is shown anywhere

I was able to identify the problem by examining battery and traffic usage on the phone, once noticed significant battery life issues.

Screenshots below:

![image](https://user-images.githubusercontent.com/1551926/38592310-8c187cfc-3d65-11e8-9591-39a4980bc956.png)

**Comment by SaudM** [comment]
We have uploaded version 2.2.4 to GitHub，fix file upload failed
