### ISSUE TITLE
Can't upload manually most of the time when in energy saving mode

### ISSUE THREAD

**Issue by Crafter6432** [haiwen/seadroid#735]
Hi,

For the past 2 months I had issues uploading files(images,pdf) manually through seafile and the share option in other apps. When attempting to upload through Seafile I usually get "No network connection" which is certainly not the case because I can refresh my library list or folders just fine, when I attempt to upload through another app e.g. Google Drive PDF(share->print->as pdf) and selcect seafile as target my library's will be listed but I get a notification(could not connect to server. Dismiss?). I replicated this problem with my own(open source) and my uni's server(pro version). I also checked my webservers logs and there are no attempted http requests to upload said files. Sometimes however the apps logs an error:

``
04-23 22:13:21.339  7681 11204 E SeafileProvider: Exception while querying repos
04-23 22:13:21.339  7681 11204 E SeafileProvider: SeafException{code=2, msg=Network Error}
04-23 22:13:21.339  7681 11204 E SeafileProvider: 	at com.seafile.seadroid2.data.DataManager.getReposFromServer(DataManager.java:346)
04-23 22:13:21.339  7681 11204 E SeafileProvider: 	at com.seafile.seadroid2.provider.SeafileProvider$11.run(SeafileProvider.java:911)
04-23 22:13:21.339  7681 11204 E SeafileProvider: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
04-23 22:13:21.339  7681 11204 E SeafileProvider: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-23 22:13:21.339  7681 11204 E SeafileProvider: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-23 22:13:21.339  7681 11204 E SeafileProvider: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-23 22:13:21.339  7681 11204 E SeafileProvider: 	at java.lang.Thread.run(Thread.java:764)
``

Edit: Most of the time means there is a 10% chance that you won't get the network error

Seadroid version: 2.2.1
Android: 8.0

My Server:
Seafile community ed. 6.2.5
Nginx + https://hub.docker.com/r/jenserat/seafile/
Nginx is setup TLS only with SNI and Let's Encrypt certificates

**Comment by shoeper** [comment]
Why has this been closed?

**Comment by freeplant** [comment]
I thought it was caused by energy saving mode instead of a bug of the Android client.

**Comment by Crafter6432** [comment]
Disabling the engery saving mode only fixes the problem partially, because
the energy saving mode disables background data but that shouldn't be an
issue when the app is in the foreground anyway.

**Comment by RoestVrijStaal** [comment]
Bump

A whole month has been passed and I still can't upload anything. Turning off Energy Saving doesn't help :angry:

**Comment by RoestVrijStaal** [comment]
Ok, because @freeplant changed the goal of this issue, my previous comment is more targeted at #730

**Comment by SaudM** [comment]
> 伙计这真的很重要，必须修复。当手动上传文件时，应用程序处于前台（失败：“网络错误”），同时启用了相机图片的同步，如果在Android上启用了能源模式，则应用程序无法上传或同步（在Galaxy S6上测试） ，Android 7.0）。
> 
> 请找到解决方案。

* I have tested the problem. This seems to be a bug of `Galaxy S6` system. When your phone is in energy saving mode, the "background network usage" of the phone will be closed. In the case, when you open the Seafile client, Seafile client from the phone system getting the network status is false, so the Seafile client does not work and displays "Network Error"
* If you set sync of Camera pictures is enabled, you must also open "Sync" in the phone settings, and make sure the phone has a network, so the sync will work
