### ISSUE TITLE
Camera upload is not working anymore

### ISSUE THREAD

**Issue by Wurzelmann** [haiwen/seadroid#750]
Camera upload hasn't been working for two weeks now, for no apparent reason at all. I tried clearing the app's cache and forcibly restarting it, all to no avail. 

Server: Pro 6.2.13
Android: 8.1.0
App version: 2.2.1

**Comment by sappo** [comment]
Same problem here:

Server: Community 6.2.5
Android: 8.1.0
App version: 2.2.4

**Comment by fakuivan** [comment]
Same

Server: Community 6.3.2
Android: 7.0
App version: 2.2.4

**Comment by john-bill** [comment]
Same here, tried with several Client and Community-Server Releases.
App Version 2.2.1 is the last one with working picture upload (or better to say: working upload in general!)

**Comment by Wurzelmann** [comment]
Updated the Android app as well (to 2.2.4) and it still does not work.

**Comment by TT-SWP13** [comment]
Same here.

App-Version: 2.2.4
Server-Version: CE 6.2.5 & CE 6.3.2
Android-Version: 6.0.1

**Comment by reneraab** [comment]
I have the same problem that camera upload and manual upload are not working any more. Downloads are not working either.

App version: 2.2.4
Server-Version: Community Edition 6.3.2
Android Version 8.0.0

Using adb logcat, I got this error:

```
08-12 22:28:27.293 16354 12760 W System.err: java.net.SocketException: Broken pipe
08-12 22:28:27.293 16354 12760 W System.err: 	at java.net.SocketOutputStream.socketWrite0(Native Method)
08-12 22:28:27.293 16354 12760 W System.err: 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
08-12 22:28:27.294 16354 12760 W System.err: 	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
08-12 22:28:27.294 16354 12760 W System.err: 	at okio.Okio$1.write(Okio.java:79)
08-12 22:28:27.294 16354 12760 W System.err: 	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
08-12 22:28:27.294 16354 12760 W System.err: 	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
08-12 22:28:27.294 16354 12760 W System.err: 	at okio.RealBufferedSink.write(RealBufferedSink.java:41)
08-12 22:28:27.294 16354 12760 W System.err: 	at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:292)
08-12 22:28:27.294 16354 12760 W System.err: 	at okio.ForwardingSink.write(ForwardingSink.java:35)
08-12 22:28:27.294 16354 12760 W System.err: 	at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:134)
08-12 22:28:27.294 16354 12760 W System.err: 	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
08-12 22:28:27.294 16354 12760 W System.err: 	at okio.RealBufferedSink.write(RealBufferedSink.java:41)
08-12 22:28:27.294 16354 12760 W System.err: 	at com.seafile.seadroid2.httputils.RequestManager$1.writeTo(RequestManager.java:108)
08-12 22:28:27.294 16354 12760 W System.err: 	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
08-12 22:28:27.294 16354 12760 W System.err: 	at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
08-12 22:28:27.294 16354 12760 W System.err: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
08-12 22:28:27.294 16354 12760 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-12 22:28:27.294 16354 12760 W System.err: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
08-12 22:28:27.294 16354 12760 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-12 22:28:27.294 16354 12760 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-12 22:28:27.294 16354 12760 W System.err: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
08-12 22:28:27.294 16354 12760 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-12 22:28:27.295 16354 12760 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-12 22:28:27.295 16354 12760 W System.err: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
08-12 22:28:27.295 16354 12760 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-12 22:28:27.295 16354 12760 W System.err: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
08-12 22:28:27.295 16354 12760 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-12 22:28:27.295 16354 12760 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-12 22:28:27.295 16354 12760 W System.err: 	at com.seafile.seadroid2.httputils.RequestManager$LoggingInterceptor.intercept(RequestManager.java:65)
08-12 22:28:27.295 16354 12760 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-12 22:28:27.295 16354 12760 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-12 22:28:27.295 16354 12760 W System.err: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
08-12 22:28:27.295 16354 12760 W System.err: 	at okhttp3.RealCall.execute(RealCall.java:77)
08-12 22:28:27.295 16354 12760 W System.err: 	at com.seafile.seadroid2.SeafConnection.uploadFileCommon(SeafConnection.java:904)
08-12 22:28:27.296 16354 12760 W System.err: 	at com.seafile.seadroid2.SeafConnection.uploadFile(SeafConnection.java:874)
08-12 22:28:27.296 16354 12760 W System.err: 	at com.seafile.seadroid2.data.DataManager.uploadFileCommon(DataManager.java:686)
08-12 22:28:27.296 16354 12760 W System.err: 	at com.seafile.seadroid2.data.DataManager.uploadFile(DataManager.java:680)
08-12 22:28:27.296 16354 12760 W System.err: 	at com.seafile.seadroid2.transfer.UploadTask.doInBackground(UploadTask.java:89)
08-12 22:28:27.296 16354 12760 W System.err: 	at com.seafile.seadroid2.transfer.UploadTask.doInBackground(UploadTask.java:18)
08-12 22:28:27.296 16354 12760 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-12 22:28:27.296 16354 12760 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-12 22:28:27.296 16354 12760 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-12 22:28:27.296 16354 12760 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-12 22:28:27.296 16354 12760 W System.err: 	at java.lang.Thread.run(Thread.java:764)
```

A similar problem occurs when manually uploading a file.
```
08-12 22:35:53.055 16354 12762 I LoggingInterceptor: 
08-12 22:35:53.055 16354 12762 E UploadTask: Upload exception 599 File upload failed
08-12 22:35:53.056 16354 12762 W System.err: SeafException{code=599, msg=File upload failed}
08-12 22:35:53.056 16354 12762 W System.err: 	at com.seafile.seadroid2.SeafConnection.uploadFileCommon(SeafConnection.java:911)
08-12 22:35:53.056 16354 12762 W System.err: 	at com.seafile.seadroid2.SeafConnection.uploadFile(SeafConnection.java:874)
08-12 22:35:53.056 16354 12762 W System.err: 	at com.seafile.seadroid2.data.DataManager.uploadFileCommon(DataManager.java:686)
08-12 22:35:53.056 16354 12762 W System.err: 	at com.seafile.seadroid2.data.DataManager.uploadFile(DataManager.java:680)
08-12 22:35:53.056 16354 12762 W System.err: 	at com.seafile.seadroid2.transfer.UploadTask.doInBackground(UploadTask.java:89)
08-12 22:35:53.056 16354 12762 W System.err: 	at com.seafile.seadroid2.transfer.UploadTask.doInBackground(UploadTask.java:18)
08-12 22:35:53.056 16354 12762 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-12 22:35:53.056 16354 12762 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-12 22:35:53.056 16354 12762 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-12 22:35:53.056 16354 12762 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-12 22:35:53.056 16354 12762 W System.err: 	at java.lang.Thread.run(Thread.java:764)
```

Error when downloading
```
08-12 22:37:43.854 16354 12756 D SeafConnection: HTTP request failed : [URL redacted], 302, Found
```

**Comment by fakuivan** [comment]
That does not apply on my case, as the URL was set to the correct protocol. 
![image](https://user-images.githubusercontent.com/15100012/44006997-00eb14cc-9e64-11e8-92a0-c62861b96158.png)

Does anyone that commented this issue also uses an internally signed TLS certificate instead of the ones provided by Let'sEncrypt?

**Comment by sappo** [comment]
My FILE_SERVER_ROOT is also correctly set to https and I'm using a self
singed TLS certificate.

fakuivan <notifications@github.com> schrieb am Mo., 13. Aug. 2018, 00:17:

**Comment by fakuivan** [comment]
Maybe that has something to do with it since I reinstalled the app and it didn't asked me to confirm the untrusted certificate (it is trusted but the CA is installed on the user store, which seafile doesn't trust on my Android version)

**Comment by john-bill** [comment]
my FILE_SERVER_ROOT is set correctly to https, but still using self signed certificate.

**Comment by fakuivan** [comment]
I can confirm this issue has something to do with user installed root certificates. I spawned another virtual server on nginx as a proxy for the server, with a letsencrypt cert and this bug disappeared.

**Comment by sappo** [comment]
I can confirm as well that using a letsencrypt certificate solves this issue

**Comment by TT-SWP13** [comment]
I am using a LetsEncrypt certificate on my server and can't upload pictures with the automatic upload function in Android Seafile App version 2.2.4. 
Same with version 2.2.1.
Before i updated Seafile / or the App it has worked.

**Comment by fakuivan** [comment]
@TT-SWP13 Have you tried doing [what @reneraab suggested](https://github.com/haiwen/seadroid/issues/750#issuecomment-412372642)

**Comment by TT-SWP13** [comment]
@fakuivan Yes i have https in my configurations.

**Comment by BenoitGEORGELIN** [comment]
Same problem here.  
App version 2.2.5 still not working. 
It stopped working since 2.2.2 I guess 
So I went back to 2.2.1 ( https://github.com/haiwen/seadroid/releases/download/2.2.1/seafile-2.2.1.apk )
uninstall 2.2.5
install 2.2.1 

It work again , can't explain why

**Comment by tecstuff** [comment]
confirmed. Uploads not working for Android client versions beyond 2.2.1

seafile-server-6.3.2
seafile-client android 2.2.2 - 2.2.5
Android 8.1.0

Fallback to 2.2.1.apk solves the problem.

**Comment by TT-SWP13** [comment]
I tested it again with version 2.2.1 on an old LG G3 and now it works. 
But on my primary phone (Xiaomi Redmi 3s) it doesnt work.
(All Battery-Safe options are disabled, also autostart is enabled and all permissions are right for the app)
But also version 2.2.5 works on LG G3 for me.

**Comment by ktdd** [comment]
Same here. I have a LetsEncrypt certificate and my phone hasn't uploaded any new pictures since May.

Moto G5 Plus, Android 7.1. apk version 2.2.4. Gonna try 2.2.5 now

**Comment by BenoitGEORGELIN** [comment]
I installed 2.2.6 , and it works fine . 
Thanks !

**Comment by Wurzelmann** [comment]
I just installed 2.2.6 but it is still not working... :-/ Did you change anything, @BenoitGEORGELIN?

**Comment by BenoitGEORGELIN** [comment]
Nope, I but i'm pretty sure this release fixed it . 
In the release , they mentioned a fix regarding SSL .  But I don't see any error reported to the user if any error . 
What kind of Certificates do you use on your server @Wurzelmann ?

**Comment by Wurzelmann** [comment]
I am using Let's Encrypt certificates. Yesterday I cleared the app's cache, uninstalled it and added my accounts again, but it still does not upload pictures automatically. :-(

**Comment by sappo** [comment]
Upload with let's encrypt certificat did work without yesterday's app
update. So you must have configured something else wrong.

Christoph <notifications@github.com> schrieb am So., 26. Aug. 2018, 07:07:

**Comment by sappo** [comment]
This issue is about uploads failing with a self-singed certificate and
switching to an valid certificate e.g. Let's Encrypt solved the issue. Also
with 2.2.6 self-signed certificates are working again. So whatever problem
or bug you running into it is probably not related to this issue. As this
thread is already rather long I recommend that you open another issue and
describe your problem there as it is not exactly the one this issue has
been opened for. No offense.

Christoph <notifications@github.com> schrieb am So., 26. Aug. 2018, 08:22:

**Comment by Wurzelmann** [comment]
Okay, without notifying me, the app started uploading pictures again. All is good again, thanks everybody.

**Comment by TT-SWP13** [comment]
With Server-Version 6.3.4 (and App-Version 2.2.8) now it works for me on my phone (Xiaomi Redmi 3s).
