### ISSUE TITLE
<master> crashed by NullPointerException

### ISSUE THREAD

**Issue by MelanDawn** [haiwen/seadroid#751]
The app crashed when I downloaded a file. 
I findthat the filed 'txService' is judged whether it is null at other area.
 And the log is below at here.

08-02 10:23:47.995 D/AndroidRuntime(10380): Shutting down VM
08-02 10:23:48.000 E/AndroidRuntime(10380): FATAL EXCEPTION: main
08-02 10:23:48.000 E/AndroidRuntime(10380): Process: com.seafile.seadroid2.debug, PID: 10380
08-02 10:23:48.000 E/AndroidRuntime(10380): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.seafile.seadroid2.transfer.TransferService.addDownloadTask(com.seafile.seadroid2.account.Account, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at com.seafile.seadroid2.ui.activity.BrowserActivity.downloadFile(BrowserActivity.java:1562)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at com.seafile.seadroid2.ui.fragment.ReposFragment$4.onClick(ReposFragment.java:235)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at com.cocosw.bottomsheet.BottomSheet$4.onItemClick(BottomSheet.java:330)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1263)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3380)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at android.widget.AbsListView$3.run(AbsListView.java:4343)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at android.os.Handler.handleCallback(Handler.java:815)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at android.os.Handler.dispatchMessage(Handler.java:104)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at android.os.Looper.loop(Looper.java:194)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at android.app.ActivityThread.main(ActivityThread.java:5877)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at java.lang.reflect.Method.invoke(Native Method)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at java.lang.reflect.Method.invoke(Method.java:372)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
08-02 10:23:48.000 E/AndroidRuntime(10380): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
08-02 10:23:48.000 I/am_crash(  783): [10380,0,com.seafile.seadroid2.debug,13156166,java.lang.NullPointerException,Attempt to invoke virtual method 'int com.seafile.seadroid2.transfer.TransferService.addDownloadTask(com.seafile.seadroid2.account.Account, java.lang.String, java.lang.String, java.lang.String)' on a null object reference,BrowserActivity.java,1562]

**Comment by haidian6672** [comment]
之前在其它地方遇到过 app crashed 的问题，通过重写默认 UncaughtExceptionHandler 解决了。
        Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
            @Override
            public void uncaughtException(Thread t, Throwable e) {
                Log.d(TAG, "uncaughtException from "+t.getName());
                e.printStackTrace();
            }
        });

**Comment by MelanDawn** [comment]
这里应该做判空处理。同一个类中，其他地方有判空处理，异常位置没有。
