### ISSUE TITLE
Files copied to the library location are not synchronized

### ISSUE THREAD

**Issue by wsw70** [haiwen/seadroid#767]
I tried to copy a file to a subfolder of an existing library (`/Seafile/<account name>/<library name>/target_subfolder`) and is was not synchronized with my server.

This is also the case when the folder is "downloaded" (marked and then downloaded).

Is there a way to have a folder monitored for synchronization?

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
