### ISSUE TITLE
Photo album backup says upload complete, but no files are actually uploaded

### ISSUE THREAD

**Issue by borie88** [haiwen/seadroid#773]
After turning on the photo backup option, selecting a cloud directory, and selecting a camera folder, uploads begin to appear in the app. Once the app says all uploads are finished, I check the web client and see that while sub-directories were created, no files were actually uploaded and the folder size is 0 bytes. Any fixes?

App: 2.2.8
Server: 6.3.x
Phone: Oppo R17, Android 8

**Comment by borie88** [comment]
Downgraded to 2.2.8 and everything works fine... So something broke over the past few updates... Hope that helps

**Comment by freeplant** [comment]
The issue should have been fixed in the latest release.
