### ISSUE TITLE
Latest update gives battery warning from android

### ISSUE THREAD

**Issue by andi-blafasl** [haiwen/seadroid#776]
After the last update of seafile app from 5.1.2019 I get a warning from Android battery management. Other users in play store reporting same error.
![screenshot_20190106-110406 2](https://user-images.githubusercontent.com/3586675/50734695-10c1f980-11a3-11e9-85fa-617188b77a04.png)

**Comment by shoeper** [comment]
Looks like the app is running all the time. But looking at the actual usage it is still almost none.

**Comment by shoeper** [comment]
At least on my phone the warning is there as well but the battery manager says Seafile 0 mAh

**Comment by andi-blafasl** [comment]
Same experience here. It's not a serious problem but the message is annoying anyways :-)
![screenshot_20190106-150351](https://user-images.githubusercontent.com/3586675/50736997-9013f500-11c4-11e9-8ad8-bd333693644c.png)

**Comment by dkrenn** [comment]
I had a significant drop of time until recharging lately (roughly 8-10% of total energy is spent on Seafile without actively using it; sync of photos however is on in background).
I blamed the my server saying "no space left" for this, as it seems to be better after freeing space (but this is only speculation; and the message is still appearing).

**Comment by gitfineon** [comment]
![screenshot_20190109-215944 2](https://user-images.githubusercontent.com/11716650/50928244-7986cb80-145a-11e9-87da-ff2b03a1f054.png)
On my Nexus with Android 7.1.1 the new Seafile version 2.2.11 also delivers a message, which is always there. It does not mention the battery and on tab showing up the "App info".
There are no libraries with synchronization enabled, but browsing works fine.

Btw: If removing permission to access phones storage, the app crashes if you try to open Settings

**Comment by shoeper** [comment]
My father and sister also reported the issue. Looks like occurs consistently across all devices.

**Comment by dreua** [comment]
Same here on Android Nougat 7.1.1

This is tagged for Android 8 but might still be related: https://stackoverflow.com/questions/46335274/android-oreo-persistent-notification-app-is-running-in-the-background#

**Comment by 92lleo** [comment]
Looks like this is fixed in https://github.com/haiwen/seadroid/releases/tag/2.2.12

**Comment by dreua** [comment]
@92lleo Thank you, that's good news. Now the only problem is that the latest version is 2.2.11, seems like they forgot to push the 12 to google play, doesn't it?

**Comment by dreua** [comment]
The 2.2.12 update is now in Google Play and works for me.

**Comment by gitfineon** [comment]
Version 2.2.12 not yet available in F-Droid Store :disappointed:

**Comment by shoeper** [comment]
It has been released there as well in the meantime.
