### ISSUE TITLE
How to use a file locally ? 

### ISSUE THREAD

**Issue by kforner** [haiwen/seadroid#779]
Hello,

I could not figure out how to use a file locally.
My use case: I have a keepass db file stored on seafile.
I'd like to open this file in keepass on my android device. 
Apparently seadroid does not know how to open the file.
So I wanted to put the file somewhere on the filesystem, so that I could load it from keepass.
But I did not find a way to do that. 
What did I miss ? 

Thanks

**Comment by sebw** [comment]
Downloaded files appear on my phone under `/storage/BBD9-1EFE/Android/media/com.seafile.seadroid2/account@example.com (description)/library/file.pdf`

**Comment by kforner** [comment]
thanks.
