### ISSUE TITLE
Google Single Sign-On doesn't work

### ISSUE THREAD

**Issue by MateEke** [haiwen/seadroid#783]
If I try to add a new Single Sign-On account with Google auth I get this error: 403 disallowed_useragent.
In all browsers SSO works fine.
The "learn more" link takes mi to this page: [Modernizing OAuth interactions in Native Apps for Better Usability and Security](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html).

Could you please make it possible to use Google Auth as an SSO option in the app?

![image](https://user-images.githubusercontent.com/11072174/51975580-e18d6800-2482-11e9-8b99-a6bed833295a.png)

**Comment by shoeper** [comment]
https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

OAuth with is not allowed with an embedded browser.
