### ISSUE TITLE
IV should be randomness and unpredictable

### ISSUE THREAD

**Issue by wwwwwwill** [haiwen/seadroid#789]
When using client-side encryption, for one encrypted library, the IV is stored and the client program always uses this one IV to encrypt and decrypt different files. IV reused is unsafe and should not be used, the IV should be randomness and unpredictable. (CWE-329: https://cwe.mitre.org/data/definitions/329.html)

These are Debug details for three different files when decrypting them in the client (Android) side:
File1: Cipher@7029
<img width="1438" alt="2019-02-18 12 45 04" src="https://user-images.githubusercontent.com/45511549/52952925-f8d2bd80-337d-11e9-8fce-aa4881b1e5f3.png">
File2: Cipher@7074
<img width="1438" alt="2019-02-18 12 46 06" src="https://user-images.githubusercontent.com/45511549/52952944-0425e900-337e-11e9-9789-d5867ec82fd2.png">
File3: Cipher@7097
<img width="1438" alt="2019-02-18 12 47 07" src="https://user-images.githubusercontent.com/45511549/52952950-07b97000-337e-11e9-9325-938626424981.png">

**Comment by freeplant** [comment]
After releasing version 7.0, we will use different IV for different libraries. But for a single library, the same IV will be used for different libraries as it requires too much effort to use different IV for every file.

As a single library can only be accessed by shared and trusted users, it should be safe enough.
