### ISSUE TITLE
Could be config 'FILE_SERVER_ROOT' by myself?

### ISSUE THREAD

**Issue by shawn2013** [haiwen/seadroid#805]
I installed seafile server at home, and set FILE_SERVER_ROOT=http://192.168.x.x:8082 within server, and if i want to access from internet, FILE_SERVER_ROOT should be set to public id/domain. But it cannot work in same time.
Here is my request, i can access my seafile server by LAN IP when i am home, and by public ip/domain when i am out.
Could you provide a option to set 'FILE_SERVER_ROOT' at client? or other way can satisfy my request.

**Comment by freeplant** [comment]
You need to set and DNS server to resolve to different IP for LAN and WAN.
