### ISSUE TITLE
Accounts not shown anymore in 2.2.15

### ISSUE THREAD

**Issue by de-es** [haiwen/seadroid#809]
Since 2.2.15 I can't access the account settings nor can I switch between accounts. A downgrade to 2.2.14 restores this functionality.

Android 7.1.2, no errors shown in log.

If you need further information, let me know.

**Comment by freeplant** [comment]
Can you try to uninstall the app and re-install it (version 2.2.15)?

**Comment by de-es** [comment]
The bug does not occur in a fresh installation.

**Comment by woffs** [comment]
Can this be solved without reinstallation?

**Comment by freeplant** [comment]
I'm afraid reinstallation is the only way to solve the problem.
