### ISSUE TITLE
Can't detect folder activity

### ISSUE THREAD

**Issue by mouarfff** [haiwen/seadroid#810]
Hello
first
Thanks for this app !

So,

When i try to put a file or a folder into the seafile library folder, the app don't detect it and don't upload files.
I need to tap "upload a file" go to the explorer, search and choose the file... But i have a lot of files !
I'm in a Homtom HT70 with android 7, kernel 3.18.35

**Comment by freeplant** [comment]
The Android app is not working this way. It is not syncing the local folder. You need to explicitly upload a file.
