### ISSUE TITLE
Navigation with Markdown-Preview broken

### ISSUE THREAD

**Issue by zwieberl** [haiwen/seadroid#812]
**Current behavior (bugs)**
1. When viewing a Markdown file not yet downloaded, it does not open the viewer, but jumps back to home
2. When viewing an already downloaded Markdown file and trying to navigate back (Using <- in the upper left corner), I jump back to home.

**Expected behavior**
1. The markdown-viewer should open.
2. When navigating back, I should get back to the directory containing the Markdown-file.

**Introduced**
This was introduced either with 2.2.15 or maybe 2.2.14

**System**
Android 4.4.4

**Comment by freeplant** [comment]
I can't reproduce the problem. Can you try to uninstall the app and reinstall again?

**Comment by zwieberl** [comment]
Reinstalling fixed it!
Weird, but thank you!
