### ISSUE TITLE
Seafile/temp/ directory is getting indexed by android gallery apps

### ISSUE THREAD

**Issue by 4ley** [haiwen/seadroid#814]
The Seafile temp directory gets indexed by the android photo/gallery app which results in hundreds of "dir-hash" directories and makes the gallery app a total mess.

The issue seems not to be quite new [/Seafile/ is indexed by the Gallery](https://github.com/haiwen/seadroid/issues/588)

Adding a `.nomedia` file to the temp directory or prefix the temp directory with a dot like `.temp` would solve the problem.

**Comment by freeplant** [comment]
The fix will be included in the next release.

**Comment by R0nd** [comment]
Still reproduces in 2.2.18
