### ISSUE TITLE
Connect to Single-Sign-On-Server impossible

### ISSUE THREAD

**Issue by aroskamp** [haiwen/seadroid#823]
Hello,

I try to connect Seafile on my phone (Samsung Galaxy S9) to a Single-Sign-On-Server. After setting the server name, I am getting forwarded to the login screen of the seafile-storage-provider. There I am setting my credential. All is fine. But when the response is coming back to Seafile, it likes a “crash” and I am back at the start screen where i can add another server.

With my old phone (Samsung Galaxy S7) everything was working fine. But now it is impossible to set up for me…

The Server-Side-Support was unable to help me. Do You have any recommendation, tipps or ideas?

Greetings, Alexander

**Comment by freeplant** [comment]
What version do you use?

**Comment by aroskamp** [comment]
Seafile Version 2.2.16 (Android)
Android 9
Kernel 4.9.59-16162958

I think these are the current versions.

**Comment by freeplant** [comment]
Upgrade to.2.2.17 should solve the problem.
