### ISSUE TITLE
Cannot download or upload

### ISSUE THREAD

**Issue by battsatac** [haiwen/seadroid#829]
Hello all,

I cannot download or upload any file from seadroid (2.2.16) but I can connect and see all the tree structure.

Besides of that, everything works fine from a browser whether on a computer or the phone, whether from LAN or WAN (except editing markdown files).

Related issues [41](https://github.com/haiwen/seadroid/issues/41) and [114](https://github.com/haiwen/seadroid/issues/114) do not seem to address my case.

Any idea ?

**Comment by freeplant** [comment]
It is likely a config problem.
