### ISSUE TITLE
Add ability to "forget" password for encrypted lib manually

### ISSUE THREAD

**Issue by patcon** [haiwen/seadroid#83]
As I understand it, Seadroid remembers the password to individual encrypted libraries for some period of time. It seems that there is a slight bug, which manually being able to clear would bypass.
## Summary

When entering a password to unencrypt, and internet connection is poor, the password somehow gets registered in seadroid as "good", even if (presumably) it was incorrect, and so it keeps trying to use it. This manifests when I now try to connect to an encrypted library, but seadroid is trying the incorrect password. The dialog to provide the password pops up, but it's already completed, and "Bad Request" displays immediately (all without me having done anything except click the library to access it). For some reason, the only button on the dialog is "Cancel", and "OK" is missing. So even if I clear out the bad password.

![screenshot_2014-07-25-13-26-45](https://cloud.githubusercontent.com/assets/305339/3707159/ee6995b4-1431-11e4-8553-cd748e0d8259.png)

Let me know if there are any more details I can provide :)

**Comment by freeplant** [comment]
The issue is long ago. Now we have implemented client side encryption.
