### ISSUE TITLE
VERY frequent "Error Loading Libraries Tap to Refresh"

### ISSUE THREAD

**Issue by dshanks01** [haiwen/seadroid#830]
Android app FREQUENTLY (more often than not) displays "Error Loading Libraries Tap to Refresh" instead of my libraries. Computers have no difficulty connecting to and syncing with the Seafile server.

Seafile server version 7.0.4
Seadroid version 2.2.18
Android version 9 (Pie)

**Comment by dshanks01** [comment]
Appears to be a configuration problem on my server rather than a bug in Seadroid. At least I hope so. I haven't figured it out yet :/

**Comment by NichtEuler** [comment]
How did you solve it?
Would be very appreciated.
