### ISSUE TITLE
Misuse of AsyncTask

### ISSUE THREAD

**Issue by pangeneral** [haiwen/seadroid#831]
According to our research, there are misuses about AsyncTask in the following classes:
1. `com.seafile.seadroid2.ui.activity.SeafilePathChooserActivity`
2. `com.seafile.seadroid2.ui.activity.GalleryActivity`

The problems are:
1. There are non-static inner AsyncTask classes in `SeafilePathChooserActivity` and `GalleryActivity`. They hold strong reference to the GUI element of Activity, which can lead to memory leak when the Activity is destroyed and the AsyncTask did not finish.
2. Their instances are not cancelled before the Activity is destroyed, which can lead to the wrong invocation of onPostExecute

I think we can make following changes to fix the misuse problems:
1. I think the inner AsyncTask classes should be changed to static classes;
2. Add a AsyncTask field in the corresponding Activities which use AsyncTask. These field refer to the annoymous AsyncTask object such as `new ASyncSMSRecovery.SMSRecoveryTask(me, _account).execute()`. Then invoke `cancel()` in the onDestroy() method of Activities.

These are my suggestions above, thank you.

**Comment by zhwanng** [comment]
Thank you very much for your suggestions, we will optimise and improve these features!
