### ISSUE TITLE
Encrypted Repo/Library local storage

### ISSUE THREAD

**Issue by damianorenfer** [haiwen/seadroid#833]
Hi there,

I just noticed that encrypted libraries are stored locally decrypted, I mean the content of the lib is browsable from any other app.

This breaks the encryption concept from an end-to-end point of view. You probably should store the libs encrypted and decrypt them on the fly each time the users want to access it from seadroid.

**Comment by freeplant** [comment]
The end-to-end encryption is to make sure the file can't be viewed via the admin at the server side. It is not cover the client side.

**Comment by damianorenfer** [comment]
Ok I see! It would be a cool feature anyway :)
