### ISSUE TITLE
Somewhere between 2.1.20 and 2.2.18 file uploads was broken

### ISSUE THREAD

**Issue by dimasafo** [haiwen/seadroid#836]
Tested on yoursecurecloud.de

On 2.2.18 file uploads does not work
The library is not encrypted
Deleting and reinstalling android application did not help.

This is definitely a bug. It appears in two forms.

1. If the library belongs to the current user. Then, after pressing "upload a file", the notification “uploading started” appears, but nothing happens after that. No errors. Nothing at all. File not added to library.

2. If the library belongs to another user, but the current user can write and read into it, then another behavior. After pressing "upload a file", the notification “uploading started” appears, and then I see "uploading failed" notification. File not added to library.

On 2.1.20 - it works OK.

**Comment by freeplant** [comment]
We will add more log to debug the issue.
