### ISSUE TITLE
Google Play Store still serves outdated version 2.2.18

### ISSUE THREAD

**Issue by RoestVrijStaal** [haiwen/seadroid#840]
See self-explanatory screenshot:
![httpsplay google comstoreappsdetailsid-com seafile seadroid2_2019-11-12_23 35-fullpage](https://user-images.githubusercontent.com/6899548/68716968-c751f000-05a5-11ea-9644-5f643a15d945.png)

Could you please publish the new(est) stable version to Google Play Store?

**Comment by freeplant** [comment]
It is updated now.
