### ISSUE TITLE
Allow auto uploac of arbitrary folders.

### ISSUE THREAD

**Issue by Ashaman-** [haiwen/seadroid#848]
For example, I have Titaniumbackup automatically backing up my phone, and would like to have the resulting folder automatically uploaded. Signal local backups is another prominent one. I'm currently using the Nextcloud app to auto upload to a webdav mount of a seafile library in Nextcloud, and I would rather not use Nextcloud's file sync'ing capabiities at all because seafile is so much better at it.

**Comment by plantroon** [comment]
> For example, I have Titaniumbackup automatically backing up my phone, and would like to have the resulting folder automatically uploaded. Signal local backups is another prominent one. I'm currently using the Nextcloud app to auto upload to a webdav mount of a seafile library in Nextcloud, and I would rather not use Nextcloud's file sync'ing capabiities at all because seafile is so much better at it.

What are you using these days? This feature is the only reason why I can't switch to Seafile. I am using Syncopoli (rsync to my server basically). I need to sync all data and this includes audio recordings. Seafile can do pictures and video quite reliably (although it's very delayed on Android 10) but nothing else.

**Comment by andrewfenn** [comment]
It's a little confusing navigating this github project as I can't see what features are planned on the roadmap, but I too would like it if the developers could please add the ability to do a complete phone backup or partial backup. Nothing fancy, just one way push all files that don't exist to a seafile library.

Please let me know what I can do with the exception of coding to get this in the app as it's a highly valued feature for me.

**Comment by maxiaoping** [comment]
Please update the latest version

**Comment by plantroon** [comment]
> Please update the latest version

What do you mean?

**Comment by MoriarT3a** [comment]
@plantroon I use Syncthing at the moment for keepass and backups from signal and my podcast player database.

@maxiaoping I use the 2.2.39 Version and can't see any sync options.

At last I hope I can use seafile as my only solution and drop Syncthing. :-)

**Comment by plantroon** [comment]
@MoriarT3a for me syncthing was too complex and I already have a server that runs most of my cloud stuff, so I feel like syncthing isn't really aimed at a user like myself.

I checked those sync options in 2.2.39 and nothing :(

Currently I use Nextcloud, and I only use its file synchronization features as I have better options for everything else.

**Comment by chb567** [comment]
Id like this feature as well, im also using syncthing for now, although its great, id be looking forward to having a more featured seafile android experience.

**Comment by Gnorv** [comment]
I think this is related to the [oldest open issue](https://github.com/haiwen/seadroid/issues/4) and [second oldest](https://github.com/haiwen/seadroid/issues/55) there is. This request has been around for almost 10 years now, and it is the only reason I cannot switch to using Seafile.
I have my phone and tablet doing backups, changes to documents, and use it for reading with Librera. All of these need to be uploaded automatically to my home server, and also synched with other devices. My current solution is Syncthing but I want the option of having files in the cloud only, not also on the device.

**Comment by freeplant** [comment]
In the latest version, you can backup any folders on the android device.
