### ISSUE TITLE
Newest Versions not compatible with Android 4.4.2 anymore

### ISSUE THREAD

**Issue by mqus** [haiwen/seadroid#849]
I'm using seafile (and the android client) for many years now but the newest versions seem to be incompatible with my smartphone, which runs on Android 4.4.2 (Kitkat/API 19). The change which matters seems to be https://github.com/haiwen/seadroid/pull/843/commits/f68f424bb6daeac1666f2c9312f50434179df035 but I can't make out the specific reasons.

Would it be possible to restore `minSdkVersion` to `16` (or even `19`) without breaking existing functionality? If not, why?

I'm aware that Android <=4.4 users are very much in the minority now but a proper explanation in the changelogs(or https://github.com/haiwen/seadroid/releases) would have been nice.

Even if you can't bring the compatibility back, thank you for the ride until now. I'll probably install seadroid again if I have a new phone sometime in the future.

**Comment by Huge** [comment]
Looks like making photo upload more elegant with cleaner code, see `@RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)` an if switch around seems possible.
