### ISSUE TITLE
Android storage access framework, DocumentsProvider with open file tree support

### ISSUE THREAD

**Issue by cyrinux** [haiwen/seadroid#853]
Hi,

I first opened an issue on seedvault, but seems its a cross issue between seedvault and seafile-server.

I'm not android dev so sorry, but the idea is to implement the missing api that nextcloud now, to expose the storage the seedvault application.

Then seedvault will need to whitelist seafile client.

stevesoltys/seedvault#84
stevesoltys/seedvault#12

@grote give the solution here
https://github.com/stevesoltys/seedvault/issues/84#issuecomment-621222238

Please tell me if you need more, i think with the 3 links ^ there is info you will need :)

Kind regards

**Comment by grote** [comment]
It looks like this is already supported: https://github.com/haiwen/seadroid/blob/5a0710c1d8fc4a57c26dfbc9df201b96c903bbd6/app/src/main/java/com/seafile/seadroid2/provider/SeafileProvider.java#L650
