### ISSUE TITLE
Large file uploads fail

### ISSUE THREAD

**Issue by MateEke** [haiwen/seadroid#854]
Upload of large files (100MB+) - mostly videos over auto upload function - always fail.

The progress bar shows 100% then "Upload failed".

[Video](https://drive.google.com/open?id=1BnlTZStMu0Z0g_zrFoKIAhQ4tcFuyM6E)

No error in server error logs.

Uploading of the same files from the same phone over browser (Google Chrome) works fine.

Server Version: 7.1.3 CE
APP Version: 2.2.25

**Comment by maxiaoping** [comment]
Test 138MB can complete automatic upload

**Comment by newdanceradio** [comment]
Hello, i have the same problem.
Server: 9.0.2 (Nginx Reverse Proxy)
Android app: 2.2.42

Photos from my phone successfully uploaded, but video file 1.2 GB and 1.5 GB can't fully be uploaded, it goes uploaded about 400-480 MB and Upload Canceled.

**Comment by vicky-bs** [comment]
> Upload of large files (100MB+) - mostly videos over auto upload function - always fail.
> 
> The progress bar shows 100% then "Upload failed".
> 
> [Video](https://drive.google.com/open?id=1BnlTZStMu0Z0g_zrFoKIAhQ4tcFuyM6E)
> 
> No error in server error logs.
> 
> Uploading of the same files from the same phone over browser (Google Chrome) works fine.
> 
> Server Version: 7.1.3 CE APP Version: 2.2.25

+1 . Upload works well on browser but android client upload fails for large files
