### ISSUE TITLE
Android app not honoring session cookies

### ISSUE THREAD

**Issue by Radapompa** [haiwen/seadroid#860]
We're using loadbalancing for Seafile setup. Where the loadbalancing is using session cookies for stickiness, as descibed in the manual for HAProxy: https://seafile.gitbook.io/seafile-server-manual/deploy-seafile-pro-edition/cluster-deployment/deploy-in-a-cluster#haproxy

This works for webclient and desktop clients. But we've seen that the Android client is not using the session cookie. So if you try to download files through the Android client, it will fail. We've tried to remove all servers but one from loadbalancing, and then the client works as expected.

Can't confirm if we have the same issues with iOS clients or not.

**Comment by freeplant** [comment]
It is likely a problem caused by your cluster setup. The document you used for deploy cluster is outdated. This is the new one: https://manual.seafile.com/deploy_pro/deploy_in_a_cluster/
