### ISSUE TITLE
Can't Download/Upload anything

### ISSUE THREAD

**Issue by xifi-kif** [haiwen/seadroid#866]
Don't know if it's related to https://github.com/haiwen/seadroid/issues/800 but anyway I can't download anything nor upload anything with seafile android app downloaded from playstore v.2.2.25. 

I tried with many phones: 
- Xiaomi Redmi note 4 with Lineage OS
- Samsung Galaxy A41 stock firmware
- An old Samsung Galaxy Tab 
No one can download or upload.

![index3](https://user-images.githubusercontent.com/22835942/91662618-d9286380-eae3-11ea-8af5-b16433f65b14.jpeg)
![index2](https://user-images.githubusercontent.com/22835942/91662620-d9c0fa00-eae3-11ea-99a9-841dec0c37a9.jpeg)
![index](https://user-images.githubusercontent.com/22835942/91662621-d9c0fa00-eae3-11ea-9cdc-151f96fb52ee.jpeg)

Web client and desktop clients works with no problem.

**Server is v7.1.4 on Banana PI (ubuntu 18.04).**

**Comment by xifi-kif** [comment]
wierd thing: if I click on the 3 dots menu inside a library and select "add" I'm able to create a new file

**Comment by james-smith-za** [comment]
I also experienced this after porting my seafile installation from a VM to a docker image. I'd obviously not configured it correctly somehow.

In System Admin -> Settings there are SERVICE_URL and FILE_SERVER_ROOT, which were default values and not correct. Once I fixed that, the android issues worked.

Weirdly, accessing Seafile via the browser or desktop clients worked like a charm. It was just the android client that failed.

**Comment by xifi-kif** [comment]
I checked SERVICE_URL and FILE_SERVER_ROOT are fine.

The worst thing are logs not showing anything useful.

**Comment by xobs** [comment]
I'm also seeing this, with no useful information in the logs.

Seadrive and Seafile work as does the Web client. It's just seadroid that's causing the issue.

**Comment by xifi-kif** [comment]
I'm diggin deeper into this problem and I'm becoming very angry:
I created a seafile server on a VM for testing purpose, with **same identical configuration** in nginx. Everything works. I'm thinking of something that might went wrong when updating through versions during the years, don't know. Really this is making me crazy. I'm thinking of reinstalling the whole system and restoring the data just to see if it works.

**Comment by maxiaoping** [comment]
Please upgrade to the latest version

**Comment by xobs** [comment]
I'm running the latest version of Seadroid that the Android Market has -- 2.2.25.

**Comment by xifi-kif** [comment]
I had to reinstall the whole server and import all the data due to a hard disk fail (backup saved my life).
Once reinstalled everything, the issue was gone. 
I leave this open for @xobs

**Comment by maxiaoping** [comment]
Please update the latest version
