### ISSUE TITLE
Images don't download automatically

### ISSUE THREAD

**Issue by NichtEuler** [haiwen/seadroid#868]
Hello,

as I said in the title, images won't download if opened.
This is shown instead.
![photo_2020-10-02_00-24-21](https://user-images.githubusercontent.com/33428455/94869423-a0164280-0445-11eb-8d4a-f12ebc3b2ac3.jpg)

To get the images to be viewable they need to be downloaded manually.
Doesn't work on Honor 7x, Samsung A40, Samsung Tab S3.

Thank you

**Comment by maxiaoping** [comment]
The new edition has been updated

**Comment by maxiaoping** [comment]
2.2.30 versions has been updated
