### ISSUE TITLE
Android Client - SingleSignOn, No Network Connection

### ISSUE THREAD

**Issue by Scoeerg** [haiwen/seadroid#884]
The Android Client 2.2.32 and 2.2.33 both throw a "No Network Connection" when trying to Single-Sign-In. Obviously I checked my network connection, which is fine.

Tested on Galaxy Tab S7+
Android 11, Patch March 1 2021
Kernel 4.19.113-20133099

The test server (https://seafile.rlp.net) is online and can be reached with the Browser from said Tablet.

**Comment by maxiaoping** [comment]
Please update the latest version for testing
