### ISSUE TITLE
[Feature request] Stream videos to external players such as VLC

### ISSUE THREAD

**Issue by fdisamuel** [haiwen/seadroid#886]
First of all, I think seadroid has a pretty solid embedded video player with a great features, however in some cases it is useful to have the option to stream videos in external players for extended functionality such as speed controlling. Currently when I try to open a video in an external player e.g. VLC using the export option in seadroid, the whole video file gets downloaded and then played, instead of streamed to the player. 

A possible workaround: 
--> Get a share link within the app to the video, make it a direct download link (append `.../?dl=1`) and then paste it to VLC, 
    which will begin to play the video as a stream. 

**Pros/cons**
- the stream name will be "/?dl=1" which is not so convenient
- after watching the video I have to manually delete the share link at seahub.

I wonder if a similar method could be implemented to seadroid. For example a temporary link could be generated and passed to the external player automatically. As far as I know, such temporary link is generated in seahub when opening a video file in new browser tab. 
It looks something like this:
 `https://seafile.mydomain.tld/seafhttp/files/513146a0-6fbd-4048-bb58-c255e7d28929/my_video_file.mp4` 
 **Pros/cons**
- By pasting the link in VLC we get a proper filename, so I prefer this solution over the share link.
- the link contains a token which is valid only for 24 hours (I guess), so I do not have to take care of cleaning up when the link is not needed anymore. 

The onedrive app for android also has a similar method to play cloud videos in external players (it passes a download link).

Would be possible tho implement such a feature in seadroid?

Thanks!

**Comment by maxiaoping** [comment]
You can choose to share the video link and set the automatic expiration time

![image](https://user-images.githubusercontent.com/7161204/115979255-6fe7ea00-a5b7-11eb-9e3b-27ef45580d33.png)
