### ISSUE TITLE
New Download location com.seafile.seadroid2 leads to the files not being accessible through other apps

### ISSUE THREAD

**Issue by raphaelporsche** [haiwen/seadroid#889]
Hello,

Seadroid changed downloading files from /Seafile to /Android/data/com.seafile.seadroid2 in some of the previous releases. This changes things drastically since files in the /Android/data directory cannot be accessed from other applications by principle! Therefore files stored in Seafile can't be viewed/edited/used trough other apps in android (the exception being exporting files which can't be done with directories or directory trees).
This is a big problem for me, because I need to download whole directories in Android and then access them through external apps (e.g. my scientific literature library).

Proposed solution:
Please change the default directory to /Android/media/com.seafile.seadroid2 or /Seafile or even better give the user the freedom to choose.

Thanks for your help!
With kind regards
Raphael

**Comment by AchimKlotz** [comment]
That is also a big issue for me. With that new location I can't access the data with other apps like the default photo app or the smart audio player. It would be really great if at least the folder for storing the data is configurable. Otherwise the app is not that useful for me

**Comment by RoestVrijStaal** [comment]
I'm facing the same issue.

And due that I can not "sync" databases of my password manager anymore.

I advise to add the possibility to save the file "as-is" via the "Export"-option. 
Or add another option to redownload (=overwrite the local file with the external one) and open the file by mime-type.

**Comment by maxiaoping** [comment]
update 2.2.36

**Comment by raphaelporsche** [comment]
Thank you very much!

**Comment by RoestVrijStaal** [comment]
@maxiaoping 
That sounds promising, unfortunately Google Play Store still serves 2.2.34 at the moment of writing this comment.

**Comment by dkaschl** [comment]
@RoestVrijStaal You can get 2.3.36 also from F-Droid. I got it today from that repo.

**Comment by RoestVrijStaal** [comment]
@dkaschl Once I used F-Droid indeed. But I got fed for poking the F-Droid-slowpokes at each new release of seadroid because they didn't update it (or used GitHub RSS for auto-updating it).
______
@maxiaoping When will version 2.2.36 appear in Google Play Store?

**Comment by maxiaoping** [comment]
Updated to the latest version
