### ISSUE TITLE
Can't establish TLS connection to Seafile Server on Android 10

### ISSUE THREAD

**Issue by lp55** [haiwen/seadroid#890]
Hi,

I'm running a seafile server with a caddy server as a reverse proxy, using TLS 1.3 and a Elliptic Curve 256 certificate. With the pc client (linux and windows) version >= 8, I can connect and everything works fine. But the android client complains about the certificate. It has the same error message as cited in issue #599.
The comments on the issue #599 say that's due to lack of support for TLS 1.3 on the system libraries, but Android 10 (according to [this](https://developer.android.com/about/versions/10/features#tls-1.3)) has support for TLS 1.3, so I'm not sure what the issue is.
Any ideas?

**Comment by RainCat1998** [comment]
Using TLS 1.2 instead. I have the same problem so I changed the minimal TLS version support(1.3only to >=1.2) of my server and everything works fine. 
Android seafile client of support for TLS 1.3 but IOS version supports TLS 1.3.

**Comment by sebw** [comment]
I recently migrated Seafile from one VPS to another. Meanwhile I upgraded the minimum TLS from v1.2 to v1.3 on the Traefik reverse proxy.

The Linux client didn't complain but the Android app (Play Store or F-Droid) started complaining with a less than useful message:

![image](https://user-images.githubusercontent.com/2285094/126527554-fab6755b-f6ea-4b1a-bdc5-d753a1d44e27.png)

I could reach my Seafile from Firefox Focus on my phone, so it took me some time to realize this was the TLS version.

I asked a friend to try with his iPhone and TLS v1.3 seems supported there.

**Comment by imp1sh** [comment]
I'm also suffering the same problem as sebw. As a workaround I enabled  EECDH+AESGCM:EDH+AESGCM:DHE-RSA-AES128-SHA; (in my case nginx) and disabled ssl_stapling and ssl_stapling_verify.
After that it works but I really think we need support for stronger security on the android client, because I now had to weaken the server just so Android user are also able to connect.
Reference:
https://forum.seafile.com/t/android-client-cannot-verify-letsencrypt-certificate/8064/12
https://forum.seafile.com/t/android-app-uses-wrong-ssl-certificate-no-trusted-ssl-server/10680
https://forum.seafile.com/t/android-client-network-error/14751/3

**Comment by Florian-Sabonchi** [comment]
> Using TLS 1.2 instead. I have the same problem so I changed the minimal TLS version support(1.3only to >=1.2) of my server and everything works fine. 
> Android seafile client of support for TLS 1.3 but IOS version supports TLS 1.3.
> 

This is not a good solution. This worsens the security

**Comment by Florian-Sabonchi** [comment]
> Referring to [this](https://developer.android.com/reference/javax/net/ssl/SSLSocket.html#protocols), would the following change be enough to enable TLS 1.3, since [TLS 1.3 cipher suites cannot be customized](https://developer.android.com/about/versions/10/behavior-changes-all#tls-1.3)?
> ```diff
>     protected String[] getProtocolList() {
>         // don't offer SSLv2 or SSLv3
> +         if (Build.VERSION.DSK_INT >= 29) {
> +            return new String[]{"TLSv1", "TLSv1.1, "TLSv1.2", "TLSv1.3"};
> -        if (Build.VERSION.SDK_INT >= 16) {
> +       } else  if (Build.VERSION.SDK_INT >= 16) {
>             return new String[]{ "TLSv1", "TLSv1.1", "TLSv1.2" };
>         } else {
>             return new String[]{ "TLSv1" };
>         }
>     }
> ```
> https://github.com/haiwen/seadroid/blob/4ea33de096c6012188a113d441b945cb765702f2/app/src/main/java/com/seafile/seadroid2/ssl/SSLSeafileSocketFactory.java#L103-L110 

It looks like pull requests are ignored

**Comment by MarcelHoell** [comment]
Will this be implemented? I cannot use the Android app right now...

**Comment by erbanku** [comment]
> Confirming this problem, Android app doesn't work with TLS v1.3 (or EC certs).

Yes, it is. I am on Android 12 with the latest app (Saturday, November 19, 2022) TLS v1.3 doesn't work; The app worked surprisingly after I changed the minimal TLS version to 1.2 on Cloudflare Dashboard.

**Comment by louisroyer** [comment]
I fixed this issue in the app with PR https://github.com/haiwen/seadroid/pull/913 last year, but it has never been merged… This is very frustrating.
