### ISSUE TITLE
Enter settings, software crash

### ISSUE THREAD

**Issue by darlexlin** [haiwen/seadroid#892]
1、Enter settings, software crash
2、Synchronization cannot be performed

**Comment by atomdmac** [comment]
Seeing the crash on Pixel 2 on Android 11.  Syncing continues to work, however.

**Comment by DPTJKKVH** [comment]
This is a duplicate of #874 . Please post your logcat excerpts there.

**Comment by fabian-z** [comment]
The settings and sync work for me on Android 11 after moving a null check - if you are affected, please test my fix in #894.

I am not sure if this is in fact a duplicate of #874, since there are different logcats in this issue and no logs are posted here.

**Comment by maxiaoping** [comment]
Please update the latest version

**Comment by darlexlin** [comment]
The latest version is ok.
