### ISSUE TITLE
Trying to move several files from an encrypted library to a subfolder -> repeatable crash

### ISSUE THREAD

**Issue by timonoj** [haiwen/seadroid#898]
Hi!    
    
I'm trying to move multiple files within an encrypted library to a different folder. This seems complicated: Once a multiple file selection is made, the "Move" and "Copy" buttons at the top will only show the other unencrypted libraries to choose, but not the current one. And if you click on the right side of a file, you can get the Copy/Move options among some other options, but I never managed to see if it would apply to one or all the selected files, because the moment you try to choose a folder, Seafile crashes completely.

I guess there's multiple bugs regarding this, any idea if they will be resolved?

Thanks!

**Comment by maxiaoping** [comment]
The modification is complete. Please update the latest version
