### ISSUE TITLE
Can't Download/Upload anything other than PNG or JPG previews

### ISSUE THREAD

**Issue by xobs** [haiwen/seadroid#899]
Continuing the issue from https://github.com/haiwen/seadroid/issues/866

Seadroid appears to be unable to download files unless they are jpg or png previews.

When viewing an image such as a JPG or PNG, the program shows a thumbnail. Clicking the "Download" button causes the screen to pop up a box saying "Downloading files...". This operation never finishes. The "Back" button does not work. The program must be force-closed.

Attempting to download any other sort of file (e.g. PDF, MP3) results in a Toast that says "Download failed", followed by an endless stream of toasts that say `Failed to download file "[filename`

This is using the latest available Seafile version from the Play store (2.2.39) and the latest available official Seafile server from Docker (6.3.4).

**Comment by maxiaoping** [comment]
I tested version 2.2.39 and did not find any of the problems you described
![image](https://user-images.githubusercontent.com/7161204/124255911-4621e500-db5d-11eb-8f45-509923139b08.png)

**Comment by maxiaoping** [comment]
It is recommended that you reinstall the test after uninstalling

**Comment by xobs** [comment]
I just removed the app from my device and reinstalled it from the Play store. It still says `Download failed`, followed by `Failed to downlaod file "FILENAME`:
![image](https://user-images.githubusercontent.com/238325/124257569-1247bf00-db5f-11eb-85e1-d8ab33251651.png)
![image](https://user-images.githubusercontent.com/238325/124257580-14aa1900-db5f-11eb-9ffd-acdc5179fa00.png)

**Comment by xobs** [comment]
Additionally, (and this is still on the device with a fresh install), JPG previews work fine, however clicking the "download" button brings up a dialog box that never finishes:

![image](https://user-images.githubusercontent.com/238325/124258721-4d96bd80-db60-11eb-947f-6e0f703ea8f2.png)
![image](https://user-images.githubusercontent.com/238325/124258732-4ff91780-db60-11eb-86d6-0cacfa22d243.png)

**Comment by maxiaoping** [comment]
https://dev.seafile.com/seahub/f/2e15a2c9f4fc4a0494ea/?dl=1

I'm going to give you a test package and you can try to see if it solves the problem

**Comment by xobs** [comment]
That does not appear to solve the problem. The new APK (which still identifies itself as 2.2.39) exhibits the same behavior. It still says "Download failed" when I try to download files other than PNG/JPG previews.

**Comment by maxiaoping** [comment]
You can uninstall the previous app, install the link to download the app to try

**Comment by xobs** [comment]
Just to be sure, I uninstalled the previous version, installed the apk you linked, and re-registered. It exhibited the same issues. Note that the one you posted is still version 2.2.39, or at least has `2.2.39` in its filename:
```
user@Cuboid:~$ curl --head 'https://dev.seafile.com/seahub/f/2e15a2c9f4fc4a0494ea/?dl=1'
HTTP/1.1 302 Found
Server: nginx/1.14.0 (Ubuntu)
Date: Fri, 23 Jul 2021 04:53:48 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
Location: https://dev.seafile.com/seafhttp/files/ebc5f11d-075b-4dcf-b53e-791f30418a39/seafile-2.2.39.apk
Vary: Cookie, Accept-Language
Content-Language: en
Set-Cookie: sfcsrftoken=YEKwACtJuRjA8CO2yYnI1FjjHiK542OHtT0FMQnjGpwE6WuqhQN2lP8aAC0j1fTd; expires=Fri, 22-Jul-2022 04:53:48 GMT; Max-Age=31449600; Path=/
Access-Control-Allow-Origin: *

user@Cuboid:~$
```

**Comment by maxiaoping** [comment]
https://dev.seafile.com/seahub/f/6f6eea79fb67465f9a85/?dl=1

Try the 2.2.40 test package

**Comment by xobs** [comment]
That version lists `2.2.40` as the version number, and exhibits the same error message.

**Comment by maxiaoping** [comment]
Phone model and android system version ？

**Comment by xobs** [comment]
I have a Huawei P30 Pro (VOG-L29) running the latest available build (11.0.0.151).

I'm unclear whether this has anything to do with it, but I do see a JSON error in the adb log that I occasionally see that mentions a completely different repo. The error is odd because that appears to be valid JSON:

```
07-23 13:40:49.681 22719 22719 V DataManager: Get cached starred files: [{"file_name":"Todo.txt","icon_path":"24/txt.png","oid":"db0502a9d4cbc7ec79365eedfaa6c57a9a305a5d","mtime_relative":"<time datetime=\"2017-10-14T13:39:30\" is=\"relative-time\" title=\"Sat, 14 Oct 2017 13:39:30 +0000\" >2017-10-14</time>","repo":"e9fbf31a-5c6e-4649-87a0-8cb2c4b3ffaf","org":-1,"path":"/Todo.txt","size":436,"repo_id":"e9fbf31a-5c6e-4649-87a0-8cb2c4b3ffaf","mtime":1507988370,"dir":false,"repo_name":"Notes"},{"file_name":"Done.txt","icon_path":"24/txt.png","oid":"d9d726477f2523f2cd69ba88f23233ed1ccd3a4b","mtime_relative":"<time datetime=\"2017-04-06T04:22:35\" is=\"relative-time\" title=\"Thu, 6 Apr 2017 04:22:35 +0000\" >2017-04-06</time>","repo":"e9fbf31a-5c6e-4649-87a0-8cb2c4b3ffaf","org":-1,"path":"/Done.txt","size":2162,"repo_id":"e9fbf31a-5c6e-4649-87a0-8cb2c4b3ffaf","mtime":1491452555,"dir":false,"repo_name":"Notes"}]
07-23 13:40:49.681 22719 22719 E DataManager: Could not parse cached starred files
07-23 13:40:49.681 22719 22719 E DataManager: org.json.JSONException: Value [{"file_name":"Todo.txt","icon_path":"24\/txt.png","oid":"db0502a9d4cbc7ec79365eedfaa6c57a9a305a5d","mtime_relative":"<time datetime=\"2017-10-14T13:39:30\" is=\"relative-time\" title=\"Sat, 14 Oct 2017 13:39:30 +0000\" >2017-10-14<\/time>","repo":"e9fbf31a-5c6e-4649-87a0-8cb2c4b3ffaf","org":-1,"path":"\/Todo.txt","size":436,"repo_id":"e9fbf31a-5c6e-4649-87a0-8cb2c4b3ffaf","mtime":1507988370,"dir":false,"repo_name":"Notes"},{"file_name":"Done.txt","icon_path":"24\/txt.png","oid":"d9d726477f2523f2cd69ba88f23233ed1ccd3a4b","mtime_relative":"<time datetime=\"2017-04-06T04:22:35\" is=\"relative-time\" title=\"Thu, 6 Apr 2017 04:22:35 +0000\" >2017-04-06<\/time>","repo":"e9fbf31a-5c6e-4649-87a0-8cb2c4b3ffaf","org":-1,"path":"\/Done.txt","size":2162,"repo_id":"e9fbf31a-5c6e-4649-87a0-8cb2c4b3ffaf","mtime":1491452555,"dir":false,"repo_name":"Notes"}] of type org.json.JSONArray cannot be converted to JSONObject
07-23 13:40:49.681 22719 22719 E DataManager:   at org.json.JSON.typeMismatch(JSON.java:112)
07-23 13:40:49.681 22719 22719 E DataManager:   at org.json.JSONObject.<init>(JSONObject.java:168)
07-23 13:40:49.681 22719 22719 E DataManager:   at org.json.JSONObject.<init>(JSONObject.java:181)
07-23 13:40:49.681 22719 22719 E DataManager:   at com.seafile.seadroid2.data.DataManager.parseStarredFiles(SourceFile:562)
07-23 13:40:49.681 22719 22719 E DataManager:   at com.seafile.seadroid2.data.DataManager.getCachedStarredFiles(SourceFile:657)
07-23 13:40:49.681 22719 22719 E DataManager:   at com.seafile.seadroid2.ui.fragment.StarredFragment.refreshView(SourceFile:161)
07-23 13:40:49.681 22719 22719 E DataManager:   at com.seafile.seadroid2.ui.fragment.StarredFragment.onResume(SourceFile:131)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.support.v4.app.Fragment.performResume(SourceFile:2390)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1474)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(SourceFile:1759)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1827)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(SourceFile:3244)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.support.v4.app.FragmentManagerImpl.dispatchResume(SourceFile:3212)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.support.v4.app.FragmentController.dispatchResume(SourceFile:217)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.support.v4.app.FragmentActivity.onResumeFragments(SourceFile:509)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.support.v4.app.FragmentActivity.onPostResume(SourceFile:498)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.support.v7.app.AppCompatActivity.onPostResume(SourceFile:171)
07-23 13:40:49.681 22719 22719 E DataManager:   at com.seafile.seadroid2.ui.activity.BrowserActivity.onPostResume(SourceFile:970)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.app.Activity.performResume(Activity.java:8283)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4896)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4949)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2458)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.os.Handler.dispatchMessage(Handler.java:110)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.os.Looper.loop(Looper.java:219)
07-23 13:40:49.681 22719 22719 E DataManager:   at android.app.ActivityThread.main(ActivityThread.java:8387)
07-23 13:40:49.681 22719 22719 E DataManager:   at java.lang.reflect.Method.invoke(Native Method)
07-23 13:40:49.681 22719 22719 E DataManager:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
07-23 13:40:49.681 22719 22719 E DataManager:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
07-23 13:40:49.682  1663  1857 I HwAudioServiceEx: ComponentInfo : className = com.seafile.seadroid2.ui.activity.BrowserActivity, flag = onResume, isHomeActivity = , isTop = true
```

**Comment by xobs** [comment]
Note that the error above is in a repo called `Notes`, and I have been doing all of my testing in a repo called `Music`.

**Comment by maxiaoping** [comment]
The cache file of the uninstalled app is not completely cleared

**Comment by xobs** [comment]
How should I clear the cache file? I have removed the APK again. I have no files or folders on my device called "haiwen" or "seafile" or "seadroid".

**Comment by maxiaoping** [comment]
/storage/emulated/0/Android/media/com.seafile.seadroid2/

/storage/emulated/0/Android/data/com.seafile.seadroid2/

**Comment by xobs** [comment]
Neither of those directories exist on my device. Note that I have uninstalled the apk again.

**Comment by maxiaoping** [comment]
Open your mobile browser and copy the link, click Browse to download the version, and then install it

**Comment by maxiaoping** [comment]
https://dev.seafile.com/seahub/f/6f6eea79fb67465f9a85/?dl=1

Open your mobile browser and copy the link, click Browse to download the version, and then install it

**Comment by xobs** [comment]
That's how I'm installing it. I've tried installing the APK twice. Now that I have reinstalled the APK, I have the two directories you mentioned earlier:

```
/storage/emulated/0/Android/media/com.seafile.seadroid2/
/storage/emulated/0/Android/data/com.seafile.seadroid2/
```

However, it still fails to upload or download anything with exactly the same error messages.

**Comment by maxiaoping** [comment]
Please check if your storage permissions are disabled

**Comment by xobs** [comment]
![image](https://user-images.githubusercontent.com/238325/126748051-c4b7647b-d47a-46ca-9472-b42a15152191.png)

Storage permissions are allowed

**Comment by maxiaoping** [comment]
Huawei phone? Android 10?

**Comment by xobs** [comment]
Yes. Huawei P30 Pro, Android 10.

**Comment by maxiaoping** [comment]
Can I log in the app？

Is the download and upload just not successful

**Comment by xobs** [comment]
I can log in and browse. I can download image previews, for example jpg thumbnails. However, upload and download are not successful.

**Comment by maxiaoping** [comment]
https://dev.seafile.com/seahub/f/7da58e8143814e448940/?dl=1

Install the test app that collects and downloads logs

Log path：/storage/emulated/0/Android/media/com.seafile.seadroid2/xxxLog.txt

**Comment by xobs** [comment]
Hi,

Here is the contents of a file. The screen is showing `Failed to download file "seafile-ignore.txt` repeatedly on the screen.

```
2021-07-29 19:42:30    d    Utils    phoneModelInfo-------HUAWEI/VOG-L29/10
2021-07-29 19:42:45    d    Utils    ---------DownloadTask---54line---23898b31-5c7d-4ee0-a2d7-08b4d2bcd2b0---/seafile-ignore.txt---67---Music
2021-07-29 19:42:45    d    Utils    ---------getFile---464line---/storage/emulated/0/Android/media/com.seafile.seadroid2/Seafile/sean@xobs.io (nas.xobs.io)/Music/seafile-ignore.txt
2021-07-29 19:42:45    d    Utils    ----------initWidgets---/seafile-ignore.txt
2021-07-29 19:42:45    d    Utils    ------DownloadTask--104--------1
2021-07-29 19:42:45    d    Utils    ------DownloadTaskManager--------1
2021-07-29 19:42:45    d    Utils    ------BrowserActivity--2109--------1
2021-07-29 19:44:42    d    Utils    ---------DownloadTask---54line---23898b31-5c7d-4ee0-a2d7-08b4d2bcd2b0---/seafile-ignore.txt---67---Music
2021-07-29 19:44:42    d    Utils    ---------getFile---464line---/storage/emulated/0/Android/media/com.seafile.seadroid2/Seafile/sean@xobs.io (nas.xobs.io)/Music/seafile-ignore.txt
2021-07-29 19:44:42    d    Utils    ----------initWidgets---/seafile-ignore.txt
2021-07-29 19:44:42    d    Utils    ------DownloadTask--104--------2
2021-07-29 19:44:42    d    Utils    ------DownloadTaskManager--------2
2021-07-29 19:44:42    d    Utils    ------BrowserActivity--2109--------2
```

**Comment by xobs** [comment]
Interestingly, the directory `/storage/emulated/0/Android/media/com.seafile.seadroid2/Seafile/sean@xobs.io (nas.xobs.io)/Music/` does exist. However `/storage/emulated/0/Android/media/com.seafile.seadroid2/Seafile/sean@xobs.io (nas.xobs.io)/Music/seafile-ignore.txt` does not exist.

**Comment by maxiaoping** [comment]
https://dev.seafile.com/seahub/f/7da58e8143814e448940/?dl=1

Install the test app to further collect detailed logs and lock specific problems

Clear the cache of path （/storage/emulated/0/Android/media/com.seafile.seadroid2/Seafile/） before installing tests

**Comment by xobs** [comment]
The directory `/storage/emulated/0/Android/media/com.seafile.seadroid2/` was removed when I uninstalled the APK prior to installing the test version.

With this new test version, attempting to download files causes the program to crash to the system launcher.

The log file doesn't look any more interesting, though:

```
2021-07-30 19:16:59    d    Utils    phoneModelInfo-------HUAWEI/VOG-L29/10
2021-07-30 19:17:32    d    Utils    ---------DownloadTask---54line---23898b31-5c7d-4ee0-a2d7-08b4d2bcd2b0---/seafile-ignore.txt---67---Music
2021-07-30 19:17:34    d    Utils    phoneModelInfo-------HUAWEI/VOG-L29/10
2021-07-30 19:17:38    d    Utils    ---------DownloadTask---54line---23898b31-5c7d-4ee0-a2d7-08b4d2bcd2b0---/seafile-ignore.txt---67---Music
2021-07-30 19:17:38    d    Utils    ----------initWidgets---/seafile-ignore.txt
2021-07-30 19:17:40    d    Utils    phoneModelInfo-------HUAWEI/VOG-L29/10
```

**Comment by maxiaoping** [comment]
https://dev.seafile.com/seahub/f/7da58e8143814e448940/?dl=1

I'm really sorry that the logs cannot be collected due to some bugs in the last test package. Please reinstall the new test app.

very sorry , please forgive me

**Comment by maxiaoping** [comment]
https://dev.seafile.com/seahub/f/7da58e8143814e448940/?dl=1

I'm really sorry that the logs cannot be collected due to some bugs in the last test package. Please reinstall the new test app.

very sorry , please forgive me

**Comment by xobs** [comment]
Sure, though the new version only gives slightly more information:

```
2021-07-30 22:01:29    d    Utils    phoneModelInfo-------HUAWEI/VOG-L29/10
2021-07-30 22:02:03    d    Utils    ---------DownloadTask---54line---23898b31-5c7d-4ee0-a2d7-08b4d2bcd2b0---/seafile-ignore.txt---67---Music
2021-07-30 22:02:03    d    Utils    ----------initWidgets---/seafile-ignore.txt
2021-07-30 22:02:03    d    Utils    --------getDownloadLink-------"/seafhttp/files/5d1b88fb-b8b7-4975-ace5-de5df786fe0b/seafile-ignore.txt"
2021-07-30 22:02:03    d    Utils    ------DownloadTask--104--------1
2021-07-30 22:02:03    d    Utils    ------DownloadTaskManager--------1
2021-07-30 22:02:03    d    Utils    ------BrowserActivity--2109--------1
```

Interestingly, `/seafhttp/files/5d1b88fb-b8b7-4975-ace5-de5df786fe0b/seafile-ignore.txt` appers to be a URL that works exactly once. If I take that and put it into my desktop web browser, it succeeds in downloading it the first time, and says `Bad access token` if I try to download it a second time. So the download link appears to be correct, but maybe the program never actually tries to fetch the URL?

**Comment by maxiaoping** [comment]
Can you test more files and provide more download links to the log?

I presume that the download link is wrong, and I need to further debug and troubleshoot the problem.

Here is the correct download log for my test.
![image](https://user-images.githubusercontent.com/7161204/127759480-25c84aaa-7078-4a73-b187-93bd547bd94b.png)

**Comment by xobs** [comment]
Here I have tried to download three files:

```
2021-08-01 12:48:06    d    Utils    phoneModelInfo-------HUAWEI/VOG-L29/10
2021-08-01 12:48:15    d    Utils    ---------DownloadTask---54line---a15ffff4-4685-48cf-9ed7-abfd4b8e91a2---/openauto-notes.txt---2314---Ion Mobility
2021-08-01 12:48:15    d    Utils    ----------initWidgets---/openauto-notes.txt
2021-08-01 12:48:15    d    Utils    --------getDownloadLink-------"/seafhttp/files/03842949-de6f-4dae-92e9-b53ab70b5fe7/openauto-notes.txt"
2021-08-01 12:48:15    d    Utils    ------DownloadTask--104--------1
2021-08-01 12:48:15    d    Utils    ------DownloadTaskManager--------1
2021-08-01 12:48:15    d    Utils    ------BrowserActivity--2109--------1
2021-08-01 12:48:24    d    Utils    ---------DownloadTask---54line---3a8a221d-4109-4b5c-80f6-8a300292a307---/How_to_install_and_configure_ExaGear_Desktop.pdf---1947170---Exagear
2021-08-01 12:48:24    d    Utils    ----------initWidgets---/How_to_install_and_configure_ExaGear_Desktop.pdf
2021-08-01 12:48:24    d    Utils    --------getDownloadLink-------"/seafhttp/files/4fd020d0-01fc-4473-ad40-4a52a319625d/How_to_install_and_configure_ExaGear_Desktop.pdf"
2021-08-01 12:48:24    d    Utils    ------DownloadTask--104--------2
2021-08-01 12:48:24    d    Utils    ------DownloadTaskManager--------2
2021-08-01 12:48:24    d    Utils    ------BrowserActivity--2109--------2
2021-08-01 12:48:37    d    Utils    ---------DownloadTask---54line---3d88a571-c8df-420c-b788-c654b90eae65---/Sketchup-pic.PNG----1---Renovation
2021-08-01 12:48:37    d    Utils    --------getDownloadLink-------"/seafhttp/files/1c05e5af-0929-4693-a41c-8db8fdef6b17/Sketchup-pic.PNG"
2021-08-01 12:48:37    d    Utils    ------DownloadTask--104--------1
2021-08-01 12:48:37    d    Utils    ------GalleryActivity--------/---Sketchup-pic.PNG
2021-08-01 12:48:37    d    Utils    ---------DownloadTask---54line---3d88a571-c8df-420c-b788-c654b90eae65---/Sketchup-pic.PNG----1---Renovation
2021-08-01 12:48:37    d    Utils    --------getDownloadLink-------"/seafhttp/files/1bf33eaa-01cc-45cc-9d9a-1d9dadadedce/Sketchup-pic.PNG"
2021-08-01 12:48:37    d    Utils    ------DownloadTask--104--------2
2021-08-01 12:48:37    d    Utils    ------GalleryActivity--------/---Sketchup-pic.PNG
2021-08-01 12:48:37    d    Utils    ---------DownloadTask---54line---3d88a571-c8df-420c-b788-c654b90eae65---/Sketchup-pic.PNG----1---Renovation
2021-08-01 12:48:37    d    Utils    --------getDownloadLink-------"/seafhttp/files/ebe1a304-d643-42fc-ba6d-f0aa899923bd/Sketchup-pic.PNG"
2021-08-01 12:48:37    d    Utils    ------DownloadTask--104--------3
2021-08-01 12:48:37    d    Utils    ------GalleryActivity--------/---Sketchup-pic.PNG
2021-08-01 12:48:52    d    Utils    phoneModelInfo-------HUAWEI/VOG-L29/10
```

The first two files gave me the usual "Download Error" message that was mentioned in the original bug report. The third file is a PNG. The thumbnail displayed correctly, but when I tapped the "Download" button it presented a dialog box that said "Downloading files..." that never finished, and I had to force-close the program.

**Comment by maxiaoping** [comment]
“/seafhttp/files/5d1b88fb-b8b7-4975-ace5-de5df786fe0b/seafile-ignore.txt”
Are you correct in saying that this URL can be downloaded directly from your browser on your PC?

**Comment by xobs** [comment]
Yes, that can be downloaded directly from any device anywhere. It will work exactly once. For example:

```
user@Ondo:~$ wget https://nas.xobs.io/seafhttp/files/1c05e5af-0929-4693-a41c-8db8fdef6b17/Sketchup-pic.PNG
--2021-08-01 13:19:32--  https://nas.xobs.io/seafhttp/files/1c05e5af-0929-4693-a41c-8db8fdef6b17/Sketchup-pic.PNG
Resolving nas.xobs.io (nas.xobs.io)... 132.147.96.146
Connecting to nas.xobs.io (nas.xobs.io)|132.147.96.146|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 319969 (312K) [image/png]
Saving to: ‘Sketchup-pic.PNG’

Sketchup-pic.PNG        100%[=============================>] 312.47K  --.-KB/s    in 0.003s

2021-08-01 13:19:32 (95.0 MB/s) - ‘Sketchup-pic.PNG’ saved [319969/319969]

user@Ondo:~$ wget https://nas.xobs.io/seafhttp/files/1c05e5af-0929-4693-a41c-8db8fdef6b17/Sketchup-pic.PNG
--2021-08-01 13:19:43--  https://nas.xobs.io/seafhttp/files/1c05e5af-0929-4693-a41c-8db8fdef6b17/Sketchup-pic.PNG
Resolving nas.xobs.io (nas.xobs.io)... 132.147.96.146
Connecting to nas.xobs.io (nas.xobs.io)|132.147.96.146|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2021-08-01 13:19:43 ERROR 400: Bad Request.

user@Ondo:~$
```

**Comment by freeplant** [comment]
@xobs Can you try to check the value of  FILE_SERVER_ROOT in your seahub_settings.py? Normally, it should start with https://

**Comment by xobs** [comment]
It's set to the following:

```
FILE_SERVER_ROOT = "/seafhttp"
```

It starts to work if I update that variable to include the whole URL rather than just the root.

**Comment by xobs** [comment]
Would it make sense to add a check to ensure `FILE_SERVER_ROOT` is a valid URL, as opposed to the infinite loop that it gets into now?

**Comment by freeplant** [comment]
According to the manual, it should including the domain part  ("https://" part) . It works well so far.

**Comment by xobs** [comment]
Thank you for your help! I'm sorry for taking up your time. I hope that this bug report can help future users resolve this issue if they encounter it.
