### ISSUE TITLE
Cannot see shared link, it creates everytime a new one

### ISSUE THREAD

**Issue by Schroeffu** [haiwen/seadroid#901]
Hi Seadroid Team,

when sharing a file with a link in the android app, then choose again "share" > share link (no password), the app is generating a new share link and the old one is not active anymore.

I cannot see the old shared link to re-use it anywhere.

In the WebUI everything works.

Android App 2.2.39
Server 7.1.15

Thanks for watching this issue!

**Comment by maxiaoping** [comment]
As soon as the shared link is regenerated for the same file, the old link will expire

**Comment by Schroeffu** [comment]
> As soon as the shared link is regenerated for the same file, the old link will expire

exactly this is the issue: if there is already a shared link, the old link will expire. but i want to copy & paste the old link again to share again. this seems not possible. android app is overwriting the shared link again and again.
