### ISSUE TITLE
click edit  but not enter edit-interface, go to main list interface

### ISSUE THREAD

**Issue by saleo** [haiwen/seadroid#914]
i can open file but when click the edit icon on the top-right, it go back to main list interface.

tried the version before 2.2.41 and 2.2.41 , both work as above

**Comment by maxiaoping** [comment]
I have tested the txt and md files and there is no problem. What type of file are you opening?

**Comment by saleo** [comment]
md files, thanks

**Comment by saleo** [comment]
It's okay now ，although I did not do anything.
