### ISSUE TITLE
SSL issue if using Cloudflare Proxy with TLS 1.3

### ISSUE THREAD

**Issue by Florian-Sabonchi** [haiwen/seadroid#915]
![IMG_20211102_152743_345.jpg](https://user-images.githubusercontent.com/54689374/139866848-0ff376fb-e512-4ce4-9f44-190c062a8ff5.jpg)

**Comment by louisroyer** [comment]
I think this issue is a duplicate of #890.

**Comment by Florian-Sabonchi** [comment]
> I think this issue is a duplicate of #890.

Closed
