### ISSUE TITLE
no up/download 

### ISSUE THREAD

**Issue by umbm** [haiwen/seadroid#918]
No working up/download or sync at android 11. Access to android file system is granted, I can browse the library at server and can see thumbnails, but every up or download ends in error. 
The windows client is working as usual with seafile server. 
Is there a general android problem? Most of personal local cloud system apps (nextcloud, synology...) got common problems last weeks.

**Comment by maxiaoping** [comment]
please provide the log file under the "/0/Android/media/com.seafile.seadroid2/Seafile/xxxx-xx-xxLog.txt "path

**Comment by umbm** [comment]
For me it's solved without fix the problem. 
I switched to an other system...
