### ISSUE TITLE
Thumbnails and pictures not showing using self signed certificate

### ISSUE THREAD

**Issue by GitMastic** [haiwen/seadroid#924]
Hello,

I converted my self hosted seafile (Apache2+MySQL) to HTTPS using a self signed certificate (since this is a local server). Everything was working fine, also everything is still working fine on Windows and Web version. 

However on the android application the thumbnails do not load anymore and the pictures show a black screen if I enlarge them. I can however download them and any other file.

I had a look at the apache error.log, there is a bunch of "unknown certificate" errors and the client reject the connection (although I accepted the certificate in the app when connecting).

My guess is that the app itself is OK with a self signed certificate but another component (webview?) is not.

The issue was also discussed there:

https://forum.seafile.com/t/seafile-android-client-2-2-34-photo-preview-doesnt-work/14630

**Comment by XaapX** [comment]
Bumping this as I have been affected by this issue for a long time.
I cannot confirm the self signed certificate theory (though I do use a self signed cert) but I have the same consequences:
-Image files have no thumbnail
-Opening a non-downloaded image is just a forever black screen
-Downloading manually first lets then open the image but still no thumbnail

I was not able to find any errors about certs in all nginx & seafile logs while opening libraries.

Thumbnails work fine in web interface.

I finally took some time to identify the regression point and for me it appeared in between 2.2.28 and 2.2.30
2.2.30 -> no thumbs, no auto image DL
2.2.28 -> all working fine

There are not many commits but I'm not able to bisect/build...

OP, can you maybe confirm if 2.2.28 works for you? (you can install them from the apk in release page, downgrading was only possible by uninstalling first on my android)

**Comment by XaapX** [comment]
I was able to bisect between 2.2.28 and 2.2.30.
This is the very last commit (2.2.30 which is **f6ba277f0f8**) that breaks thumbnails on my device.

For reference this commit is not so big, it seems to indeed change mainly how images are loaded (moves from lib nostra13/Android-Universal-Image-Loader to _glide_).

Probably a consequence of that change is how images are fetched from the network. There may be regressions with self signed hosts when fetching through this new library? For reference I am on a fairly old device (Galaxy S7, android 8 Oreo).

Unfortunately I am not comfortable enough with android development to debug this...

I've seen those posts that seem related:
https://forum.seafile.com/t/solved-android-trust-anchor-for-certification-path-not-found/6665
https://forum.seafile.com/t/bug-valid-personal-certificate-detected-as-invalid-on-seadroid/6373

I do have the following exception when seadroid tries to load the thumbnails:
```
03-02 14:18:59.834 17863 17863 W Glide   : Load failed for https://XXXXX/api2/repos/64c7aa4e-3eec-49c3-884c-XXXXX/thumbnail/?p=%2FXXXX.JPG&size=157 with size [157x157]
03-02 14:18:59.834 17863 17863 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-02 14:18:59.834 17863 17863 W Glide   : There was 1 cause:
03-02 14:18:59.834 17863 17863 W Glide   : javax.net.ssl.SSLHandshakeException(java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.)
03-02 14:18:59.834 17863 17863 W Glide   :  call GlideException#logRootCauses(String) for more detail
03-02 14:18:59.834 17863 17863 W Glide   :   Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
03-02 14:18:59.834 17863 17863 W Glide   : There was 1 cause:
03-02 14:18:59.834 17863 17863 W Glide   : javax.net.ssl.SSLHandshakeException(java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.)
03-02 14:18:59.834 17863 17863 W Glide   :  call GlideException#logRootCauses(String) for more detail
03-02 14:18:59.834 17863 17863 W Glide   :     Cause (1 of 1): class javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
03-02 14:18:59.834 17863 17863 I Glide   : Root cause (1 of 1)
03-02 14:18:59.834 17863 17863 I Glide   : javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1477)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1423)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1367)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:219)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:142)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:410)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:343)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:489)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:104)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
03-02 14:18:59.834 17863 17863 I Glide   :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-02 14:18:59.834 17863 17863 I Glide   :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-02 14:18:59.834 17863 17863 I Glide   :      at java.lang.Thread.run(Thread.java:764)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
03-02 14:18:59.834 17863 17863 I Glide   : Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:739)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:612)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:499)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:422)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:343)
03-02 14:18:59.834 17863 17863 I Glide   :      at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
03-02 14:18:59.834 17863 17863 I Glide   :      at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:203)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:607)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
03-02 14:18:59.834 17863 17863 I Glide   :      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
03-02 14:18:59.834 17863 17863 I Glide   :      ... 22 more
03-02 14:18:59.834 17863 17863 I Glide   : Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
03-02 14:18:59.834 17863 17863 I Glide   :      ... 33 more
```

I tried:
- Generating my own CA and sign the final cert with it : no change
- Install those two certs (root ca and seafile) locally on the device : no change

I did not try to use a known "system" root CA though...

In the end I simply used the last known good commit (parent of 2.2.30) , bumped version to 999 and installed this locally so the play store does not try to update it.

**Comment by XaapX** [comment]
Hello,

I gave it another try and I finally got it to work.
My earlier attempt to use a self signed CA was not done correctly in my last post : I forgot to setup nginx to actually send the CA cert along twith the server cert. (They need to be concatenated)...

Now it works!
And thumbnails display is actually so much quicker than with previous non-glide lib!

So to summarize:

- Single key+self signed cert -> no thumbnail, no preview and CertificateException :x: 
- Self-signed CA cert + cert signed by this CA -> all good :heavy_check_mark: 

**Also very important** : do retrieve the root CA certificate the server now uses to your android client and open it through your file explorer and add it to whitelist it locally, otherwise it does not work either.
And do not forget it to concatenate server and CA certs to one single file to be used as a cert if using nginx.

Btw this is the guide I used to generate the keys, CA cert, CSR and sign it :
https://www.golinuxcloud.com/create-certificate-authority-root-ca-linux/
(I just didnt use the -passin thing but it's probably irrelevant)

**Comment by zar3bski** [comment]
Hi, 

I encounter a similar issue with version 3.0.9 using a full [root + intermediary + leaf] certificate. All the android apps for the different services (bitwarden, different browsers) accept this cert but Seadroid 
- refuses to load images and to download files (*not trusted SSL server*) while
- it sends the authentication info during logging without any complain
