### ISSUE TITLE
Detect AsciiDoc files also as plain text (and make them editable)

### ISSUE THREAD

**Issue by sdaschner** [haiwen/seadroid#929]
When AsciiDoc files are also detected as plain text, they'd open up in the same editor, which would be really helpful. Even if the editor wouldn't (yet) support the AsciiDoc syntax, this would greatly benefit users with reading/writing those files on the go. WDYT?

PR #920 should fix this.

**Comment by maxiaoping** [comment]
Version 2.2.47 has been resolved
