### ISSUE TITLE
2.2.44 Network Error but still uploading

### ISSUE THREAD

**Issue by matoq** [haiwen/seadroid#931]
I run 2.2.44 on an Android device (microG for LineageOS, 17.1 = Android 10) and a private seafile server with a self-signed certificate. 

The app came from F-Droid.

The app can't display any libraries citing a "network error". An attempt at re-login fails some time after password input with that same "network error".

HOWEVER

The app STILL uploads jpgs from my camera app's save folder. I can collect them from seafile on my computer.

Clearly, everything else is working smoothly. No changes were made to the seafile setup.

**Comment by maxiaoping** [comment]
Can you provide a screenshot of the error message?

**Comment by matoq** [comment]
It's in German and reads "error loading libraries. tap to try again."

![screen](https://user-images.githubusercontent.com/98488557/163717369-6a072705-4690-4ff2-bad2-d73b2837b249.png)

Note the "network error" overlay at the bottom center.

The app is set to sync photo folders to the server. I can access and download all my recent photos via the desktop client.

So it's clearly a very strange app problem, not wanting to show any libraries, while the server works fine.

**Comment by maxiaoping** [comment]
The network request for your current page is in error, but the album synchronization function is not affected.

**Comment by matoq** [comment]
indeed. access to all content works on the mobile device via seafile's integration with the andoid (LineageOS) file browser.

**Comment by maxiaoping** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/7161204/164593150-67cce88a-67a1-4bbb-97dc-4c6ac4956738.png">
Please check the network request on your current page
