### ISSUE TITLE
2.2.44 Open files in external apps broken

### ISSUE THREAD

**Issue by ggogel** [haiwen/seadroid#932]
How to reproduce: Open a file that requires an external app from within Seadroid, such as a PDF. Select the external app. File will not be opened.
Expected behavior: File is opened. Feature works in 2.2.42.

Files are actually downloaded correctly and be opened from a file explorer app.

**Comment by maxiaoping** [comment]
I tried to use my two test phones to test, both phones have no problem[
![image](https://user-images.githubusercontent.com/7161204/163659722-a3ec0061-28c8-43e0-b96b-d30769cfc69f.png)
](url)
[
![image](https://user-images.githubusercontent.com/7161204/163659737-72ef370c-e5a9-4ded-b6f8-d19b6ae23d2d.png)
](url)

**Comment by maxiaoping** [comment]
[](url

https://user-images.githubusercontent.com/7161204/163659810-422c279a-bd3d-4e29-ab34-50560d82eb60.mp4

)2.2.44

**Comment by maxiaoping** [comment]
Version 2.2.44 Tested
[](url

https://user-images.githubusercontent.com/7161204/163659974-82ab3fe4-9586-4978-9d14-a27cb5287383.mp4

)

**Comment by seidler2547** [comment]
I have this problem, too. Android 12 on Samsung Galaxy S10e.

**Comment by seidler2547** [comment]
https://user-images.githubusercontent.com/729588/166155751-98ced979-43cf-401a-a53e-3b1bc4bd0c6a.mp4

**Comment by ggogel** [comment]
> I have this problem, too. Android 12 on Samsung Galaxy S10e.

The issue on my phone is exactly the same as in your video. I tried several different PDF apps.

Android 11, OnePlus 8T

**Comment by j6b72** [comment]
I've got the same problem. Pixel 6 with Android 12

**Comment by j6b72** [comment]
The issue only seems to appear if the app was installed from the google play store - if i use the supplied version from the releases tab on this github page, even if the version numbers match the ones from the play store, this issue doesn't appear.

Tested on the android studio emulator pixel 5 with android 12

**Comment by maxiaoping** [comment]
Has been modified.

Version 2.2.45 has been updated on the Google Play Store.

**Comment by ggogel** [comment]
@maxiaoping Thank you. Version 2.2.45 fixed the issue 👍
