### ISSUE TITLE
Consider refactoring of transfer package

### ISSUE THREAD

**Issue by alfh** [haiwen/seadroid#94]
I've been looking at the code in the transfer package, and I think a refactoring of the code might be needed. To me, there seems to be too much code duplicationg, and things not working the same way for upload/download when it should, for example cancelling of downloads do not seem to be handled / supported.

To me, it seems like one could make a TransferTask and TransferTaskInfo, and use those. Perhaps, if needed, one could have a UploadTask/UploadTaskInfo and a DownloadTask/DownloadTaskInfo, extending the TransferTask/TransferTaskInfo.

Improving the quality of this central package would be nice.

Also, I think the GUI itself should get a "Download" fragment/tab, just like it has a "Upload" fragment/tab. This way, one could support downloading a whole folder, and then having each individual download appearing in the "Download" tab. There should be a separate issue for this, but I did not want to make it now, I want some discussion first if it is needed.

Also, I think it needs to be considered what part of the code should have the responsibility to check whether a file should be uploaded or an update should be performed of an existing file. To me, it seems like this fits at a low level like in the transfer package. As of now, for example, if I try to upload an image, and it already exists in the same folder on the server, I get a duplicate file in that folder, instead I think the transfer package should detect that the file already exists on the server, and since there are no changes for the file on the server and the client, nothing should be done.

The transfer package should also be responsible for "restarting" uploads/downloads after the application has been exited and started again. I am not sure if the transfer package is doing that currently.

It would also be nice if the transfer package could do a "sha sum" of the file on the client, and get the "sha sum" of the file on the server, and if they match, and it is a "update" request, then the client would not have to transfer the file to the server, This would save bandwith.

These are some of my thoughts, I appreciate some feedback.

**Comment by Logan676** [comment]
this PR, transfer manager #192, solves most of the request as you mentioned above, including
- [x] cancelling of downloads
- [x] refactor and abstract base classes like, `TransferTask` and `TransferTaskInfo`
- [x] GUI part, added the "Download Task List" tab
- [x] support downloading a whole folder
- [x] having each individual download appearing in the "Download Task List" tab
- [x] photo backup module now supports restarting uploads/downloads when restart the app
- [ ] check file should be uploaded/update not implemented yet
- [ ] add "sha sum" of the file not implemented yet

BTW, this issues feels like an inspiration to me, thanks!
