### ISSUE TITLE
How to share folder with other users of the same server?

### ISSUE THREAD

**Issue by KeenMaron** [haiwen/seadroid#941]
Hi,

i'm just wondering why i can't share folders via user-specific sharing? It is easily possible via web browser?

I can only create a sharing link but i want to share it with a group of user on the seafile server or a few users.

Is this planned to be implemented?

**Comment by freeplant** [comment]
Sharing to specific people should be done with the Web UI. We don't have a plan to implement it at the mobile client.

**Comment by KeenMaron** [comment]
Ok too bad :(. I think this should be handled as a major feature in these days of excpecting more and more smooth UX.
