### ISSUE TITLE
"Export" only shows bluetooth

### ISSUE THREAD

**Issue by qinq-net** [haiwen/seadroid#942]
Version 2.2.46/47 on Xiaomi 12S Ultra

"Export"ing file only shows "Bluetooth", no other apps. The permission for listing apps has been granted.

![Screenshot_2022-08-13-10-16-57-939_com seafile seadroid2](https://user-images.githubusercontent.com/14189352/184464908-2d172d33-5a6f-41ec-80a2-9b6ef55e35fa.jpg)

![Screenshot_2022-08-13-10-18-21-929_com miui securitycenter](https://user-images.githubusercontent.com/14189352/184464911-82956589-cb3a-497f-85da-75b5d55f9fa5.jpg)

**Comment by maxiaoping** [comment]
Version 2.2.48 will solve this problem more, please note the update.

**Comment by maxiaoping** [comment]
2.2.48 A version has been released. Please update it.
