### ISSUE TITLE
GPS Position is set to null for uploaded images

### ISSUE THREAD

**Issue by mkobel** [haiwen/seadroid#946]
It's probably the same issue as https://github.com/nextcloud/android/issues/6248

> Stripping EXIF data is part of the android Q privacy feature set.
> Starting with Android 10 (or 11?), apps need to explicitly specify that they want to receive Metadata.
> https://github.com/nextcloud/android/issues/6248#issuecomment-1147167524

Granting more permissions might help: https://github.com/nextcloud/android/issues/6248#issuecomment-1207315271

**Comment by rikrdo89** [comment]
I have the same issue using Seadroid v2.2.46, and android  v13 on a google pixel 5... I just realized that the photo upload feature in  seafile for android has been stripping all GPS information from the exif data of all my jpgs.... now I have thousands of backed up photos without GPS info. Has anyone found a fix or way around this issue?

**Comment by mavinV6** [comment]
Same problem on Xiaomi Mi 9T Pro with Android 11.

The GPS information is removed only if the photo was uploaded via auto upload.
If you upload a photo manually, the GPS information remains.

**Comment by Hobby-Student** [comment]
same problem here. Android Seafile 2.2.46

**Comment by rikrdo89** [comment]
any news on this issue? any plans to allow GPS info to be included in the seadroid uploads?

**Comment by gschintgen** [comment]
Wow, I've recently stumbled over this **DATA LOSS bug**.

I am so fortunate that my device is only at 94% storage and I did not yet delete my original pictures. At first I was furious at Seafile, only to realize that the outcome (nulled location or preserved) was almost random, depending on whether I use Seadroid's auto-backup (removes location), android-share it from FileManager+ or android-share it from f-Stop.

Still: Seadroid *must* do everything it can to prevent data loss, in particular when it comes to its auto-backup function!

**Comment by gschintgen** [comment]
My pictures are fine till 2020-09, then starting in 2020-10 my photos have nulled location data. "Coincidentally", Android 11 was released on September 8, 2020 and was (probably) the first Android release which changed the relevant APIs for privacy reasons. (See the already linked [comment](https://github.com/nextcloud/android/issues/6248#issuecomment-1147167524) on nextcloud's corresponding issue.)

**Comment by gschintgen** [comment]
I don't know anything about Android development, but the fix *may* be rather simple. It seems to me that the app needs
* an additional permission: https://developer.android.com/reference/android/Manifest.permission#ACCESS_MEDIA_LOCATION
This is also  [part of the proposed(?) fix for nextcloud](https://github.com/nextcloud/android/commit/b8791e2dfd4a5aa87fc9d4b02402e9a08e3fd2af).
* to explicitly ask for the original unmodified media contents. This is potentially as simple as adding a single library call: https://developer.android.com/reference/android/provider/MediaStore#setRequireOriginal(android.net.Uri)
"This can be useful when the caller wants to ensure they're backing up the exact bytes of the underlying media, without any Exif redaction being performed."

It'd be nice to have some feedback from the developers. Thanks.

**Comment by tubezleb** [comment]
I got this issue too, still no fix?

This is a big loss of data's for people's relaying on the mobile app to save pictures to seafile.

**Comment by GiMo84** [comment]
I was facing the same issue, since the upgrade of my phone to a model running Android 13 (Pixel 7a).
I tried [this](https://github.com/nextcloud/android/issues/6248#issuecomment-1510383027) fix, took a picture and checked what had been uploaded to Seafile, and this time it contained all the exif location info!

**Comment by rikrdo89** [comment]
@GiMo84 Thanks lot. This worked for me, now all my exif location data is being synced. 
For those of you who may be in the same situation, here is a brief explanation. Seafile in android requests access to your photos and videos, and once those permissions are granted, it syncs files with the BIG issue of not syncing exif data. You need to, inaddition, manually grant permission to ALL FILES from within `Permission Manager`. Below is where I found Permission Manager in my Google Pixel 5. It is not as easy to find:

`Settings> Security & Privacy > Privacy > Permission Manager > Files  > See more apps that can access all files > Seafile`

**Comment by zhwanng** [comment]
Please update to the latest version to verify this, and if the issue reappears with the new version, it will be re-opened.
