### ISSUE TITLE
Error getting starred files / starred-items on seafile server <=6.2.5

### ISSUE THREAD

**Issue by rcoss** [haiwen/seadroid#947]
Between seadroid v2.2.25 and v2.2.26 the method for getting starred files changed from GET /api2/starredfiles to GET /api/v2.1/starred-items. The latter does not work on seafile server v6.2.5 or earlier. I can't find an announcement for that change. In the current code the former method is still there, but it is commented out: line 348 in
[https://github.com/haiwen/seadroid/blob/a2f4d2a0214582530672ec1413c90cd29c79a6d3/app/src/main/java/com/seafile/seadroid2/SeafConnection.java](url)
Setting and unsetting star to files still works with seadroid v2.2.48 and server v6.2.5.

**Comment by freeplant** [comment]
We does not support server v6. It is better to upgrade to newer versions.
