### ISSUE TITLE
[BUG] Upload/download failed when seafile server FILE_SERVER_ROOT host doesn't match SERVICE_URL host and FILE_SERVER_ROOT use HTTPS

### ISSUE THREAD

**Issue by kuresaru** [haiwen/seadroid#948]
## Version
- seadroid 2.2.46
- seafile server 9.0.4 on Debian 11

## Problem
Can't upload or download any files with seadroid, and no any requests in seafhttp nginx access log. **But in same config, seahub web works OK.**

## Reappear
Seafile server on server A, nginx on server A proxy pass to local seahub port 8000, nginx on server B proxy pass to server A seafile port 8082, and both nginx use https. *(Nginx on server B use http will works OK.)*

**In some special reason, I can't use nginx on same server to access seahub and seafhttp.**

**Comment by kuresaru** [comment]
I think this problem caused [here](https://github.com/haiwen/seadroid/blob/a2f4d2a0214582530672ec1413c90cd29c79a6d3/app/src/main/java/com/seafile/seadroid2/SeafConnection.java#L798)...

**Comment by maxiaoping** [comment]
You can update the latest version of seadroid to test it

**Comment by kuresaru** [comment]
> You can update the latest version of seadroid to test it

I upgrade to seafile server 9.0.9 and seadroid 2.2.48, and the problem is still.
