### ISSUE TITLE
Can't add account

### ISSUE THREAD

**Issue by willthong** [haiwen/seadroid#952]
Hi! I'm getting the same problem as [this very old issue](https://forum.seafile.com/t/solved-android-app-account-disappears/4947/12): whenever I put in account login details for my "Other Seafile Server", when I submit the details it throws me right back to the "Add Account" screen without adding the account. The same happens when going through the "Accounts & Sync" page of my Android Settings. I have tried deleting the app and all of its data, and reinstalling it, as well as a different Seafile account. My phone appears in the Admin interface, and I've tried logging in after deleting it from the Admin interface too, but no joy.

My phone doeesn't have an SD card so I don't know what could be causing it. I'm running Seadroid 2.2.46 and Android 11. Thanks for any help!

**Comment by maxiaoping** [comment]
Please update the latest version 2.2.48 and then test whether there is the same problem.

**Comment by willthong** [comment]
Updated to 2.2.48 via the APK on this GitHub, deleted app cache and data, but same problem.

**Comment by zhwanng** [comment]
We closed this issue, you can verify it with the latest version, and if the issue reappears with the new version, reopen it.
