### ISSUE TITLE
No `open with` option for some file types

### ISSUE THREAD

**Issue by seekstar** [haiwen/seadroid#953]
For example, there is an `open with` option for `.sh` file type:

![Screenshot_20221119_140733_com seafile seadroid2](https://user-images.githubusercontent.com/33680208/202837184-cac7729e-e2a1-4860-a4ed-385fa84ef41f.jpg)

However, the option is not available for the `.yaml` type:

![Screenshot_20221119_140945_com seafile seadroid2](https://user-images.githubusercontent.com/33680208/202837246-3eba5f0c-4ca2-4e63-9ca8-7b8635026b6f.jpg)

**Comment by maxiaoping** [comment]
The latest version supports .sh file editing.However, direct editing of yaml files is not supported

**Comment by seekstar** [comment]
Not being able to direct edit is fine for me. But not being able to open the file with other apps is not.

**Comment by maxiaoping** [comment]
The file format is too special, you can choose to export the file.
