### ISSUE TITLE
F-Droid can not update because Seadroid uses upstream repo

### ISSUE THREAD

**Issue by chtfn** [haiwen/seadroid#96]
I saw that the version of the Android client is stuck at 8.2 on the F-Droid repo. It is explained on the [wiki](https://f-droid.org/wiki/page/com.seafile.seadroid2) that it is because it "uses upstream's own maven repo".

Is there anything that can be done in order to get the latest version of the client for F-Droid users?

Cheers

**Comment by OuTopos** [comment]
Any update on this?

Seafile is such a nice piece of software, please keep it FOSS.

Thank you.

**Comment by rdsqc22** [comment]
Seadroid is still FOSS, it just hasn't updated on Fdroid. Every week or so I clone the repo and build the app myself from source, it works just fine.

**Comment by Logan676** [comment]
Edition updates only published via Google Play and official Seafile website. The dev team has little time to study how to publish the updates through the third party App Store, like F-droid. Anyone who are interested in publishing the updates is more than welcome. Thanks.

Regards

**Comment by mrjovanovic** [comment]
F-Droid maintainers do it themselves, the issue according to them is that Seadroid [uses binaries from an upstream maven repo](https://gitlab.com/fdroid/fdroiddata/issues/37).

**Comment by Logan676** [comment]
this was fixed by [this commit](https://gitlab.com/fdroid/fdroiddata/commit/fe7f6bfc553c29b703ba373cb509bd6d9232f9ad), you can download Seafile1.4.2 by F-Droid now.

**Comment by mrjovanovic** [comment]
Installs fine, thanks.
