### ISSUE TITLE
Downloading large amount of file gets stuck after a while

### ISSUE THREAD

**Issue by FluffyDiscord** [haiwen/seadroid#970]
App downloading gets stuck while downloading large amount of files.

The transfer list no longer updates and restarting/killing the app removes all files from the transfer list, so I have to manually re-add all files which start downloading again, even though they are already downloaded.

Unacceptable behavior. 

The library is around ~200GB - files ranging from 5MB to 600MB

This has been an issue from day 0 using this app. Is there absolutely nothing to be done to fix it? The desktop clients are fantastic, why is this android app lacking these basic features?

**Comment by zhwanng** [comment]
please update to the latest release and try it.
