### ISSUE TITLE
"let me pick my photo albums" lets me choose only from unique folder names

### ISSUE THREAD

**Issue by peemot** [haiwen/seadroid#976]
New Sony phones have default photo folder named as PHOTOGRAPHY_PRO and seadroid appeared to not find it. So i chose to pick it myself but i couldn't. After some experimenting i found out that if i have folders with photos arranged like that:
DCIM/PHOTOGRAPHY_PRO
Pictures/XXX/2022
Pictures/YYY/2022
Pictures/YYY/PHOTOGRAPHY_PRO
... then the app shows only 2 choices when i chose "let me pick my photo albums":
2022 (path: Pictures/YYY/2022)
PHTOTOGRAPHY_PRO (path: Pictures/YYY/PHOTOGRAPHY_PRO)

When i renamed Pictures/YYY/PHOTOGRAPHY_PRO to Pictures/YYY/PHOTOGRAPHY_PRO_ then i got to choose from 3 different folders:
2022 (path: Pictures/YYY/2022)
PHTOTOGRAPHY_PRO_ (path: Pictures/YYY/PHOTOGRAPHY_PRO_)
PHTOTOGRAPHY_PRO (path: DCIM/PHOTOGRAPHY_PRO)

Seems like there is a constraint to only show each folder name once.

I have app version 2.3.4

**Comment by zhwanng** [comment]
This is similar to the [974](https://github.com/haiwen/seadroid/issues/974) problem, We are optimizing the "Camera Backup Feature"

**Comment by peemot** [comment]
Thanks, seems to be resolved! At least folder with the same name are now selectable for syncing
