### ISSUE TITLE
"Download failed" when downloading from paths including illegal characters.

### ISSUE THREAD

**Issue by ToxicMushroom** [haiwen/seadroid#985]
**Problem**
When trying to download files containing the colon, or files in folders containing the colon; seafile would throw the not very helpful messages: "Download failed".

**Potential solution**
Perhaps pre-download checking could be done to make sure the user is not trying to download illegally named files/paths.
And if they are, show a more friendly error like for example "Illegal character : in path" 

**Discovery**
I found this by checking the logcat output when downloading a failing file, which logged a rename warning here:
https://github.com/haiwen/seadroid/blob/edd86098b5769a8f6da258fb3337653ec4d68b8d/app/src/main/java/com/seafile/seadroid2/SeafConnection.java#L631C1-L635C14

I didn't immediately find an official list of illegal characters but from what I read it seems to be the same as FAT32 ?
https://stackoverflow.com/questions/2679699/what-characters-allowed-in-file-names-on-android

**Comment by zhwanng** [comment]
Is that so?
![Screenshot_20230918_100445](https://github.com/haiwen/seadroid/assets/48609908/e6a1db8e-5566-4764-ad3b-045699339616)

**Comment by ToxicMushroom** [comment]
oops meant colon, not semicolon

**Comment by zhwanng** [comment]
Oh, I also reproduced and got the same test result. we will fix this.

**Comment by zhwanng** [comment]
This issue has been resolved, please download the latest version.
