### ISSUE TITLE
Add Arabic as an option in your transifex project

### ISSUE THREAD

**Issue by tareefdev** [haiwen/seadroid#989]
I would like to contribute to translating the APP into Arabic, however, under the Seadroid project on Transifex, "Arabic" is not an available option. Other related options are, for example, Syrian Arabic, Egyptian Arabic, etc. The difference between both is that "Arabic" represents the Standard Arabic, which, usually, is used in translating UIs across different Arabic countries.

**Comment by freeplant** [comment]
I have approved the request for the language Arabic. Please let me know if you need future help.

**Comment by tareefdev** [comment]
Thanks! I have sent a request to join the project there.

**Comment by freeplant** [comment]
Approved! Thanks in advance.
