### ISSUE TITLE
(feature request) Dark theme

### ISSUE THREAD

**Issue by RenautMestdagh** [haiwen/seadroid#990]
This has already been asked in #879 but since it's almost 3 years later, i thought i could ask this again.
Are there any plans to implement a dark mode in the app? This would be really nice.

**Comment by nixigaj** [comment]
I agree. Dark mode would be really nice.

**Comment by Rescue9** [comment]
Currently working on implementing this.

So far, I have a working theme switch based upon system settings, but the colors are wrong. I also want to implement a Force Dark Mode option in settings. While the toggle is there, it's currently non-functional.  I'm working on fixing everything, but the code changes are extensive.  I can see why the developer didn't want to bother with this. 
https://github.com/Rescue9/seadroid/wiki

**Comment by zhwanng** [comment]
@Rescue9 

We are in the process of refactoring the Seadroid code. If possible, when the refactoring is complete, you can add the code for blackout mode directly in the resource file.

**Comment by Rescue9** [comment]
@zhwanng
Is there a general timeframe on the completion of refactoring?

**Comment by zhwanng** [comment]
> @zhwanng
> Is there a general timeframe on the completion of refactoring? 

At present, we are in the process of reconstruction, and it is expected to be completed in one to two months.

**Comment by DoS007** [comment]
Hi, just wondering: Isn't https://forum.seafile.com the appropriate place for feature requests. I thought github is only for bugs?

**Comment by Rescue9** [comment]
This list explains what the GitHub issues section is for. https://github.com/haiwen/seadroid/labels

**Comment by DoS007** [comment]
@Rescue9 So they both seem to be valid, forum and github for feature requests.

**Comment by JScharloo** [comment]
+1 for this

**Comment by antoniolago** [comment]
This says completed but I don't see any options for dark theme in the app, maybe I'm missing something?
