### ISSUE TITLE
app crash when open file

### ISSUE THREAD

**Issue by JavaSCU** [haiwen/seadroid#992]
click one file, and downloaded successfully. then open it by other app(eg xlsx, docx, pdf) in seafile app, the app crashed.

log:
01-22 10:55:14.585 30296 30296 E AndroidRuntime: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.seafile.seadroid2
01-22 10:55:14.585 30296 30296 E AndroidRuntime: 	at androidx.core.content.FileProvider.getFileProviderPathsMetaData(FileProvider.java:664)
01-22 10:55:14.585 30296 30296 E AndroidRuntime: 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:695)
01-22 10:55:14.585 30296 30296 E AndroidRuntime: 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:645)
01-22 10:55:14.585 30296 30296 E AndroidRuntime: 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:449)
01-22 10:55:14.585 30296 30296 E AndroidRuntime: 	at com.seafile.seadroid2.ui.WidgetUtils.showFile(WidgetUtils.java:257)
01-22 10:55:14.585 30296 30296 E AndroidRuntime: 	at com.seafile.seadroid2.ui.activity.BrowserActivity.onFileSelected(BrowserActivity.java:1576)
01-22 10:55:14.585 30296 30296 E AndroidRuntime: 	at com.seafile.seadroid2.ui.activity.BrowserActivity.onFileSelected(BrowserActivity.java:1600)
01-22 10:55:14.585 30296 30296 E AndroidRuntime: 	at com.seafile.seadroid2.ui.fragment.ReposFragment.onListItemClick(ReposFragment.java:668)
01-22 10:55:14.585 30296 30296 E AndroidRuntime: 	at androidx.fragment.app.ListFragment$2.onItemClick(ListFragment.java:64)
01-22 10:55:14.585 30296 30296 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)

**Comment by mrbeak** [comment]
Not sure if it's the same problem but when I try to open a text file within seafile app, the app crashes. This happens with the newest version 2.3.6 but not with the version from playstore which is currently 2.3.4.
(Android 13 in case this matters)

**Comment by ariloc** [comment]
I've experienced the same issue. I cloned the project and tried to replicate the bug building the debug and release variant, then running them in the emulator, and both worked as expected. I even tried building an apk with the release variant and then installing that one to test it. Also worked with no issues.
At first glance, it seems to be an issue with the release apk on GitHub, which is the only one I was able to replicate the bug with.
Tested on Android 10 (emulator and physical device).

**Comment by zacharywell** [comment]
Same issue when I tried opening or sharing files with 2.3.6. It seems to happen only when the file finish downloading.

**Comment by aschuster** [comment]
Same problem here after updating from 2.3.5 to 2.3.6 on my Pixel 8 using Android 14.

**Comment by zhwanng** [comment]
please  download this release: v2.3.7
