### ISSUE TITLE
Photo upload failing

### ISSUE THREAD

**Issue by Quayyy** [haiwen/seadroid#994]
When trying to upload a photo taken directly through seafile, I sometimes get the error message "upload not possible, path not found"
Taking the photo via the normal camera app and then uploading it as a file works without problems though.
Maybe it happens because my phone can't process the photo fast enough, and by the time seafile checks to upload the photo, the file is not actually finished creating?
I don't really know, but I would love a fix for this issue!
Cheers!

**Comment by zhwanng** [comment]
Can you provide a screenshot of the running and app version and phone model?

**Comment by looric** [comment]
seafile 2.3.6 version, immediately stop work of the application, after you click take photo and upload.
