### ISSUE TITLE
Bug: Favorite folder/directory shown but not clickable (not opening)

### ISSUE THREAD

**Issue by DoS007** [haiwen/seadroid#995]
App-Version: 2.3.4
Seafile-Server: 9.0.15
Android: 14 on Samsung Galaxy A54

Reproduction:
1. Go to webinterface an make a folder your favorite (click on the "star" button). Now it will be shown on the left handside under favorites. And if you go there you can easily access even your maybe deeply nested folder. 
2. Go on your android device and you will see your folder under favorites. Click on it and you will see the "click" but **nothing happens** (i.e. the folder is *not* opened).

![illustraive_recording](https://github.com/haiwen/seadroid/assets/11618958/0dc7c083-e502-4308-9958-bca21fe35384)

**Comment by zhwanng** [comment]
We have found this bug and are waiting for a new version to be released

**Comment by DoS007** [comment]
@zhwanng Thank you very much for that promptly response. Greets DoS007

**Comment by zhwanng** [comment]
please bump to v3.0.3 and retry it.

**Comment by DoS007** [comment]
@zhwanng Hi, i tested one on google play and it works now (nice! :)), but one improvment request: When clicking on the folder the folder itself isn't opend but the parent folder. I think it would be much better, if the folder itself would be opend because otherwise there is always one further click to do (and adding a dummy subfolder just to workaroung this isn't so nice; so direct folder jump and not parent would be better :)).

**Comment by DoS007** [comment]
@zhwanng As an update. It works, the folder opens directly. The animation is only fluently if opening the same folder twice and not when changing. But the functional problem is fixed. Thank you.
